### ISSUE TITLE
Game directory 

### ISSUE THREAD

**Issue by faroukabd000** [stenzek/duckstation#1016]
I am using android with lollipop version
I tried to select game directory but it seems doesn't work
![Screenshot_2020-10-29-10-33-18](https://user-images.githubusercontent.com/64847752/97551411-3dc44980-19d3-11eb-8447-e946b9d8e225.png)

**Comment by stenzek** [comment]
I didn't even know there were any 64-bit phones running Android 5.

The directory selector might require a newer Android version.

**Comment by faroukabd000** [comment]
@stenzek
Lenovo vibe p1am40 is a 64bit with lollipop version.
I tried the emu on mi a3 android 10
But the emu crash when trying to select game directory. 
Cpu sd 665
Gpu adreno 610
Ram 3gb

**Comment by stenzek** [comment]
Are you using the play store version? The crash should hopefully get reported if so.

**Comment by faroukabd000** [comment]
@stenzek
I tried both github and the playstore one

**Comment by stenzek** [comment]
I haven't seen any crashes reported on selecting the game directory in the play store console.

This isn't the only issue I've seen with Android 5.0, so I think it's best to just bump the minimum required version to avoid confusing other users. Sorry that your device won't be supported anymore.

For what it's worth, I don't have any devices which run Android 5 and are 64-bit, but I did try with the emulator and the file selector appeared to work fine. Maybe because it's a Google build...
