### ISSUE TITLE
[SLUS-00707] Silent Hill (NTSC) - Crash Reports

### ISSUE THREAD

**Issue by RaydenX93** [stenzek/duckstation#1051]
Hello,
As previously mentioned on Discord, I'm encountering game crashes which I decided to properly report here on GitHub for study/posterity.

**System Info**
- Win 10 2004 - 64 bit
- Intel Core i7-7700K
- NVIDIA GeForce GTX 1060 6 GB
- Duckstation 0.1-2228-gcf2d9b86 (master)
- SCPH-5501
- cue/bin matches Redump

**Crash 1**
When you enter Balkan Church, there's a dialogue with a lady. The game crashes as soon as the dialogue start. Disabling PGXP solves the issue.

**Crash 2**
After the fight in the amusement park, there's a dialogue with a nurse. The game crashes around the end of the dialogue. Disabling Recompiler and switching to Interpreter solves the issue. PGXP seems not to be the culprit.

I am uploading my memory card, my test index and all my settings below, so that these bugs could be reproduced.
[SH_NTSC_crashreports_20201108.zip](https://github.com/stenzek/duckstation/files/5506095/SH_NTSC_crashreports_20201108.zip)

I hope this proves valuable for the community.

**Comment by Richard-L** [comment]
Exchange with Stenzek on the church: https://discord.com/channels/695640472202379425/695640472202379428/761539042885894186

in simple English: due to enhancements stuff becomes too much and overflows, and breaks.

Other than the places mentioned by Rayden, it also happened to me in the Draw Bridge control room before entering the resort part of Silent Hill. After the amusement park Cybil fight it crashed earlier for me (Dhalia talking down on Alessa). But then also crashed (=freeze) during the cutscene with Lisa (nurse).

Reloading and turning off enhancements for those moments meant everything was fine, so it doesn't seem to be Duckstation's "fault" in that sense. I'm not sure a custom coded solution to make possible enhancements during these moments of the game is feasible, unless a lot of other games should also benefit from it.

**Comment by Tikilou** [comment]
@Richard-L , a good way could be to increase memory allowed to the PsOne emlated.
Actually, it's already possible to overclock CPU, so why not add some extra memory ?

**Comment by Margen67** [comment]
> 
> 
> @Richard-L , a good way could be to increase memory allowed to the PsOne emlated.
> Actually, it's already possible to overclock CPU, so why not add some extra memory ?

#991

**Comment by stenzek** [comment]
Merging with https://github.com/stenzek/duckstation/issues/1457 as the first part isn't considered a bug (PGXP is an enhancement), and the second is the same as the linked issue.

We probably should document the PGXP issue on the wiki though.
