### ISSUE TITLE
Doom and Final Doom look bad in Hardware mode

### ISSUE THREAD

**Issue by ToniBC** [stenzek/duckstation#1063]
The game Doom and Final Doom and some others I think also have errors, they reproduce badly when we use the Hardware mode, both in Libretro and in Standalone. By software it works fine, but we don't have the improvements.

![Doom (USA)-201111-231320](https://user-images.githubusercontent.com/45365478/98870922-53764c00-2474-11eb-821e-a4a47d57748c.png)

This can be fixed, as other emulators such as Beetle PSX HW implemented an option to fix these errors.

![Captura de pantalla 2020-11-11 232045](https://user-images.githubusercontent.com/45365478/98871071-9afcd800-2474-11eb-83da-5aca9c66bb83.png)
![Doom (USA)-201111-231247](https://user-images.githubusercontent.com/45365478/98871079-9fc18c00-2474-11eb-92cc-be0ccf9b526e.png)

The same could be included in this emulator.

Thank you.

**Comment by stenzek** [comment]
This is not a hardware renderer bug - it works fine at 1x. The standalone version forces these games to 1x resolution via the compatibility ini, but because the libretro core downloader only downloads a shared library and nothing else I can't ship it for RetroArch.

Implementing the line hack is pointless for these games because they don't upscale anyway, and it adds a bunch of overhead for every polygon drawn.

I'll probably have to come up with a way of integrating the compatibility ini into the source code for libretro, it's just annoying to have to come up with rubbish like that because the ecosystem doesn't allow for supplementary files.

**Comment by ToniBC** [comment]
It is not necessary to implement the ini, Retroarch allows configuration per game in all emulators, you just have to create a configuration for that game, change the parameters and that's it. The problem is, it doesn't look the same, not even close.

x4 (Hardware)
![Doom (USA)-201112-030635](https://user-images.githubusercontent.com/45365478/98887025-69e0cf80-2495-11eb-94ea-b9909d73ae7d.png)

x1 (Hardware)
![Doom (USA)-201112-030924](https://user-images.githubusercontent.com/45365478/98887071-87159e00-2495-11eb-9b85-4c68488286a1.png)

x1 (Software)
![Doom (USA)-201112-031110](https://user-images.githubusercontent.com/45365478/98887090-94328d00-2495-11eb-9396-d56c767319cd.png)

I understand that an option like this can consume resources, but it is an option, you can disable it. It also consumes resources the resolutions or the x32 supersampling that you can put. Any option that improves or repairs some bugs in some games is well received.

If custom textures are ever implemented, resources will also increase, but they are improvements, you can use them if you want.

Luckily with the launchers we can select with which emulator to launch each game, Doom with Beetle, the pistol ones with Duckstation Standalone, the rest with Duckstation Libretro.

Anyway, thanks for responding. I will remain attentive to the news and bugs reported to me.

**Comment by stenzek** [comment]
> It is not necessary to implement the ini, Retroarch allows configuration per game in all emulators, you just have to create a configuration for that game, change the parameters and that's it. The problem is, it doesn't look the same, not even close.

The problem with this is users have to know there's an issue, and create a custom config, and not post a bug like you did ;) In standalone problematic enhancements are automatically disabled without any user action at all.

I guess I could convert my compatibility ini over as well. Same with integrating the compat list into the core itself. But I have no idea how many users actually use the libretro core, since they don't track downloads, so it's unclear whether it's worth the effort. Based on my own stats, it's approximately 2% of downloads, which is not worth the effort. But I also know most people use the retroarch core downloader, and you're also losing a bit of performance there because they refuse to update the compiler on the buildbot, and last I checked it couldn't do LTO. 

> I understand that an option like this can consume resources, but it is an option, you can disable it. It also consumes resources the resolutions or the x32 supersampling that you can put. Any option that improves or repairs some bugs in some games is well received.

Sure, but those are GPU performance hits, where there's significantly more headroom. Adding an overhead on every **polygon** (of which there can be thousands of per frame) is not an insignificant hit to emulation speed, and carries some penalty even if the enhancement is disabled.

I have some other per polygon checks (texcoord clamping, flipped sprite adjustment) for upscaling, but those cover a wide variety of games, not just a handful, so IMO it's worth the hit.

At the end of the day, I have to decide what enhancements to include while still maintaining a performance target. This is not one of them. If you want a slow emulator with these options, I'd say stick with beetle :)

**Comment by dankcushions** [comment]
the libretro core mupen64plus-nx uses an internal .ini to force certain settings, if their implementation helps: https://github.com/libretro/mupen64plus-libretro-nx/blob/develop/GLideN64/ini/GLideN64.custom.ini

**Comment by stenzek** [comment]
@dankcushions DuckStation is the same. The issue is utilizing it when the only thing you can supply for download is a shared library... only way I can think is to #include the ini in the source, since resource files in PEs aren't exactly cross platform.

**Comment by ToniBC** [comment]
I am not an expert, I only know what I read in various reports from various emulators, but in Retroarch, in the system folder, there are configuration files, mame you have the plugins and ini files, which the emulator itself creates with the configuration, ppsspp other system files you need etc ... so yes you can use an ini.

Other NES and Master System emulators have an internal database to correctly apply the game region if the rom has no header, for example. Mupen apparently has something similar.

You say that you cannot know the downloads of Libretro, it is obvious, to see when they put the new buildbot and they may put it there, but there are many more of us who use Duckstation in Libretro before the standalone version. The reasons are simple, each loose emulator has an interface, some options, etc ... but you cannot apply shaders, bezels, have a nice interface, in the end we launch everything with a Launcher + Retroarch + Standalone, but we have to have everything separated when it could be all united.

Duckstation is a "new" development, I have for the moment replaced Beetle PSX HW with Duckstation because it seems to me that it is in a very good condition and is evolving, but of course, things are missing, such as the implementation of the gun in Libretro, the custom textures , those improvements that I mentioned here, etc ...

Using Retroarch as the only system, Lakka for example, allows me to have a list of PS1 games and launch each one with Beetle or Duckstation, which is appreciated.

I guess part of the feeling is that being inside Libretro, it seems that visibility of the project is lost, but, on the contrary, with the release on Steam, if Duckstation is faster and better than Beetle, it will become the emulator more used, the same thing that happened to Snes9x, GenesisGX, Gambatte, etc ...

People want unified, simple things, they don't want to have 15 emulators, each one with an interface, with different ways of loading things, etc ... All emulators generally need specific adjustments in some games and they cannot always be automated, because they can use hacks, translations, etc ...

I give you an example, in Demul, there are several games that in VGA mode (the progressive one that we could say in Duckstation) does not work, because those games do not support that mode, so in Demul you have to put the interlaced mode and it looks ugly, but then, Flycast (Reicast) does load them, with the resolution improvements and that, then what happens, because they somehow solved that problem. In N64 Parallel, there are games that have an interlaced mode, but they implemented a deinterlacing filter which works quite well, looking at other projects.

And nothing else, I just wanted to express my opinion, since at the moment it is the only thing I can collaborate with, reporting errors.

Thanks for your effort and we hope it continues to improve the project and become the best emulator of all.

**Comment by stenzek** [comment]
The issue is distribution. The libretro core is messy enough already, I don't want to have a self-extracting dll. Better to just embed it...

> You say that you cannot know the downloads of Libretro, it is obvious, to see when they put the new buildbot and they may put it there, but there are many more of us who use Duckstation in Libretro before the standalone version. 

You know, I hear this all the time. But I've never seen any numbers to back it up. Standalone gets around 500-1000 downloads a day, you can check it here: https://somsubhra.com/github-release-stats/?username=stenzek&repository=duckstation (it only shows downloads since the last release, and it's been 2 days).

RetroArch doesn't post any download statistics, so I have no idea how many users there are. But I doubt it gets 1k downloads a day.

**Comment by stenzek** [comment]
The other thing I particularly dislike is the lack of control. Like I said before, you're actually at a disadvantage for using the core downloader in retroarch, not only because you're dependent on them picking up the new build, but like I said they're using an older compiler and refuse to upgrade. So you end up with a potentially out-of-date, as well as slower experience.

And people blame the emulator/core when it's the builder/retroarch's fault...

**Comment by dankcushions** [comment]
my interest is retropie, which uses mostly libretro cores by default (easier to automate their controller configs, consistency in UI, doesn't need mouse + keyboard, vast end system compatibility, etc). cores are distributed within pre-built images for raspberry pis, which has [~1 million downloads per version](https://somsubhra.com/github-release-stats/?username=RetroPie&repository=RetroPie-Setup), but that doesn't include people updating or installing the script manually (as is mandatory for non-pi hardware), or anyone using one of the myriad third party images (booo). retropie also builds its own binaries rather than grab them from the buildbot (i agree - control of the build is important and also the libretro makefiles can be a little wild sometimes). that's millions of users libretro won't be tracking.

duckstation isn't part of retropie yet (working on it! need to wait for [this](https://github.com/libretro/RetroArch/pull/11181) to make it to the next RA release, for one). i am curious to try standalone once it works in KMS/DRM (retropie doesn't use X for pi) and see if it's a good fit (we could potentially add both).

(sorry for adding to the off topic!)

**Comment by stenzek** [comment]
Frontend stats don't really mean anything, since you have plenty of people who will never use a PS1 emulator :)

> duckstation isn't part of retropie yet (working on it! need to wait for this to make it to the next RA release, for one). i am curious to try standalone once it works in KMS/DRM (retropie doesn't use X for pi) and see if it's a good fit (we could potentially add both).

I've hooked up keyboard input for NoGUI now (on a branch), haven't checked controllers yet. I'd be very surprised if it didn't run quicker than Retroarch.
