### ISSUE TITLE
Custom game names/entries in game list

### ISSUE THREAD

**Issue by RaydenX93** [stenzek/duckstation#1077]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to change the game name inside the game list because they are inferred by the corresponding entry of the Redump DB. This is a problem if, for example, an user wants to play a modded version of a game while keeping the vanilla version in the roms folder as well. Two identical entries are shown in the gamelist and their only difference is the file size.

**Describe the solution you'd like**
A way to freely rename an entry in the game list, so that two version of the same game are recognizable and could also, for example, also use 2 different mem cards (if the memory card creation option is set to Per-game title)

**Describe alternatives you've considered**
Probably this is not feasible but if the games were associated to the redump DB via the hash instead of the game code, the modded version would not be mistaken from the vanilla version. I suspect the hashing of many files would take a lot of time, though.

**Additional context**
I'm open to questions since I don't currently have additional context

**Comment by RaydenX93** [comment]
hi # github
I believe this could be related to #1200 ?

**Comment by levonnn** [comment]
Since my thread is closed, I'll post here if you don't mind.

Akumajou Dracula X: Gekka no Yasoukyoku [SLPM 86023]
Akumajou Dracula X: Gekka no Yasoukyoku (Rev 1) [SLPM 86023]
Akumajou Dracula X: Gekka no Yasoukyoku (Rev 2) [SLPM 86073, SLPM 87328]

Why all of them are labeled as Rev 1 in the game list? Serials are different in case of Rev 2. I'm assuming internal serial is used for the game list. But then even the vanilla version is called Rev 1 for some reason. Maybe it's worth prioritizing non-Rev version in titles? And as addition give an option to make a custom title that will replace redump one like OP suggested.

**Comment by ZachFett** [comment]
Would really like to be able to change game titles or move around their order. 

Currently the Twisted Metal series is all out of order. Right now it goes:

Twisted Metal [SCUS-94304]
Twisted Metal - Small Brawl [SCUS-94642]
Twisted Metal 2 [SCUS-94306]
Twisted Metal 4 [SCUS-94560]
Twisted Metal III [SCUS-94249]

Twisted Metal 3 is going after 4 because it's using Roman numerals. Not sure why Small Brawl is in between 1 and 2, possibly because of the dash? Drives me crazy, though.
<img width="229" alt="duckstation-qt-x64-ReleaseLTCG_afrkSEdW1i" src="https://user-images.githubusercontent.com/29797689/149042016-88a4f4a0-5dc2-41ed-956b-47636036103b.png">

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/ccb76d1451c7e4fe3e0660d0c8258d77536db76d.
