### ISSUE TITLE
Opengl optimization advice

### ISSUE THREAD

**Issue by nineKnight** [stenzek/duckstation#1080]
https://github.com/stenzek/duckstation/commit/4f4c4f41465ff80bb0d3eb22ee4bbf2aef0b3f7b#r44211647

**Comment by stenzek** [comment]
See my reply on the commit, this won't change anything. Unless I'm misunderstanding.

**Comment by nineKnight** [comment]
No, it hasn't finished yet. I reply too. Shall we discuss here but the commit?

**Comment by stenzek** [comment]
I'm still not sure what you're getting at. It could be lighter because it's using a 16-bit backbuffer instead of 32-bit? Not sure.

Regardless, an ES context is never requested on Windows, since it'll always try for a core/compatibility context first. It'll only use ES if you set the `PREFER_GLES_CONTEXT` environment variable, which only exists for debugging.

**Comment by nineKnight** [comment]
Disappointed!!!
If you never run the code posted [there](https://github.com/stenzek/duckstation/commit/4f4c4f41465ff80bb0d3eb22ee4bbf2aef0b3f7b#r44216286), there is no need to debate any more.
The phenomenon is 100% for certain caused by ([here](https://github.com/stenzek/duckstation/blob/71eb578db18570311c4ee9f4009e83cfecdee2aa/src/common/gl/context_wgl.cpp#L303))
```
      WGL_CONTEXT_PROFILE_MASK_ARB,
      ((version.major_version >= 2) ? WGL_CONTEXT_ES2_PROFILE_BIT_EXT : WGL_CONTEXT_ES_PROFILE_BIT_EXT),
```
Why not just try and comment these two line?

What you will see
------------------------------
![image](https://user-images.githubusercontent.com/30484198/99341499-f5f35c80-28c4-11eb-8380-f82fd5ee9d1b.png)
```
glClearColor(0.5f, 0.5f, 0.5f, 1.0f);   // should be #808080 but #bbbbbb
```

**Comment by stenzek** [comment]
Which GPU are you using? It gives back (127, 127, 127) on my system.

If I remember correctly the ES2-via-WGL is an NVIDIA-only thing.. Probably should have a check for `WGL_EXT_create_context_es2_profile`, but as this is a debugging path nobody ever actually hit it.

**Comment by nineKnight** [comment]
With ES[2]_PROFILE:
```
[    0.2006] I/GL::Context: Created a OpenGL ES context
[    0.2016] I/GL::Context: GL_VENDOR: Intel
[    0.2019] I/GL::Context: GL_RENDERER: Intel(R) HD Graphics 630
[    0.2022] I/GL::Context: GL_VERSION: OpenGL ES 2.0 - Build 27.20.100.8681
[    0.2025] I/GL::Context: GL_SHADING_LANGUAGE_VERSION: OpenGL ES GLSL ES 1.00 - Build 27.20.100.8681
```
----------------------------------------------------------
With CORE_PROFILE or without setting PROFILE_MASK:
```
[    0.5552] I/GL::Context: Created a OpenGL ES context
[    0.5617] I/GL::Context: GL_VENDOR: Intel
[    0.5620] I/GL::Context: GL_RENDERER: Intel(R) HD Graphics 630
[    0.5624] I/GL::Context: GL_VERSION: 4.6.0 - Build 27.20.100.8681
[    0.5630] I/GL::Context: GL_SHADING_LANGUAGE_VERSION: 4.60 - Build 27.20.100.8681
```

**Comment by stenzek** [comment]
Sounds like an Intel driver bug then.

I still don't see how this is an issue which will affect anyone, since GLES is not used on desktop (you always have core/compatibility contexts).

**Comment by nineKnight** [comment]
Since OpenGL is something like wrapper, the implements are originally various from manufacturer to  manufacturer. Therefore, it's not a driver bug. What's more, as [Khronos' doc](https://www.khronos.org/registry/OpenGL/extensions/ARB/WGL_ARB_create_context.txt) shows you, ES[2]_PROFILE shouldn't be set.

**Comment by stenzek** [comment]
Have you read https://www.khronos.org/registry/OpenGL/extensions/EXT/WGL_EXT_create_context_es2_profile.txt ?

**Comment by nineKnight** [comment]
No.
The problem still exists after I update the driver.
I test on another PC, and codes work as expected. However it's a too old machine running Win7 and hard to update its driver.

Maybe it's driver's bug as you mention, but I still suggest you to comment these two lines.

**Comment by stenzek** [comment]
Please read the extension specification before telling me to comment out code which is fine. The only thing which is missing here is to check that the extension is actually supported, but even if it's not, the driver should return an error.

Commenting out the ES2 bit makes no sense, since then you'll get a compatibility context then, and it's in a block which checks if the caller requested a ES context?

Anyway, it doesn't matter for DuckStation because like I said, this code is not executed. It will always try for a core/compat context before a ES context: https://github.com/stenzek/duckstation/blob/master/src/common/gl/context.cpp#L189

If you don't believe me, I'd suggest running with a debugger, dropping a breakpoint in this function, and seeing what it does ;)
