### ISSUE TITLE
Dualshock 4 not working with Cubed Backend

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#1120]
**Game details**
Not Game related

**Description of the issue / bug**

![image](https://user-images.githubusercontent.com/43047877/100613232-f6dbb380-32f2-11eb-9ab6-247aef0ea325.png)

**Steps to Reproduce**

- Plug Dualshock 4 controller;

- Run Duckstation
(Notice a blue light meaning Duckstation recognized Dualshock 4);

- Change backend; 
(From Cubed to SDL in Audio Settings);

- Boot a game, and before it finishes to load game to RAM, boom error: Failed to create audio stream.

**Enhancements information**
Nothing to do with any games.

**Hardware/software**
Desktop Ryzen 53600, GPU: Rx580 Windows 10 / 1909

**Emulator version**
Latest - 0.1-2408-gc3932e94

**Additional context**
-

**Comment by ggrtk** [comment]
Seems to be related to how Cubeb is handling the WAVEFORMATEX returned by WASAPI. 

For the DualShock 4, GetMixFormat returns `WAVE_FORMAT_IEEE_FLOAT` for the wave format tag. Cubeb is reconfiguring the mix format based on the `cubeb_stream` passed to `setup_wasapi_stream_one_side()` and setting the bits per sample to 16, which is incompatible with `WAVE_FORMAT_IEEE_FLOAT`. If I'm not misunderstanding, the wave format tag probably needs to be changed in this case to `WAVE_FORMAT_PCM` like what's being done in the WinMM backend so that the IAudioClient initialization doesn't fail. From brief testing, forcing `WAVE_FORMAT_PCM` enables audio through the DualShock 4 at the very least.

It might be best to report this issue to Cubeb upstream.

**Comment by andercard0** [comment]
Fixed in the latest build Thank You!
