### ISSUE TITLE
[SLUS-00522] Auto Destruct (USA) - Controller is connecting/reconnecting indefinitelly when starts the game

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#1167]
**Game details**
[SLUS-00522] Auto Destruct (USA)

**Description of the issue / bug**
The controls aren't properly running in this game.

**Steps to Reproduce**
Start the game, after the istructions be made, the game will "pause" for few times, after that, the controller will start to "connect/reconnect" section...
(It's woth mention that I already take sure that the analog mode is off, when testing this game, since this game has no analog support) 

**Emulator version**
0.1-2483-g98d6b499

**Comment by ggrtk** [comment]
Does this issue also occur with Digital Controller or is it only a problem with Analog Controller?

**Comment by Shideravan** [comment]
It's happens in digital controller too (but not with the same "intensity", the disconection are more "spaced".

**Comment by ggrtk** [comment]
Seems to be a DMA timing related, setting DMAMaxSliceTicks to around 200 fixes this.

**Comment by stenzek** [comment]
Gameini override added in https://github.com/stenzek/duckstation/commit/d7de578d4a8b00ab8c7cb0d4bc4c4c9b409a23e7

I'm wondering if we should just lower the slice size by default, since it does seem to break a few games, and the performance impact is minimal. This way we wouldn't need to override them. The hit is greater on mobile devices though, probably need to speed things up a bit first there, otherwise the Android 1-star gang will rise up.

**Comment by stenzek** [comment]
Closing as it has been worked around via gameini.
