### ISSUE TITLE
[SLPM-86505] Dancing Stage featuring DREAMS COME TRUE (Japan) - Greatest Hits mode not working properly after disc change

### ISSUE THREAD

**Issue by tjbautista01** [stenzek/duckstation#1176]
**Game details**
[SLPM-86505 Dancing Stage featuring DREAMS COME TRUE (Japan)]

**Description of the issue / bug**
After changing to any of the disc images of THE SOUL (Audio CDs in bin/cue format), the game stops for a long while (more than a minute) at disc check (see image)
![image](https://user-images.githubusercontent.com/63538745/101508120-420c5b00-39b2-11eb-8023-f464f99a2413.png)

Then after a while it will throw a Wrong Disc message (see image):
![image](https://user-images.githubusercontent.com/63538745/101508328-7d0e8e80-39b2-11eb-9c02-55144efd7ffc.png)
Note: The disc trying to be loaded here is THE SOUL Disc 1. Same result happens for Disc 2

**Steps to Reproduce**
1. Load Dancing Stage featuring DREAMS COME TRUE
2. Go to Greatest Hits mode and press Start to auto-select Play Style options
3. Choose any song and change disc to requested disc number (load using cue file)

**Enhancements information**
None

**Hardware/software**
Hardware: Intel Core i7-7700 @ 3.6 GHz, AMD RX 550, 32GB RAM
Software: Windows 10
GPU Renderer: Software

**Emulator version**
0.1-2499-g770dd5a6

**Additional context**
It loads faster when using the bin file, but still reports a Wrong Disc message regardless. In the PSX BIOS CD Player, the CDs can be loaded properly with their respective cue sheets but seems to have an issue where any track beyond Track 10 doesn't load properly (separate issue?)

**Comment by stenzek** [comment]
Could you upload the cue sheet are you using for the second disc? (might have to zip it, or you could paste the content in a code block)

**Comment by tjbautista01** [comment]
> 
> 
> Could you upload the cue sheet are you using for the second disc? (might have to zip it, or you could paste the content in a code block)

Only the cue sheets?

**Comment by stenzek** [comment]
Thanks! Will look into this soon.

**Comment by stenzek** [comment]
Do you know if this works in other emulators? It looks like the game tries to read the audio CD as data, and compares it. I don't think the CD controller should return audio sectors as data, because it has no way to know which sort of sector it is.

So I'm wondering if what would normally be audio sectors are flagged as data sectors in the subchannel. I've uploaded a build below which disables the subchannel data flag check for reads - drop it in your duckstation directory alongside the normal executables. If this fixes it, it could be the issue.

Alternatively, if you want to patch this out and build yourself, replace this line: https://github.com/stenzek/duckstation/blob/681fccd5e6e5b2e48c0ffa1fd67880136365e531/src/core/cdrom.cpp#L1835 with `if (m_drive_state == DriveState::Reading)`.

[duckstation-qt-x64-ReleaseLTCG-cdda-as-data.zip](https://github.com/stenzek/duckstation/files/5710136/duckstation-qt-x64-ReleaseLTCG-cdda-as-data.zip)

**Comment by tjbautista01** [comment]
> 
> 
> Do you know if this works in other emulators?
For evidence here's it running in Mednafen:
https://streamable.com/ns4idd

And here it is using same discs in Duckstation (long video):
https://streamable.com/65bz6r

As of this posting I haven't tried your build yet so I'll give it a go. 

Separate issue but I want to try the DDR Club Versions in Duckstation too to test if it handles bypassing anti-mod checks properly. The Club Versions are notorious for screwing up their timing windows when the games detect that the anti-mod check has been skipped or patched out.

**Comment by tjbautista01** [comment]
Update: issue fixed on latest build. Issue can be closed.
