### ISSUE TITLE
Win32 (x86) releases

### ISSUE THREAD

**Issue by Psycho-A** [stenzek/duckstation#1226]
I was saddened to learn that there are no releases for such a great emulator for 32-bit versions of Windows. The PS1 hardware is not the kind that requires at least 64-bit powerful systems, so I see no reason not to compile 32-bit versions of the emulator.

**Comment by stenzek** [comment]
There's no recompiler for 32-bit x86, nor do I have any interest in writing one, as any hardware from basically 2004-ish onwards should be 64-bit. You could compile it yourself, but it's going to only have an interpreter and be slower.

**Comment by Psycho-A** [comment]
I'm late with answer but I just recently found that there's 32-builds for libretro frontends and they work fine to me. So what limitations not to do standalone Windows 32-bit builds for now? I have second PC with 2007 dual-core CPU and 3 Gb of RAM, and 32-bit OSes works better and faster on it than x64. Know also different use cases when 32 bit OS is more preferred, but the performance is pretty enough for using  PS1 emulators.

**Comment by stenzek** [comment]
Because the recompiler has to have a backend for each target and 32bit x86 is much more limiting, and not worth the maintenance burden. Duckstation is a more accurate emulator than others and has higher hardware requirements as such, but still (IMO) very reasonable.

Like I said, feel free to compile it yourself, but you won't get a recompiler and it will be slow. It's too much for me to support as a side project, unfortunately I have to draw the line somewhere.

**Comment by stenzek** [comment]
(to be clear, by support I mean provide builds and ensure it is a good experience. I don't believe in releasing for 20 different architectures when it's not going to generally work well, one should be able to expect a certain level of quality)

**Comment by Psycho-A** [comment]
Okay, got your point.
