### ISSUE TITLE
Add Horizontal Image Offset Option

### ISSUE THREAD

**Issue by Awakened0** [stenzek/duckstation#1249]
When using the "Only Overscan Area" cropping option, some games get cut off a little on the left or right. With a horizontal offset option, the image could be shifted left or right to fit within the cropped area.

Notable games:
Castlevania Chronicles (USA) - Two pixels cut off on the left. Has an in game adjustment, but when moving it to the right the right gets cut off instead.
CTR - Crash Team Racing (USA) - One pixel cut off to the right. No in game adjustment.
Spyro 2 - Ripto's Rage! (USA) - One pixel cut off to the right. In game horizontal adjustment set to -1 fixes it.

**Comment by stenzek** [comment]
There's a horizontal offset in compatibility settings, it's just in ticks not pixels. Maybe worth changing the unit..

**Comment by Awakened0** [comment]
It's not something exposed as user changeable in the libretro core though, right?

**Comment by stenzek** [comment]
No, because the range is in thousands, and I can't expose a range that large via core options.

**Comment by Awakened0** [comment]
Oh :0

Beetle just uses a range of -12 to 12 pixels.

**Comment by ggrtk** [comment]
Beetle uses fixed pixel offsets in the software renderer (but not the hardware renderers) because that's years-old code that was never updated. For some reason, those options were added to the software renderer despite being a mismatch with upstream Mednafen behavior.

We might be able to get away with tying a single core option to both the start and end offsets so that the image is just shifted rather than expanding or shrinking the visible screen area. I'm not really a fan of using pixels as a measurement since it doesn't entirely account for width mode changes.

Frankly, libretro needs a better way to expose large number ranges in core options. Even something simple like being able to pass a {min, max, step} to the frontend would be nice, but instead we have to deal with large unwieldy arrays.

**Comment by stenzek** [comment]
Closing since this the ticks adjustment is already present, just in ticks (game properties -> compatibility settings), and the libretro core no longer exists.
