### ISSUE TITLE
Crop Mode "None" Missing Left/Right Padding in Software [Libretro]

### ISSUE THREAD

**Issue by Awakened0** [stenzek/duckstation#1258]
I mentioned this on Discord awhile ago, but I forget if it was fixed before. With the latest dev build it's happening though.

Software:
![soft](https://user-images.githubusercontent.com/4565863/102668946-44617880-415b-11eb-867c-18b1dfb4b254.png)

Vulkan:
![vulk](https://user-images.githubusercontent.com/4565863/102668953-4a575980-415b-11eb-921b-471e30a751b0.png)

Using the libretro core, build 0.1-2598-g9e198706

**Comment by Awakened0** [comment]
Only Overscan Area is being affected too. Less noticeable in this example since it's only one pixel of padding, but it does affect the aspect ratio.

Software:
![Castlevania Chronicles (USA)-onlyoverscan](https://user-images.githubusercontent.com/4565863/102672203-2ba69200-415e-11eb-9e98-1060c3ce6b94.png)

Vulkan:
![Castlevania Chronicles (USA)-onlyoverscanvulk](https://user-images.githubusercontent.com/4565863/102672231-3f51f880-415e-11eb-8312-a7f2cdef456f.png)

**Comment by stenzek** [comment]
It's because it's presenting the area of VRAM  where the DAC is enabled, and the libretro API offers no way to add additional padding.

Then only option without complicating the renderer side would be to do yet *another* copy and add the padding, which isn't something I'm keen on (especially for low end devices which use the sw renderer).

This is basically what the hardware renderers do, except the performance impact isn't as high there because it's happening on the GPU. But yeah, still, another reason why libretro is slower than standalone.

IMO libretro should provide a way for the core to specify additional padding, which is applied at AR calculation time. But I'm pretty sure that'll never happen, so I'm not really sure what else to do here aside from making things slower :/

**Comment by stenzek** [comment]
If you don't mind, I'll merge this with #1064, that way there's a clear list for anyone who wishes to improve the libretro core in the future.

Unfortunately, due to recent events I no longer wish to have nothing to do with libretro/retroarch - I'll keep providing builds and ensure the core builds, but it's not something I desire to put any more time into myself.

**Comment by Awakened0** [comment]
Yeah, no problem.
