### ISSUE TITLE
Vulkan: Fullscreen briefly unmaximizes when pressing Tab

### ISSUE THREAD

**Issue by ipatix** [stenzek/duckstation#1265]
**Game details**
[SLES-02965, Europe]
I also have this problem in all other games I was able to try and I highly doubt that this is a game related bug.

**Description of the issue / bug**
When Vulkan renderer is selected, using the "Tab" key in fullscreen mode causes DuckStation to go briefly out of fullscreen and then switching to fullscreen again (for a small fraction of a second). This causes very annoying flicker, making it impossible to use the fast forward option without getting epilepsy. This does not occur with Direct3D11 or OpenGL.

**Steps to reproduce**
Load any game, select Vulkan renderer in settings, play any game, and press tab key during gameplay.

**Enhancements information**
N/A

**Hardware/software**
Intel Core i7 6700, AMD Radeon R9 200 series, Windows 10 64 bit.

**Emulator version**
0.1-2615-g6224d0ab (should be up to date)

**Additional context**
This problem occurs with the Qt and the SDL version.

**Comment by stenzek** [comment]
It's unavoidable, because Vulkan doesn't let you change the presentation mode (specifically whether vsync is enabled) without recreating the swap chain.

Disabling vsync will work around it, and if you have a FreeSync display won't make any difference. Otherwise you'll end up with duplicate frames.

Using D3D11 will also solve the problem, and is recommended. Vulkan is mainly for Linux and Android.

**Comment by stenzek** [comment]
Another possibility would be to keep vsync on but skip presenting frames to uncap the framerate, which I'll consider.

**Comment by ipatix** [comment]
Okay, thanks for the info.
