### ISSUE TITLE
Enable postprocessing shaders to access the depth buffer

### ISSUE THREAD

**Issue by YooPita** [stenzek/duckstation#1280]
Hi, I'm interested in a depth map for using FX. Can I access it for the SSAO shader?

I want to access the depth map. For the shaders that I want to use, it would probably still be useful to have information about the fog that hides the draw distance.

I tried to connect to the application via reshade, but it did not read the depth map. I came to the conclusion that it simply does not exist.

If I am wrong and there is such a way, then how to get the depth information in the shader?

**Comment by stenzek** [comment]
No. The PS1 has no depth buffer.

I have a branch where I try to recreate one based on depth from PGXP, but the problem is games use inconsistent depth ranges (e.g. the background has a lower Z than the foreground). So I use a threshold which clears the depth buffer when the depth increases beyond a threshold.

But overall compatibility is very low.

**Comment by stenzek** [comment]
Depth buffering will be in the next beta release. I still have to expose this to the postprocessing framework.

**Comment by stenzek** [comment]
This was implemented in https://github.com/stenzek/duckstation/commit/34d5cdec9657a6ef1ff68875d08b11caee1eb2bb, but only for Reshade shaders. Depth buffer not working well in some games is a separate issue.
