### ISSUE TITLE
Resident Evil 3 Item pickup takes forever to load

### ISSUE THREAD

**Issue by SilentHeII** [stenzek/duckstation#1302]
**Game details**
SLUS-00923, Resident Evil 3 - Nemesis (USA)

**Description of the issue / bug**
Sometimes, picking up an item can take an extraordinary amount of time. This is random, but can be accomplished in a couple minutes and happens a lot in a normal playthrough. I did not have issues with this game until VERY recently.

**Steps to reproduce**
Start a new game and play until you are able to pick up items. I was able to reproduce this rather consistently with the lighter oil.

**Enhancements information**
I used the software renderer. It occurred on all hardware renderers as well.

**Hardware/software**
https://pcpartpicker.com/list/4qBFb8

**Emulator version**
g095bc28

**Additional Information**
I checked this with both of these BIOS and had the same issues:
SCPH-5501
PSP 6.60 PSX BIOS

**Video**
https://streamable.com/6mx3pl

**Comment by Sekai9** [comment]
This has been fixed.
I have been trying to trigger this bug since yesterday and nope, no longer possible : )

DuckStation 0.1-3128-g05545566

**Comment by stenzek** [comment]
Hmm, I didn't do anything specific here for this issue. But perhaps it may have been https://github.com/stenzek/duckstation/commit/b7752ff30b7ec98825e48e62e18820b29a8a165c

**Comment by Sekai9** [comment]
Yup, i'm sure pretty that was the fix.

I've attached a log generated with an older build (0.1-2975-gddcc29c8, i got this from emucr btw)

The log is massive because when this issue is triggered the System Console starts spamming thousands of lines per second.
Also, if 'Log To System Console' is enabled, there is a big performance hit (Duck speed drops from 100% to ~65%)

This is fixed now but perhaps this info will be useful later.
[duckstation.log](https://github.com/stenzek/duckstation/files/5936071/duckstation.log)

**Comment by stenzek** [comment]
The slowdown is expected (and why logging is off by default). Logging to the console is slow :)

But yes, based on that message the listed commit would have indeed been the fix.
