### ISSUE TITLE
[META] Having two release builds (Preview / Development) seems unnecessary.

### ISSUE THREAD

**Issue by ImSpecial** [stenzek/duckstation#1330]
It's going to limit and slowdown testing / catching of bugs / reports, now instead of 10 people grabbing the latest build, only 5 will, while the other 5 will not.

Unless you stagger them literally a day or two apart, which as of now is not the case, people are just having to wait even longer for fixes and features, making the dev builds completely pointless.

It's also just confusing, "Preview" what the hell is that? I can't think of any software that offers a preview build in addition to dev builds or beta builds that would be considered more "experimental". Most people see software like this when it comes to "stability" sorta like this: Beta / Dev, etc. -> RC (Release Candidate) / Pre-Release -> Stable / Final Release.

I get why you do it, in theory, but it's not like DuckStation is so highly volatile anyway that warrants the above, this is all IMO of course, keep up the good work, etc, etc.

**Comment by stenzek** [comment]
The split is necessary because of users who 1-star the emulator because of a regression, instead of reporting it so it can get fixed.

The preview builds are so I can push new features/changes without fear of breaking things, and the people using the preview builds are more likely to report issues so they can get fixed, prior to it being pushed to the normal release.

"preview" is kinda like canary builds, used by other emulators, browsers, etc.

> Unless you stagger them literally a day or two apart, which as of now is not the case, people are just having to wait even longer for fixes and features, making the dev builds completely pointless.

That is the case. The last release was a few days ago, I'll likely push another one today.
