### ISSUE TITLE
Setting version mismatch. Settings have been reset to default

### ISSUE THREAD

**Issue by avalanchemaster** [stenzek/duckstation#1378]
I get this at program start up..
Setting version mismatch. Settings have been reset to default.
Any help appreciated

**Comment by ggrtk** [comment]
If this only happens on the very first startup, then this is expected behavior. I'd been meaning to change this to something more descriptive when a settings file isn't found, but kept forgetting, so thank you for the reminder.

However, if you get this warning every single time you start up the program, please check if `settings.ini` is being created in the user directory (or program directory, if you are running in portable mode).

**Comment by avalanchemaster** [comment]
It does not create an  .ini file.

**Comment by stenzek** [comment]
Are you checking in the DuckStation directory in your documents directory? (or the executable directory if using portable mode)

It should create the ini either after you change any settings or add a game directory, or exit the program.

**Comment by avalanchemaster** [comment]
![image](https://user-images.githubusercontent.com/76920305/103523847-70c40700-4e74-11eb-9ba7-31c41d0ffd06.png)

**Comment by avalanchemaster** [comment]
It does not create an ini file.

**Comment by stenzek** [comment]
You are not using portable mode. Therefore the ini file is saved in `Documents\DuckStation`.

If you have a permission issue or some other reason it cannot save to documents, use portable mode. Create an empty file named `portable.txt` in the directory with the exe, or start with `-portable` on the command line.

**Comment by avalanchemaster** [comment]
I think this is beyond my knowledge base tbh.

**Comment by stenzek** [comment]
[portable.txt](https://github.com/stenzek/duckstation/files/5764182/portable.txt)

Put this file (`portable.txt`) in your duckstation directory, run DuckStation, and add your games.

**Comment by avalanchemaster** [comment]
THANK YOU!!!!

________________________________
