### ISSUE TITLE
GTE overclock feature

### ISSUE THREAD

**Issue by garmendes** [stenzek/duckstation#1387]
**Is your feature request related to a problem? Please describe.**
I was experimenting with 60 fps patches (unlock fps limiter) and it will benefit to have a option like Beetle PSX GTE overclock.

**Describe the solution you'd like**
A option to enable the GTE to be overclocked/unlocked, so games and hacks that hit the performance cap can archive higher frame-rates a less slowdowns.

**Describe alternatives you've considered**
Besides using Beetle PSX there is no other AFAIK.

**Additional context**
Beetle PSX implements three overclock options: CPU, GTE (3d) and GTE rasterizer (2d). DS has only the CPU overclock option, but there are cases where the bottleneck is in the GTE. I made a 60 fps patch and tested in both BP and DS, and as expected in BP there are almost no slowdowns, while in DS they are present.

**Comment by stenzek** [comment]
Currently the GTE has no timing (I have it on a branch, but not merged).

Sounds more like you're asking for GPU overclock - when you overclock the CPU, it also overclocks the GPU as well.

**Comment by garmendes** [comment]
I really don't know the correct term, but there is a option like this in Beetle PSX and it does work for my use case.

![image](https://user-images.githubusercontent.com/22453509/103606826-50955600-4f0f-11eb-9c69-cd32712e4c33.png)

**Comment by stenzek** [comment]
Just overclock the CPU in DuckStation. The GPU will also be overclocked as a result.

Adding a separate GPU overclock would require additional complexity in the GPU tick routines, potentially costing performance. I'm not convinced it's worthwhile, unless you can show a case where GPU overclocking is necessary **but not** CPU overclocking.

**Comment by garmendes** [comment]
In fact this is a very specific issue and may not be worth the trouble. For the game that I am talking about (Legend of Legaia) both GTE and CPU overclock provides less slowdowns, but the latter also make the entire game faster, with faster animations, faster walking speed and suck. I've found that is possible to do a moderate CPU overclock that will not introduce noticeable speed artifacts. The use case of this feature in when the game depends too much on CPU timings, but I can't provide more examples. Feel free to close the issue. BTW your emulator is superb.

**Comment by foxsevent** [comment]
> In fact this is a very specific issue and may not be worth the trouble. For the game that I am talking about (Legend of Legaia) both GTE and CPU overclock provides less slowdowns, but the latter also make the entire game faster, with faster animations, faster walking speed and such. I've found that is possible to do a moderate CPU overclock that will not introduce noticeable speed artifacts. The use case of this feature in when the game depends too much on CPU timings, but I can't provide more examples. Feel free to close the issue. BTW your emulator is superb.

That's an issue with ePSXe and Beetle implementation of Overclocking, in Duckstation this doesn't happen or at least not the few cases I checked like Soul Reaver,
ePSXe
https://youtu.be/MjNV67glxwA
Duckstation
https://youtu.be/sov1ylJgivQ
Same OC setting and just like overclocking in other emulators it nicely smoothes any in game FPS drops Soul Reaver is now constant 30FPS instead of 15-20FPS it usuallu runs at,

**Comment by Snake356** [comment]
I found this thread here because I have exactly the same problem. I also play with 60 FPS patches and since I would like to enjoy the Gran Turismo series in 60 FPS, this emulator needs a GTE Overclock feature. I have always played with the PCSXR-PGXP before and GT1 and GT2 run without problems with 60 FPS patch. With the Duckstation it is unfortunately the case that the GT1 has slowdowns from time to time, so the overclocking brings something, but it is still noticeable. GT2 is not playable at 60 FPS, because the game runs very slowly and unfortunately the overclocking does not bring anything and I am already at 150% and when I go higher the game runs more and more unstable.

Here is a comparison of how it runs on PCSXR-PGXP with 60 FPS:
https://youtu.be/5CQilSYaDUM

and here how it works with the Duckstation with 60 FPS:
https://youtu.be/W8J0OeXs8ag

PS: Nevertheless I have to say that this emulator is really the best right now and I am absolutely amazed by the Duckstation. You're doing a really good job.

**Comment by stenzek** [comment]
I'm going to close this, because Duckstation doesn't have any GTE timing to overclock in the first place. I've considered adding them, but haven't seen any games which actually require it yet.

If you're seeing slowdowns with overclocking, then just overclock it higher. Duckstation emulates GPU draw timings as it's required for several games (PCSXR does not), so you might actually be seeing slowdown due to the GPU, not the CPU. But overclocking the CPU will also overclock the GPU, so just bump it up higher.

**Comment by Blackbird88** [comment]
FWIW I just found out there's a massive slowdown in Bugs Bunny: Lost in Time if you use widescreen hack/cheat in the intro. and surprisingly enough it's not affected by regular CPU OC. Not sure if it's relevant to this issue, but didn't want to open new one as I have no idea why it happens.

**Comment by foxsevent** [comment]
> FWIW I just found out there's a massive slowdown in Bugs Bunny: Lost in Time if you use widescreen hack/cheat in the intro. and surprisingly enough it's not affected by regular CPU OC. Not sure if it's relevant to this issue, but didn't want to open new one as I have no idea why it happens.

As already stated OC already overclocks both the CPU and GPU so nothing really can be done here without breaking something else.
As for why does this happens is simple because the game wasn't made to run in widescreen so forcing it to do so can work but it also can break the game in weird ways, as all enhancements can do.
If an enhancements breaks a game disable it.
