### ISSUE TITLE
Vibration inverted.

### ISSUE THREAD

**Issue by drdeathd** [stenzek/duckstation#1407]
I tried Metal Gear Solid vibration test and it's wrong and annoying in games because the vibration was not supposed to be like that.

**Comment by stenzek** [comment]
Which controller are you using? Last I checked with an xbox controller and DS4 it was correct.

**Comment by drdeathd** [comment]
I'm using a PS3 controller (SCP Driver so tecnically it's an xbox controller) Moreover I use ePSXe and doesn't had any problem with that.

**Comment by Alien-Grey** [comment]
> I tried Metal Gear Solid vibration test and it's wrong and annoying in games because the vibration was not supposed to be like that.

I also think something was wrong with vibration because it feels differnt too with WipEout 3 Special Edition. I can't test it any more because with current builds it no longer works for me. :(

**Comment by stenzek** [comment]
Just checked with a DS4 and the SDL controller interface with the latest build and it's correct.

**Comment by Alien-Grey** [comment]
I'm using a GPD Win 2 with XInput controller. Early revision with dual vibration motors Both XInput and SDL backend work but no vibration with current builds. Tried with deleting the settings.ini and reconfigure but still not working. When I assign a button to enable vibration nothing happens when I presss that button. No message like when enabling or disabling analog support.

All I know is that it worked in the past and that it stopped working after an update not too long a go.

**Comment by ggrtk** [comment]
I tested this a while back on two different Windows 10 setups with ScpToolkit and a DualShock 3 and was unable to replicate any sort of inverted vibration problem. And in any case, ScpToolkit is considered obsolete by its author.

**Comment by stenzek** [comment]
Sounds good, thanks for checking @ggrtk.
