### ISSUE TITLE
Little Princess - Marl Oukoku no Ningyouhime 2 (Japan) hangs on the first screen

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#141]
![Capture](https://user-images.githubusercontent.com/31968468/77250280-06522980-6c9b-11ea-8f0a-cab5974172bd.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/77250291-179b3600-6c9b-11ea-9f8a-556e93864dc1.PNG)

**Comment by kurayami6** [comment]
As of the latest version the game fades to a black screen before crashing. So I guess in the two months since I reported it broken it's managed to progress about 2 or 3 seconds further. 

![SLPS-02376_2020-06-03_23-01-02](https://user-images.githubusercontent.com/31968468/83639969-d609fe00-a5ee-11ea-8f88-7242b9d54731.png)

![Capture2](https://user-images.githubusercontent.com/31968468/83639988-db674880-a5ee-11ea-9733-20bc2bafeb59.PNG)

**Comment by stenzek** [comment]
Fixed with https://github.com/stenzek/duckstation/commit/71eb578db18570311c4ee9f4009e83cfecdee2aa
