### ISSUE TITLE
Playstation Mouse support

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#143]
Seeing as there's like 60 games that use it. It's not exactly an obscure peripheral. 

![Capture](https://user-images.githubusercontent.com/31968468/77257161-ba1cde80-6cc6-11ea-9c8e-91812bc0cfb8.PNG)

**Comment by stenzek** [comment]
Basic support implemented in https://github.com/stenzek/duckstation/commit/8f8298734184dbdb171ef2b90eaed5710e00c03e

It's not ideal though, since it doesn't use relative mode in the host or capture the pointer it won't line up with the cursor in the game.

I'll probably add that at the same time as crosshair overlays for the lightgun, since that needs sensitivity settings and such as well.
