### ISSUE TITLE
macOS/MoltenVK renderer: entering/exiting full screen mode cause the emulator to crash 

### ISSUE THREAD

**Issue by tonyunreal** [stenzek/duckstation#1436]
**Game details**
SLPS-01800, R4 - Ridge Racer Type 4 (Japan, Asia)

The issue is present in every game I tested. The crash log below was from running the game above.

**Description of the issue / bug**
When I manually enable or disable fullscreen mode in the standalone DuckStation emulator, the program immediately crashes. This only happens when the MoltenVK renderer is selected, neither the software renderer nor the OpenGL one has this problem. "Disable all enhancement" is checked in the settings.

Here's the crash log:

[vulkan_fullscreen_crash.txt](https://github.com/stenzek/duckstation/files/5794324/vulkan_fullscreen_crash.txt)

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?

No.

2. Which controller backend are you using in general settings

SDL

**Hardware/software**
Mac mini (2020, M1), macOS Big Sur 11.1
GPU Renderer - Vulkan

**Emulator version**
0.1-2862-g6fbffb6f (dev)

**Comment by stenzek** [comment]
Can't promise when I'll be able to investigate this, I don't have a Mac at the moment, let alone a M1-based one.

**Comment by tycooko** [comment]
> Can't promise when I'll be able to investigate this, I don't have a Mac at the moment, let alone a M1-based one.

I'm talking to the team of MoltenVK myself: https://github.com/KhronosGroup/MoltenVK/issues/1196 .
Since I'm not seeing much response/availability, would you at least be so kind as to tell me if you think that this automatically generated report after a MoltenVK crash on DuckStation would lead them in the right direction or is it just a very generic one: [DuckStation report.txt](https://github.com/stenzek/duckstation/files/5795120/DuckStation.report.txt) .
Thank you.

**Comment by stenzek** [comment]
Since upstream MoltenVK hasn't pulled in the SPIRV-Cross fix yet, I built a version with it added. Will be in the next build, or you can grab it from https://github.com/stenzek/duckstation-ext-mac/raw/master/MoltenVK/libvulkan.dylib and overwrite the `libvulkan.dylib` in `DuckStation.app/Contents/Frameworks`.

**Comment by tycooko** [comment]
@stenzek Works like a charm! My Final Fantasy games have never looked better! :)
Now, if automatic updates could be added to the Mac version as well, that would make it perfect.

**Comment by tonyunreal** [comment]
Thank stenzek, that build does fix the xBR hang issue tycooko mentioned. However full screen mode still crashes, so this might be a different issue than tycooko's. 

What is weird is that the built-in fullscreen mode from macOS works with DuckStation (which can be toggled from the little green button on the top-left corner of the window), but not the fullscreen mode from DuckStation itself. It is also worth mentioning that the Dolphin emulator uses MoltenVK but does not have this issue. I have been copying newer versions of libvulkan.dylib back and forth between the two emulators but Dolphin never crashes upon entering or exiting fullscreen mode. 

Maybe it's a issue with how DuckStation interacts with Qt or the MoltenVK rendering window?

**Comment by tycooko** [comment]
> Thank stenzek, that build does fix the xBR hang issue tycooko mentioned. However full screen mode still crashes, so this might be a different issue than tycooko's.
> 
> What is weird is that the built-in fullscreen mode from macOS works with DuckStation (which can be toggled from the little green button on the top-left corner of the window), but not the fullscreen mode from DuckStation itself. It is also worth mentioning that the Dolphin emulator uses MoltenVK but does not have this issue. I have been copying newer versions of libvulkan.dylib back and forth between the two emulators but Dolphin never crashes upon entering or exiting fullscreen mode.
> 
> Maybe it's a issue with how DuckStation interacts with Qt or the MoltenVK rendering window?

So sorry for hijacking your thread! I was so sure it was the same issue, but you're right: it still crashes for me, too.
Also: do you also see the dock getting "auto-hiding" enabled right after every crash?!

**Comment by tonyunreal** [comment]
In case anyone is interested, I have created [a patched version](https://github.com/tonyunreal/duckstation/tree/tonyunreal-m1) to demonstrate how this issue could potentially be mitigated, albeit only partially.

In this version, the rendering surface is no longer destroyed and re-created during a single game session, thus preventing the crash initiated by MoltenVK mid-game. My code also responds better to the application entering / exiting the full screen mode outside of the code's control, such as the user clicking the full screen button on the title bar or the "view - enter full screen" option from the system menu. In fact, the emulators now handles at least three ways of entering / exiting the full screen mode: through the built-in toolbar button or the menu option (settings - fullscreen), through a keybind (option+return), and through macOS interfaces (green button on the top-left corner of the window, "view - enter full screen" in the menu), all interacts with each other. Switching the options of "Start Fullscreen" and "Render to Main Window" back-and-forth is also supported.

Unfortunately, the real problems do seem to be residing inside MoltenVK. Destroying / recreating the rendering surface a second or a third time would have a high chance of crashing the application. To replicate this, just start a game then shut it down through the "power off" option of the emulator, then start another one, the application usually crashes or glitches out on the second or third try. This happens with the official version of DuckStation too, and occasionally with the Dolphin emulator, so it must MoltenVK that is malfunctioning.

**Comment by stenzek** [comment]
@tonyunreal thanks for investigating. I'm not really a fan of getting rid of the surface recreation - it's necessary to switch to exclusive fullscreen mode on Windows, as well as for runtime toggling of render-to-main-window. Similar in Linux/Wayland - you can't reparent a window, has to be a new one.

I suppose _in theory_ if you had render-to-main off, then could elide the fullscreen check. Could you try the following patch and see if it makes any difference with render-to-main off? https://github.com/stenzek/duckstation/commit/ed57c631d2f948fb351f5af43154fe2cae0413eb

**Comment by tonyunreal** [comment]
Yeah, that is why I call it a demo, I'm sure it breaks more things on Windows/Linux than it fixes on macOS. I'm also surprised that re-parenting works under macOS, which I assume it wouldn't at first.

**Comment by tonyunreal** [comment]
> I suppose _in theory_ if you had render-to-main off, then could elide the fullscreen check. Could you try the following patch and see if it makes any difference with render-to-main off? [ed57c63](https://github.com/stenzek/duckstation/commit/ed57c631d2f948fb351f5af43154fe2cae0413eb)

Yeah it works, as in, not crashing when fullscreen mode is toggled.

**Comment by stenzek** [comment]
Cool, I'll push it to master and that solves part of the problem anyway.

Another option could be to use https://github.com/stenzek/duckstation/issues/1439 once I finish it, as the entire UI is rendered using the graphics API.

**Comment by tycooko** [comment]
The current solution works as long as downsampling isn't activated, in which case the software behaves as before and crashes when fullscreen is turned on.

**Comment by stenzek** [comment]
Closing since mac builds are no longer supported; from the readme:

> MacOS builds are no longer provided, as I cannot support a platform which I do not own hardware for, and I'm not spending $1000+ out of my own pocket for a machine which I have no other use for.
> You can still build from source, but you will have to debug any issues encountered yourself.
> If anyone is willing to volunteer to support the platform to ensure users have a good experience, I'm more than happy to re-enable the releases.

**Comment by tycooko** [comment]
That's fine.
Is there a way I could access the previous versions of the program - when it was still compatible with macOS - to find one that suits me best?
Apparently, Web Archive only has one past version of the page with the "Preview" build and it is from February (when you forgot to add Mac builds to the list) and all Development builds I've downloaded from Web Archive have weird glitches (like the absence of the grid view for the games).

**Comment by stenzek** [comment]
Build from source. There's instructions in the readme.

The CI is still building it (so I know when I break it compiling at least), and you can download the artifacts from there (click the green tick next to the commit), but they're not listed in the release page because apparently despite the warning message in the readme, people still expected me to fix issues. Hopefully with it hidden they won't.

It was like 1.4% of the users anyway. can't justify $1k for a Mac mini out of my own pocket for 1% of users. Unless someone wants to send me one ;)

**Comment by tycooko** [comment]
> Build from source. There's instructions in the readme.
> 
> The CI is still building it (so I know when I break it compiling at least), and you can download the artifacts from there (click the green tick next to the commit), but they're not listed in the release page because apparently despite the warning message in the readme, people still expected me to fix issues. Hopefully with it hidden they won't.
> 
> It was like 1.4% of the users anyway. can't justify $1k for a Mac mini out of my own pocket for 1% of users. Unless someone wants to send me one ;)

Apparently, second-hand products don't exist where you live. Sorry to hear that.
I've already made myself available greatly, with barely any response. Plus, all the time you blamed the operative system, the ROM dumps or whatever, it was actually your laziness/distraction/incompetence that was easily solved with just a little care (from yours truly or better developers).
If I'm ever doing something "crazy" as giving a Mac computer to someone so they can develop software on it, surely that someone won't be you.
Also, I'd say that, after just one year of "I hate macOS", "Maybe I will look into that issue in 3 or 4 months", "Just do it yourself" and all the attitude you've always had toward the Mac and Mac users, the fact that several people with a Mac still downloaded your product can be considered a success.
You're unbearable and I pity whoever needs to put up with you in real life, but thanks anyway for what could easily be the best emulator on the Mac, had you had thicker skin.

**Comment by stenzek** [comment]
To be able to debug and fix issues, I need access to machine with development tools installed. Any random machine won't work.

I'd actually considered using one of the cloud Mac offerings to debug these issues, but the last time I checked they were quite expensive. And I can only spend so much out of pocket for a project which brings in zero income.

I even gave you a solution (download the CI artifacts directly), but that's not good enough I guess. Geez man, I give all my work away for free and never ask for anything, and all you do is shit all over me.

But hey, if I'm such a failure and a horrible person, don't use my stuff then. Why are you wasting your breath?

**Comment by tycooko** [comment]
I don't understand the correlation between the stuff and the people who make the stuff.
I'd like Apple's headquarters to burn down and I think they're a bunch of capitalist thieves, but I love (a very few of) their products.

**Comment by stenzek** [comment]
Because you're figuratively biting the hand which feeds you.

Like I said, I was considering other options (cloud services) so I could sort out the platform specific issues, as well as figure out how to create native builds for M1 users, since duckstation has an aarch64 dynarec.

But gosh, if you're just going to attack me... I'm definitely not paying for something out of my own pocket just to get shit on.

**Comment by tycooko** [comment]
You sound like someone who could record his own voice to jerk off to it later.
Anyway, suit yourself and tell your loved ones to write me their addresses so I can send them wine bottles.
Bye.

**Comment by stenzek** [comment]
How mature. Despite you not being a customer (you didn't pay anything), I've treated you professionally and with respect, and provided solutions where I can.

I've blocked you from the repository, and will be reporting you to GitHub.

**Comment by lwouis** [comment]
Reporting some tips here to help other mac users:

DuckStation works great on macOS. I was pleasantly surprised as to how nice the experience was. You build the app from source using the instructions on the homepage, and it just works.

2 things that took me a while to workaround:

* `Display Settings > Renderer` switch to `Vulkan`. The default `OpenGL` crashes for me
* `General Settings > Render to Main Window`. Uncheck it, so that you can fullscreen/de-fullscreen the game window by clicking the green button on the top-left corner of the window, instead of using the built-in fullscreen button/hotkey. This avoid the crash discussed in this ticket.

Other than that the emulator really impresses. Everything is smooth. Preferences can be set in real time (so cool!). The Enhancements are incredible. The UI is very easy to understand and well organized.

@stenzek thank you very much for you work! This piece of software is smoother to use than most of my every day work software (Outlook, Jira, Figma, etc). I feel sorry that the jerk above attacked you. I can't understand people complaining to volunteer work. It's like going to a local animal shelter and complaining they don't do something good enough. Like who does that in real life? Only through the pseudo-anonymity of the Internet are such behaviors possible.

In any case, again thank you for you work on this emulator, and the brilliant piece of software, and for not plainly abandoning macOS support even though you don't own Hardware.

2 ideas maybe to improve the mac experience:

* Maybe, only on the mac, map the built-in fullscreen button to macOS window fullscreen action? I guess [this API using QT](https://doc.qt.io/qt-5/qwidget.html#showFullScreen)?
* Use a VM maybe to test macOS? I test some stuff on Windows 10 from my mac sometimes, and I also test my FOSS project on multiple versions on macOS. I use VMs with different macOS releases to do that one a single machine.
