### ISSUE TITLE
Bug with Bluetooth controllers and FastForward.

### ISSUE THREAD

**Issue by Ryusan-AT** [stenzek/duckstation#1459]
Good morning to all.

I'm running Windows 10 (20H2), Gamer laptop and I'm using the latest DuckStation build.

When I use my joystick in Bluetooth mode and FastForward/Turbo mode, I do not exceed 170% acceleration (CPU at 6% charge). On the other hand in USB mode, no problem, I exceed 1000% speed (CPU at 12% charge).

Can you check on your side? Thank you. Possibly a bug or a bad management of Bluetooth in the emulator.
I specify that my drivers are up to date.

**Comment by Ryusan-AT** [comment]
No one can reproduce this behaviour?

**Comment by stenzek** [comment]
Seems very strange. A couple of things to try:
 - Check "use blit swap chain" in Display Settings.
 - Set the max display fps to 60 in Advanced Settings (will limit presentation when fast forwarding).

**Comment by Ryusan-AT** [comment]
No change, I always run at 180FPS when my controller is plugged in Bluetooth in Fastforwarding, and at more than 1000FPS when it is plugged in USB.

**Comment by stenzek** [comment]
Hmm, I'm able to reproduce this, looks like it gets blocked sending the rumble/vibration intensity to the controller. So if you unbind the rumble (right click), it'll stop limiting it.

We switched from sending the vibration on change to every frame a little while back, presumably because long sequences would get stopped mid-way. Maybe it's worth changing this, or putting it on a timer (e.g. sending rumble at most every second). @ggrtk any thoughts?

**Comment by ggrtk** [comment]
The change from before might have been too aggressive, so I think it's fine to revert it but keep the SDL rumble duration value at the maximum 65535 ms. I'd assume no games would send the exact same rumble strength to the controller for over a minute straight.

**Comment by stenzek** [comment]
I added a limit to the rumble updates in https://github.com/stenzek/duckstation/commit/cbee8fab666d1cc39f31ff931fa83e4bd1f2b99d, see if this makes any difference.

(You will have to switch to the preview build to see it for now, General Settings -> Update Channel -> preview, click Check For Updates).
