### ISSUE TITLE
Downsampling adaptive Crash issue

### ISSUE THREAD

**Issue by backgamon** [stenzek/duckstation#1488]
Hello,

If use the fast forward (TAB) with the Adaptive Downsampling enabled Duckstation just hang.
It happen in game and when bios boot, if don't use TAB or if i doesn't enable the adaptive it work as attended.
When it hang i need to kill task in the task manager, it won't exit alone.

-> Latest Duckstation.

Window 10 pro x64
I9 10850k@4.8/4.9Ghz
Asus Maximus XII Formula
64Gb Gskill Trident Z RGB XMPII@3600Mhz
Gigabyte RTX 2070 8G Gaming OC

**Comment by stenzek** [comment]
Please fill out the issue template:

**Game details**
[Serial Code, Region]
[i.e SLUS-00404 Ace Combat 2 (USA)]

**Description of the issue / bug**
[Describe what you are seeing and/or hearing during gameplay]

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
2. Which controller backend are you using in general settings

**Note:**
If you are using Duckstation on Android device please consider the following before report:
Are you using any kind of "memory optimizer" program such as: Ccleaner, Wisecleaner, Clean Master, Boost Android etc. ?
(if so, please, consider create an exception on it first and test; or even remove / uninstall it retest and then, if the problem persists continue with the report.

**Steps to reproduce**
[Try to provide as much detail as possible to reproduce the issue]

**Enhancements information**
[Make sure they are all turned off before report]

**Hardware/software**
[If Android, which phone and Android version]
[If desktop, your CPU, graphics card, and operating system]
[GPU Renderer - D3D11/OpenGL/Vulkan]

**Emulator version**
[Shown in the title bar of the emulator]

**Additional context**
[Add any other context about the problem here]

**Comment by backgamon** [comment]
Game details
Any game suffert.
But for this time i will use : Ridge Racer SCES-00001

Description of the issue / bug
When using at start Downsampling : Adaptive -> Duckstation crash.
When enable during gameplay -> It work except if using the shortcut TAB (Fast Forwarding).
I have that error when crash:
![crash](https://user-images.githubusercontent.com/39404647/105509831-38268900-5cce-11eb-9ea3-4597ae17b271.jpg)


Steps to reproduce
Launch Duckstation with Downsampling Adaptive enabled.

Enhancements information
With or without - No change.

Hardware/software
Using Vulkan Render

Windows 10 pro x64 [19042.746]
I9 10850k@4.8/4.9Ghz
Asus Maximus XII Formula
64Gb Gskill Trident Z RGB XMPII@3600Mhz
Gigabyte RTX 2070 8G Gaming OC[461.09]

Emulator version
Duckstation 0.1-2957-g3c3bfdea

**Comment by stenzek** [comment]
Okay, so potentially a Vulkan issue. Will check when I have time.

**Comment by stenzek** [comment]
I believe this was fixed a couple of weeks back. If it's still happening on the latest preview build, please let me know.
