### ISSUE TITLE
Bind keyboard/mouse to analog sticks

### ISSUE THREAD

**Issue by OvsyankaT** [stenzek/duckstation#1502]
Hi! It would be nice to bind the mouse to an analog stick. Is it possible and will it be?

**Comment by stenzek** [comment]
Not really sure how this would work - would the mouse movement behave like a stick being held in place?

**Comment by 6lackmag3** [comment]
@stenzek may I ask you please to expand mapping of analogs on Android so you can map left, right, up and down axis separately instead of just Left stick X, Left stick Y? You see, some games (C-12 specifically) use sticks to look around but unfortunately lack option to invert camera movement.

**Comment by OvsyankaT** [comment]
@stenzek I saw this function in the PS2 emulator, I think it works like a "spring" there. I'm not good at programming, but I think this can be done by calculating the delta of each axis.

**Comment by Weej1** [comment]
Came here searching for exactly this. I was trying to map the 'left' and 'right' turns (i.e. not strafe keys) to relative Mouse axes on FPS games like Kileak the DNA imperative and Disruptor. 
I intend to use WASD with WA being front and back, SD being strafe left/right respectively, but with the mouse handling the actual turning to left/right (There usually aren't any look up/down abilities in these games).  

Is there a way to attempt this at all with the current builds of Duckstation?

**Comment by MateusAuri** [comment]
+1 this
I wanted to map the analogs to WASD and arrow keys so I could quickly test Ape Escape without plugging a controller in.

**Comment by Nine-H** [comment]
It takes some magic number tweaking to get it correct but you can just grab the mouse input for each axis and then scale and normalise it so movement fits into the -1.0 to 1.0 of a joystick axis. It seems like it would be more complex, but I was hacking mouse and keys into a godot project I was working on and that just worked for camera input. Probably won't work for cursors because any weight and smoothing added by the game will always make them feel off.

**Comment by UserGit-2021** [comment]
Medal of Honor mouse supported?

**Comment by stenzek** [comment]
Was implemented in the UI revamp.
