### ISSUE TITLE
Netplay

### ISSUE THREAD

**Issue by imvr17** [stenzek/duckstation#1507]
Would it be too troublesome to add it?

By the way, you're doing an exceptionally great work with this emulator so far! This low end user is very grateful!

**Comment by stenzek** [comment]
Not trivial at all to add. Not when done well, anyway.

I'll keep this open as a request, but I have no plans in the near future to implement it.

**Comment by stenzek** [comment]
Closing, since I'm trying to clean up requests which are not in the scope of the project.

**Comment by danprice142** [comment]
Hoping this does get added at some point and would be even better if somehow when netplay is enabled the game would render the single player screen instead of split screen, making it feel more like a multiplayer game while maximising screen space and resolution. Could be a new way to experience ps1 games

**Comment by stenzek** [comment]
Just use parsec then.

**Comment by danprice142** [comment]
Wont work on Xbox and many other devices, netplay would be a much better option

**Comment by stenzek** [comment]
Please stop being demanding. I am not interested in the slightest in netplay, and it is a **lot** of work for very minimal gain.
