### ISSUE TITLE
the play store is saying that the application is no longer compatible with the recent version and I download it from the internet that runs normally

### ISSUE THREAD

**Issue by Wesleyjor6** [stenzek/duckstation#1577]
Hello I came to report a problem about the emulator in the Play Store it showed normally from the Play Store and now it is saying that it is not compatible with my phone I find it very strange because I download an APK here from the git hub it works normal But I prefer to download it on the Play Store  for very direct questions and my phone is an LG k11 Plus and this emulator runs normal on my phone although the Play Store is verified that the is not compatible anymore on the phone it still runs the Emulator Could you fix this?

**Comment by jpchow26** [comment]
I would continue to use github then to update the app. It may run but the hardware is too slow to be supported officially.

**Comment by stenzek** [comment]
I excluded around 10k low-spec devices because they were having performance issues, leading to ratings tanking from devices which did not meet the minimum requirements.

Especially for the armv7 recompiler, you really need a CPU faster than 1.5ghz on Android. 1.0ghz+1.5ghz isn't sufficient for heavier games.

As @jpchow26 said, you can still grab the apk from github and it'll work. But on the play store I've had to set some minimum requirements, this way it doesn't waste users time if their device is too slow.
