### ISSUE TITLE
Feature Request: Tessellation,  custom mapping, quad renderering, and  per-pixel lighting 

### ISSUE THREAD

**Issue by ADormant** [stenzek/duckstation#1601]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Dolphin has per-pixel lighting (should be possible with Z-buffer also for PS1) and Ishiiruka  supports  tessellation  and custom maps. 
 Edgbla's closed source  unreleased plugin apparently has tessellation and  quad renderering for years. Quad renderering improves some artifacts inherent to PS1. Anyway thank you for improving PS1 emulation.
https://github.com/Tinob/Ishiiruka

https://forum.emu-russia.net/viewtopic.php?f=29&t=1188&start=20

https://forum.emu-russia.net/viewtopic.php?f=29&t=1192&sid=d0f03d07d91596250caa9c286d8fac35&start=640

http://www.emutalk.net/threads/54527-edgbla-s-gpuBladeSoft-v1-42a

![4c38600b9349](https://user-images.githubusercontent.com/10523326/107154709-c2c8e280-6974-11eb-9823-07e08634aafb.png)

**Describe alternatives you've considered** 

**Additional context**

**Comment by foxsevent** [comment]
> Dolphin has per-pixel lighting (should be possible with Z-buffer also for PS1)
Yeah PS1 doesn't have a Z-buffer so that maybe an issue here.
That's why PGXP exist to try to correct a few issues on the PS1 that lack of Z-buffer creates like warping textures.
Also I'm pretty sure that most PS1 games have lighting baked into the textures, rather than actual lighting engines, but I dunno how per pixel lighting works so who knows.

**Comment by stenzek** [comment]
Tesselation requires displacement maps to actually be useful, otherwise you'd just creating extra geometry on the same plane with no benefit.

Per-pixel lighting is debatable - there's no bump maps for the PS1, not to mention actually getting the light data from the GTE to the GPU in the first place would require even slower than PGXP-like tracking.

I'm not convinced quads vs triangles would be any benefit, since the games were clearly designed with quads -> two tris in mind.

Texture replacement is WIP, see https://github.com/stenzek/duckstation/tree/texture-dumping-2.0 and https://github.com/stenzek/duckstation/issues/2
