### ISSUE TITLE
[Android] Rewind not working

### ISSUE THREAD

**Issue by stagestage** [stenzek/duckstation#1621]
I really love the fact that the 'Rewind' feature is part of Duckstation however I can't get it working. I've bound it to a button but each time I hold the button, the game freezes. Releasing the button makes everything go back to normal.

I am using Duckstation on Nvidia Shield.

Thank you

**Comment by stenzek** [comment]
Runahead/rewind is deliberately not exposed on Android - the code is all there since it's the same code which runs on desktop, but it's not listed in the UI so you can't enable it. Most devices are not powerful enough, and unfortunately with the way that typical Android users act, results in ratings tanking because of unrealistic expectations.

I'll remove the hotkey binding so it's not confusing.

**Comment by stagestage** [comment]
@stenzek Thank you for the explanation, maybe a notification could pop up stating this when enabling it instead of removing it all together?

**Comment by Nucleoprotein** [comment]
But it will not work, button is there by mistake.

**Comment by eadmaster** [comment]
could you reconsider showing this feature and leaving disabled by default?

I've tested rewind with the libretro core, and it was running mostly fullspeed with 2D games...
