### ISSUE TITLE
Broken Dithering pattern In Silent Hill [SLUS-00707]

### ISSUE THREAD

**Issue by AndrzejSzpadel** [stenzek/duckstation#1641]
![Dither](https://user-images.githubusercontent.com/75213772/107856784-db307580-6e2a-11eb-817f-c4244e7c3658.png)
![Dither2](https://user-images.githubusercontent.com/75213772/107856866-775a7c80-6e2b-11eb-897f-7e255626766e.png)
Hello.

Dithering Pattern seems to be broken showing square dot pattern even on solid color, like grey fog or very dark surfaces making it visually unpleasing, on real console dithering renders in similar fashion except it is excluded on solid color, making it much cleaner looking.
Issue appears on every renderer, and persist through/scales with internal resolution with dithering scaling enabled.

is there any solution to fix this problem?

**Comment by stenzek** [comment]
Are you sure you are correct here? I believe dithering is applied on all colours, assuming it's enabled. The dithering formula is as listed in https://psx-spx.consoledev.net/graphicsprocessingunitgpu/ under `24bit RGB to 15bit RGB Dithering (enabled in Texpage attribute)`.

It might just be less noticeable on console due to the composite video output.

For what it's worth, you can disable dithering, as well as scaling the pattern in enhancements.

**Comment by foxsevent** [comment]
This maybe the case as it mentions the dots 
`The intended effects of dithering is often lost in emulation due to the emulators not emulating the system's video output, but rather only the RGB signal the graphics processor generates. The dots or lines appear as they actually are with no blurring`
https://emulation.fandom.com/wiki/Dithering
I've never seen those dots on og hardware and other emulators official and unofficial, not even screen shots.

**Comment by stenzek** [comment]
Nevermind, there was an issue here - an off by one error in one element of the 4x4 dither matrix. Fix will be pushed later today.

**Comment by AndrzejSzpadel** [comment]
Thank you for fixing problem :) 
For dither comparisons i was using PSOne connected with RGB Scart to 32'' TV and picture was sharp as it can be so dithering is easily visible.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/0d13e1013de49576c0018ec752c558175d56263f (preview build).
