### ISSUE TITLE
[Feature Request] VR (Virtual Reality) toggle support

### ISSUE THREAD

**Issue by SaberAkiyama** [stenzek/duckstation#1647]
I was hoping support VR support, it will be great like the other PSX emulator on Android devices

Like this one:
![Screenshot_2021-02-16-14-48-21-07_fb03ef0c8b28a89953d9b4d28ff1e82b](https://user-images.githubusercontent.com/48464326/108028137-4d40ce80-7066-11eb-991b-d180e33fad4e.jpg)

**Comment by stenzek** [comment]
I'm not sure how well fudging the projection to render two eyes would work for the PS1.

**Comment by SaberAkiyama** [comment]
Like on ePSXe emulator for Android. It has a VR support

**Comment by stenzek** [comment]
Looking at epsxe's "VR" support, both eyes are the same, so I don't really see the point - you may as well just use another app to duplicate the screen or something.

**Comment by stenzek** [comment]
Or, alternatively, a postprocessing shader to distort the image. But like I said, unless you're drawing two eyes with the appropriate projection changes, it's not going to be 3D in VR, it'll just be a 2D image with no depth.

And due to the PS1's architecture, I'm not sure if reprojection would work well. Not to mention games which postprocess vertices wouldn't work.

**Comment by SaberAkiyama** [comment]
Yeah, I don't think VR support didn't work in this app. Thanks mate

**Comment by DCxDemo** [comment]
This 2018 article about EmuKit 2 showcases some stereo screenshots, it seems like native vr is kinda possible for at least some games. github repo was not updated ever since though.
https://medium.com/webmr/emukit-2-immersive-psx-n64-vr-on-the-web-7c1ec110a592
https://github.com/exokitxr/emukit

**Comment by AARP41298** [comment]
i thought that i was the first asking for a VR mode, i'm glad that i'm not the only one

There's a mod that activate the discontinued 3D vision of the nvidia GPU cards, named Helix Mod
And exist another program to do this called trideft (thats another story)
In the discord server of helix mod, i found a guy that  achive the sterescopic 3d in this games
![image](https://user-images.githubusercontent.com/33246631/123206377-30d3f900-d481-11eb-9bfe-cd9bcadfe2d5.png)

Also, searching in the compatibility list of helix mode, it appears de n64, ps2 and ps3 emulator, also a ps1 emulator called pcsxr (i never heart that before) that in conjuntion with the PGXP plugin enables the 3D
![image](https://user-images.githubusercontent.com/33246631/123205533-b656a980-d47f-11eb-8f20-e950df0f68dc.png)

btw, trying something stup... i use the files of the helix mod for rpcs3 in duckstation, following the istructions (using OGL instead of DX) and these are the results
![ps1 with ps3](https://user-images.githubusercontent.com/33246631/123207501-169b1a80-d483-11eb-9ca6-5788c2f45781.png)

@stenzek could you re-open this?

**Comment by stenzek** [comment]
No. I have no interest in implementing such a feature, like I said it wouldn't work very well/at all anyway, due to lacking depth information and projection happening in the GTE instead of the GPU.

**Comment by AARP41298** [comment]
:,v ty for reply

**Comment by SaberAkiyama** [comment]
> :,v ty for reply

It's said need GPU implementation for VR. But it requires DirectX or Vulkan API.
