### ISSUE TITLE
Glitches during the opening logos in Final Fantasy 7 (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#170]
I apologize if these aren't glitches and the game is just like this. I couldn't find any footage of it being played on original hardware. 

The bottom of the Squaresoft "A" is a bit glitchy.

![SCUS-94163_2020-03-26_11-34-24](https://user-images.githubusercontent.com/31968468/77598813-ecdd0600-6f56-11ea-9a78-8617f36199b9.png)

The Sony message looks like this as it fades out. 

![SCUS-94163_2020-03-26_11-35-28](https://user-images.githubusercontent.com/31968468/77598838-ff573f80-6f56-11ea-8e07-602d2ac2ee0b.png)

**Comment by stenzek** [comment]
I assume it's writing to each field independently, so unless you emulate the interlaced output it's not going to show "correctly". FF7 did look a little flickery on my TV here, I'll have to check it again.

**Comment by ggdrt** [comment]
The garbled pixels on the SquareSoft logo isn't a glitch from what I remember, it's just not very visible if at all on original hardware.

The "Sony Computer Entertainment America Presents" scene is one of those weird cases. That scene runs in 480 interlaced mode and outputs from a single framebuffer region which is typical for 480i, but instead of letting the video output handle the interlacing the game itself draws to the framebuffer region in an interlaced fashion. I'm not sure if there's a good solution for these kind of cases other than emulating the interlaced output like you said, and either way there's going to be interlacing artifacts when the logo fades in/out.

**Comment by ggdrt** [comment]
The garbled pixels on the SquareSoft logo isn't a glitch from what I remember, it's just not very visible if at all on original hardware.

The "Sony Computer Entertainment America Presents" scene is one of those weird cases. That scene runs in 480 interlaced mode and outputs from a single framebuffer region which is typical for 480i, but instead of solely letting the video output handle the interlacing the game also draws to the framebuffer region in an interlaced fashion. I'm not sure if there's a good solution for these kind of cases other than emulating the interlaced output like you said, and either way there's going to be interlacing artifacts when the logo fades in/out.

**Comment by stenzek** [comment]
Indeed. I already emulate the interlaced output with "weave" deinterlacing, but it doesn't look great - hence the "force progressive output" option. But, some games are dependent on interlaced rendering (skipping field being displayed), so the "force progressive output" option will probably turn into a "force progressive rendering" as well.

**Comment by stenzek** [comment]
Should be fixed in latest master if you disable the force progressive scan option. I'd recommend keeping it enabled though, as it'll give you combing artifacts in other 480i games which don't need it enabled.

Eventually I'll add a gameini system to force disable these enhancements on problematic games.

**Comment by kurayami6** [comment]
Thanks.
