### ISSUE TITLE
Frontend Support (Android)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#1821]
Would it be possible to enable frontend Support for the Android version of DuckStation? Frontends like Reset and Dig allow users to launch games from different emulators from one menu.

**Comment by andercard0** [comment]
> Would it be possible to enable frontend Support for the Android version of DuckStation? Frontends like Reset and Dig allow users to launch games from different emulators from one menu.

Would you mind to FILL the template with your request correctly as follows : ? 


**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by stenzek** [comment]
You can already do this. Launch the Emulation Activity. 

As for how to do that, that'll depend on your frontend.

https://github.com/stenzek/duckstation/blob/a34f0d55996fd155a5c355be617e69eeb51ca61a/android/app/src/main/java/com/github/stenzek/duckstation/MainActivity.java#L378
