### ISSUE TITLE
Not compatible anymore the play store version on my Redmi 9 Android 10

### ISSUE THREAD

**Issue by Gamemulatorer** [stenzek/duckstation#1881]
![Screenshot_2021-03-29-09-24-13-997_com android vending](https://user-images.githubusercontent.com/37603562/112775919-cae9f800-9070-11eb-94ad-e8ca4c864395.jpg)

### My Phone Specs
https://www.google.com/amp/s/m.gsmarena.com/xiaomi_redmi_9-ampp-10233.php

**Comment by stenzek** [comment]
If your phone is the PowerVR GPU variant, I've excluded those due to both the OpenGL and Vulkan drivers being completely broken. And since I don't have one and the shader compiler provides no useful error message, I can't fix it. But you can always download the APK version from GitHub.

If you have the Mali variant, it should be unexcluded now.
