### ISSUE TITLE
Add multiple touch buttons on android like Fpse64?

### ISSUE THREAD

**Issue by Gamemulatorer** [stenzek/duckstation#1893]
![Screenshot_2021-03-31-12-14-29-761_com emulator fpse64](https://user-images.githubusercontent.com/37603562/113090000-5d2dff80-921b-11eb-99b5-88cad85db9e2.jpg)
![Screenshot_2021-03-31-12-17-03-126_com emulator fpse64](https://user-images.githubusercontent.com/37603562/113090146-b433d480-921b-11eb-83a8-eaa6f9a75640.jpg)

**Comment by stenzek** [comment]
No idea what you're asking for - please fill out the template, not delete it.

DuckStation supports multiple touchscreen controller layouts, adding/removing buttons, opacity. Multiple buttons can be pushed at once, as well as "touch gliding" (start with one face button and press another without releasing the pointer).

**Comment by Gamemulatorer** [comment]
In fpse64 I can add Multiple button 1 as a combination of ✖️⚫ as shortcut but duck station doesn't have it.

Sorry for my English :(

**Comment by stenzek** [comment]
I don't see why that's necessary. Enable touch gliding , press the X button, and slide your finger to the O button.

**Comment by Gamemulatorer** [comment]
PPSSPP emulator also have a combo/multiple key but why not implement it on duckstation? 😔
![Uploading Screenshot_2021-03-31-17-25-10-194_org.ppsspp.ppsspp.jpg…]()

**Comment by Gamemulatorer** [comment]
> I don't see why that's necessary. Enable touch gliding , press the X button, and slide your finger to the O button.
> 
> This is a far superior solution to having even more buttons on sc

> I don't see why that's necessary. Enable touch gliding , press the X button, and slide your finger to the O button.

Im not comfortable on that :/
> 
> This is a far superior solution to having even more buttons on screen.
I prefer more buttons on screen :/

**Comment by stenzek** [comment]
This is basically a one person project, which I work on in my spare time. It brings in no money since it's free and has no ads. 

Therefore I have to limit the features to what I have time to work on, and this is not one I am interested in adding at the moment. Sorry.

**Comment by Gamemulatorer** [comment]
OK I understand I will use Fpse64 as of now waiting for duckstation to implement that features on the future 😄

**Comment by stenzek** [comment]
You realise you're being a little disrespectful, right?

Saying "your stuff sucks I'm going to use something else instead" removes all my interest in adding a feature.

Maybe it's better you do. It's a paid all, you can expect them to add your requests since you're paying for it. I'm going to keep my app free and add what I find interesting, and don't really care if you use it or not.

**Comment by stenzek** [comment]
Furthermore, duckstation is **not** epsxe or fpse or whatever. I don't use either of those, so it's based on my own ideas instead. 

And frankly I'm sick of the comparisons. Nobody every says "fpse is bad because it's missing PGXP" or anything like this. But everyone compares duckstation for tiny little things like touchscreen controllers. Personally I find graphical enhancements much more beneficial in the overall experience.

And you don't even have to pay a cent for it. Unlike fpse which seems to make you pay twice for the same app, and it doesn't even have any modern features? Seems kinda lame to me, but whatever, power to them if foolish people pay twice for it when there's better free alternatives.

**Comment by Gamemulatorer** [comment]
Fpse64 is the best ps1 emulator for android especially for 32bit android phone 🤷

**Comment by stenzek** [comment]
Congrarts. I'm blocking you from the repo. Please go shill/troll somewhere else.
