### ISSUE TITLE
Add 16:3 / 48:9 (3 monitors setup) to Aspect Ratios list

### ISSUE THREAD

**Issue by DrBoiffard** [stenzek/duckstation#1913]
Hello,

First of all thaks for the amazing work with this emulator. 

It'd be possible to add 48:9 (I've seen sometimes refered as 16:3) to the aspect ratios list?  I use a 3 monitor setup merged with nivida surround. The widest aspect ratio available right now (32:9) it's not enough. 

48:9 is very common among racing gamers, I've searched a little here but I haven't found this request before. Maybe I'm the first one creatint the Issue here but I don't think I'd be the only one missing it :) 

Thank you very much.

**Comment by stenzek** [comment]
Easy enough to add, but I'm not sure it'll work very well - games tend to have their own frustum culling which is already noticeable in 16:9 aspect ratios and such, let alone wider.

**Comment by DrBoiffard** [comment]
Thank you very much.

I'm only going to use this resolution for racing games, and usually you're looking to the central screen and those on the side only add speed sensation.  So i'd prefer a little bit of frustum culling rather than the black bars on the sides that appear when I use the 32:9 ratio. 

((I don't know if it's also possible (as may depend a lot on the games and not the console) to separate 2d and 3d layers in the wide hack. Let 2d sprites and menus in it's original 4:3 proportion, and only applying the widescreen hack to the 3d engine. It'd be very interesting for racing games as it'd mantain the 2d GUI layer centered and proportional. ))

**Comment by DrBoiffard** [comment]
In R4, when I play with the widescreen hack on/and off, I see the GUI layer mantain the position while the 3D "moves" . So thinking again about what I put there in the last paragraph, it won't be impossible and maybe it's easier enough to have a widescreen-related check to mantain the 4:3 in this layer.  (I guess it'd be a not very complex function to "center" the GUI/upper 2D layer instead of starting to render it in top left position) 

Personally I think that option would be the optimal  for playing in 48:9, at least racing games. Supermodel and some teknoparrot games behaves like this with 48:9 resolution and it's pretty cool as it's like playing in it's original proportion with the screen expanded in both sides, and the menus are a lot more readable.  Maybe it's interesting in other kind of games, too, and to use it in not-that-wide resolutions. I think any game that renders a 2D layer above the 3D engine can benefit of this option, specially if there is text involved, some fonts are horrible when stretched even when it's only to 16:9.

**Comment by stenzek** [comment]
Not really. All the PS1 GPU sees are 2D vertex coordinates. There's no way to differentiate between UI and actual polygons. Sure, you could use heuristics, but it'd be slow and not very reliable.

**Comment by DrBoiffard** [comment]
I'm sorry but I think I'm not explaining very well. I'm only talking about "centering" and "not stretching horizontally" the part which isn't affected by the widescreen hack, which has to be possible and irrelevant in performance. **This would probably make the impression that you're in 4:3 until  some 3D is rendered down**. Or "4:3" + rubbish in the extra area, would be hidden in normal conditions, specially in the menus. 

Don't know, I haven't seen the code involved in the widescreen hack but I think it should mean constant values while the resolution is untouched. Nothing about heuristics nor really accountable in performance. For every resolution there would be a fixed, constant area to render this _"unaffected-by-the-hack layer"_, instead of fullfilling the screen.

**Comment by DrBoiffard** [comment]
This is the by-default behaviour of the widescreen hack in supermodel. For a any given wide resolution, the central 4:3 area is a 1:1 reproduction of what it'd show in a 4:3 display...and for the rest of the display area, instead of having black borders, more 3D is shown: https://www.youtube.com/watch?v=c4G4-9WWEAg

Don't know, the only difference from what I was seeing in R4, is that the "unaffected part of the widescreen hack" is being stretched to fulfill the screen, instead of being let in the center unstretched. If that's possible to have in a related-check to the widescreen hack, it'd be only matter to test game by game, but I guess for every racing game in the catalogue it'd be pretty to have this behaviour.

**Comment by SuperLumberjack** [comment]
Excuse me, could I suggest a request relative to an aspect ratio too here please? I think it's not off-topic.

_Would that be possible that you add a **32:21** aspect ratio please?_

I know it's close to 3:2, but in fact I noticed that the PS1 versions of the Tomb Raider games need exactly a 32:21 aspect ratio (4:3 x 8:7 in fact) to have the exact same PAR than the PC versions. Some emulators like _BizHawk_ for example propose this aspect ratio by default for the Tomb Raider games (and the plugin "_Pete's OpenGL Windows GPU Version 1.78_" for _ePSXe_ and _PCSXR-PGXP_). But the picture quality is of course a lot better with DuckStation (I really love your emulator), it's why I ask here.

Thank you very much! It would be really great if you could add this!

**Comment by Richard-L** [comment]
https://github.com/stenzek/duckstation/issues/1913#issuecomment-823538070

^ this solution would be amazing but I'm afraid Stenzek's explanation already implies it isn't possible.

**Comment by Richard-L** [comment]
@SuperLumberjack You actually can never get the proportions right in Tomb Raider. The glyphs and all 2D like loading screens etc will only look correct in 4:3. All 3D will only look right in PAR1:1 (and with the right crop). So since of course the 3D is more important latter is what most people go with.

**Comment by DrBoiffard** [comment]
> 
> 
> [#1913 (comment)](https://github.com/stenzek/duckstation/issues/1913#issuecomment-823538070)
> 
> ^ this solution would be amazing but I'm afraid Stenzek's explanation already implies it isn't possible.

I still don't get why but OK, I  just opened the request for the 48:9 option, so even possible this would be a different feature request I think.  Sorry for the random thoughts about the widescreen hack!

**Comment by SuperLumberjack** [comment]
> 
> 
> @SuperLumberjack You actually can never get the proportions right in Tomb Raider. The glyphs and all 2D like loading screens etc will only look correct in 4:3. All 3D will only look right in PAR1:1 (and with the right crop). So since of course the 3D is more important latter is what most people go with.

Thanks for your answer ! :-)

Yes, I know that the loading screens won't look correct with this aspect ratio, but it isn't really important for me. The 3D is more imporant indeed.

I will just show you how it looks with the emulator _BizHawk_ (but as I said, the plugin "_Pete's OpenGL Windows GPU Version 1.78_" for ePSXe and PCSXR-PGXP does natively the same too, so I'm not the only or the first one who wanted to correct this apparently) with the default settings:

![01 - BizHawk - Aspect Ratio Selection - Use system's recommendation](https://user-images.githubusercontent.com/82117649/116006394-4b1d6200-a60b-11eb-8cec-f4f67fa79e5d.png)

![02 - BizHawk - Tomb Raider - Texture perfectly squared (resolution 424 x 424)](https://user-images.githubusercontent.com/82117649/116006399-540e3380-a60b-11eb-8e22-b621cbeaa137.png)

I checked the texture in red with MS Paint and the resolution is exactly _424 x 424 pixels_.
The resolution of the whole image is 1646 x 1080 (32:21 AR).

Here is with DuckStation with a 4:3 aspect ratio and the crop option on "All Borders":

![03 - DuckStation - Tomb Raider - AR 4 3 - Texture not squared (resolution 371 x 424)](https://user-images.githubusercontent.com/82117649/116006460-b0715300-a60b-11eb-98a1-633996281e31.png)

The resolution of the texture is _371 x 424 pixels_. It's not squared.

We are close with a 3:2 aspect ratio:

![04 - DuckStation - Tomb Raider - AR 3 2 - Texture not perfectly squared (resolution 417 x 424)](https://user-images.githubusercontent.com/82117649/116006502-db5ba700-a60b-11eb-8463-c56c029ac718.png)

But it's not squared yet! The resolution of the texture is _417 x 424 pixels_.

With the PC version, the texture is perfectly squared (but the FOV is different as you know):

![05 - Tomb Raider - PC ATI GLRage - Texture perfectly squared (resolution 349 x 349)](https://user-images.githubusercontent.com/82117649/116006541-00e8b080-a60c-11eb-96c7-96e7f3d85650.png)

To find the correct aspect ratio, I simply did like that:

_We are starting from a 4:3 resolution of "1440 x 1080" and we wanted to know how to go from a texture of "371 x 424 pixels" to "424 x 424 pixels".
We just have to do this calculation :_

_(4/3) x (424/371)
= (4/3) x (8/7)
= **32/21**_

I don't know why the developers chose to not have the correct PAR, but what is cool is that with our modern tools, we can fix this ;-)

I'm really sorry to have taken so much place on this thread, but I thought it would be better to not create a new one just for this, considering that I have the same type of request.

Thanks you very much!

**Comment by Richard-L** [comment]
@SuperLumberjack nice comparison.

Have you tried measuring the red square in Duckstation if it is set to PAR1:1? Also might need to experiment with the crop settings. This combination of the two is different per game to obtain the right proportions. Thankfully DS offers per game user settings.

**Comment by SuperLumberjack** [comment]
@Richard-L 

Thank you very much! You're the best! 👍 

I never thought that it could be correct simply by choosing a PAR 1:1, but now it's perfectly squared! :-D

![06 - DuckStation - Tomb Raider - PAR 1 1 - Texture perfectly squared](https://user-images.githubusercontent.com/82117649/116102813-4f02c000-a6af-11eb-951e-fb88ad532bbc.png)

In fact, the resolution is initially of : _366 x 240_

I imagined something else.

So the aspect ratio is:

_183:120_ or _1.525:1_

Therefore, the developers chose the right PAR, but with the wrong DAR. It explains why the FOV is different too on PC, because the DAR was in 4:3 too I suppose. But with the correct PAR, the DAR would have been superior to a 4:3 aspect ratio on PS1.


Thanks a lot! 👍

**Comment by SuperLumberjack** [comment]
**Little problem:** The PAR 1:1 works for Tomb Raider 1 and 2, but not for the 3, 4 et 5, because the resolution isn't _366 x 240_, but _512 x 240_.

But however, the aspect ratio displayed should be the same.

**Comment by Richard-L** [comment]
@SuperLumberjack maybe come on DS's discord and tag me (@posix) for TR aspect settings discussion. I know this topic is very confusing across the games.

Also know that I've annoyed Stenzek with this in the past, and he's not very inclined to talk about it or explain anymore ;)

**Comment by SuperLumberjack** [comment]
@Richard-L 

Yes, why not ? :-)
I will see if I had enough time in the next days. Thanks!

**Comment by SuperLumberjack** [comment]
I just checked the aspect ratio for Tomb Raider III and apparently it's more complicated for this one, the episode 4 and the episode 5, because the resolution is different than the 2 first with a resolution of "_512 x 240_" instead of "_366 x 240_", but the resolution doesn't define the correct aspect ratio to use.

The camera is different from the 2 first episodes too and if I am front of a squared texture (there aren't lots of them), the vertical edges aren't parallel, so I had to move the camera to find the right angle (and used Fraps to capture the frames in video).

Here we can see with the **PS1 version of Tomb Raider III** (4:3 AR) that the resolution of the texture is "_472 x 566 pixels"_ (approximately):

![01 - DuckStation - Tomb Raider III - AR 4 3 - Texture not squared (resolution 472 x 566)](https://user-images.githubusercontent.com/82117649/116371503-c9485700-a80b-11eb-9b55-bc077fae1a28.png)

If we choose a aspect ratio of "_1.525:1_" like the 2 first episodes, it gives a resolution of "_540 x 566 pixels_", because:

_(1,525 x 472) / (4/3) = 539,85_

So it isn't enough wide.

With the **PC version**, it's completely squared:

![02 - Tomb Raider III - PC Steam - Texture squared (resolution 472 x 472)](https://user-images.githubusercontent.com/82117649/116373473-a7e86a80-a80d-11eb-8734-1aa4db3a977b.png)

The resolution of the texture is "_472 x 472 pixels_".

In fact, to matche the PC aspect ratio for Tomb Raider 3, 4 and 5, we should be more close to:

_(566 x (4/3)) / 472 = 1,59_

And so the resolution should be close to 1726 x 1080 pixels instead of 1646 x 1080 for the 2 first episodes.

The problem is that the value of this aspect ratio isn't very precise because we can't deduce it from the resolution of the games.

I will think about all of that. Maybe the game was developed in another resolution accepted by the console which could define the aspect ratio like TR1 and 2, and then they chose a final resolution of "**512 x 240 pixels**".

It could be "_384 x 240 pixels_"...

**Comment by SuperLumberjack** [comment]
In this comment, a guy talk about the resolution of "_384 x 240 pixels_", but for the 2 first games:
https://www.sega-16.com/forum/showthread.php?4119-Tomb-Raider-was-over-rated&p=354175&viewfull=1#post354175

_(the entire thread: https://www.sega-16.com/forum/showthread.php?4119-Tomb-Raider-was-over-rated/page7 )_

It's strange, because DuckStation shows me that the resolution is "_366 x 240 pixels_" for the 2 first games, which corresponds to the pixel aspect ratio too. Maybe this guy knows something that we ignore... ^_^

**Comment by stenzek** [comment]
The rendering (VRAM) resolution versus the display resolution can be different, particularly when overscan cropping is enabled.

Use the GPU debug window and scroll down to see the full details, or set cropping to none.

**Comment by SuperLumberjack** [comment]
I tested the Tomb Raider games with the cropping set to "_None_" and it shows me that the 2 first Tomb Raider have a resolution of "_36**8** x 240 pixels_". With the cropping set to "_All borders_", the resolution is "_36**6** x 240 pixels_" like above, but with a PAR 1:1, the picture is exactly identical and there is no distorsion of the image (there are just 2 more pixels on the right with the 368 x 240 resolution).

But for all the games (like "_Legacy of Kain: Soul Reaver_" for example), I noticed that I can only have a correct 4:3 image with the cropping set on "_All Borders_" and the aspect ratio set on "_4:3_". With "_Only overscan area_" and "_None_" for the cropping, the PAR isn't correct for me.

But with the AR set on "Auto (Game Native)" and the cropping on "Only overscan area", I agree that it's like on a CRT. But on a modern screen it isn't correct. I talked about that here:

https://github.com/stenzek/duckstation/issues/1945#issuecomment-825810228

It's why I always choose a 4:3 aspect ratio with the cropping set on "_All Borders_". So when I talk about an aspect ratio, I will always talk about it with the cropping set on "_All Borders_" to avoid some confusion ;-)

But I can only talk about what I can observe at the surface, because I don't have enough technical knowledge about how the emulator and the PlayStation work.

By the way, how can I use the GPU debug window?

**Comment by stenzek** [comment]
Like I said, check the GPU debug window. TR3 was rendering at 512x224 for me.

**Comment by SuperLumberjack** [comment]
Yes, but it's only with the cropping set on "_Only Overscan Area_":

![Tomb Raider III - Cropping set on Only Overscan Area](https://user-images.githubusercontent.com/82117649/116424781-15ae8980-a842-11eb-8803-3ea070991f0d.png)

With "_None_" and "_All Borders_", I have "512 x 240":

![Tomb Raider III - Cropping set on None](https://user-images.githubusercontent.com/82117649/116424917-31199480-a842-11eb-9b92-3481ff6edc7f.png)

![Tomb Raider III - Cropping set on All Borders](https://user-images.githubusercontent.com/82117649/116424966-3b3b9300-a842-11eb-8553-e81080149db1.png)

But as I said, for me it's only relevant to choose "_Only Overscan Area_" with a CRT screen and the aspect ratio set on "_Auto (Game Native)_": https://github.com/stenzek/duckstation/issues/1945#issuecomment-825810228

On a modern screen I find that it's more correct to generally choose "_4:3_" with the cropping set on "_All Borders_".

By the way, with the Tomb Raider games we get an image even more stretched vertically because of the cropping if we choose "Only Overscan Area" (but here I chose PAR 1:1).

I think that maybe the original PAR for **Tomb Raider 3**, **4** and **5** was thought to match a resolution of "_384 x 240_" (I think it's one of the resolutions accepted by the console) and then the developers chose to keep a final resolution of "_512 x 240_".

Because with a ratio of "_384:240_"  or "_24:15_" (_1.60:1_), the squares look squared. But I don't know how to be sure that it's the correct pixel aspect ratio, but it's close.

And for **Tomb Raider 1** and **2**, the correct PAR is simply defined by the resolution of "_366 x 240_" (with the cropping set on "All Borders") or a _PAR 1:1_.

**Comment by SuperLumberjack** [comment]
I found this about some the timings for the OSSC: http://junkerhq.net/xrgb/index.php?title=Optimal_timings

It's written that the console mode for Tomb Raider 1 and 2 is "_**384x240** @59.82Hz_". Strange!

**Comment by SuperLumberjack** [comment]
By the way, I don't know if you know the "_**OpenLara**_" project, but I tried to load a PS1 level in it and we can notice that the aspect ratio is correct with Tomb Raider 3:

http://xproger.info/projects/OpenLara/

![OpenLara - Tomb Raider III with PSX level](https://user-images.githubusercontent.com/82117649/116450451-9c239500-a85b-11eb-84b8-6250e2352758.png)

![OpenLara - Tomb Raider III - Texture squared (resolution 340 x 340)](https://user-images.githubusercontent.com/82117649/116450506-aba2de00-a85b-11eb-924e-65a734ea7968.png)

![OpenLara - Tomb Raider III - Texture squared (resolution 574 x 574)](https://user-images.githubusercontent.com/82117649/116450520-b1002880-a85b-11eb-9dbb-bd83c63406cb.png)

It's why I think it's really important to get the correct aspect ratio for these games! It wasn't possible (or difficult) at the time, but today I think that we can try to fix lots of things that weren't right on a CRT screen.

In any cases, this project is rather impressive. I wonder why the textures are like on PC:

![OpenLara - Tomb Raider I with PSX level](https://user-images.githubusercontent.com/82117649/116450994-44395e00-a85c-11eb-8a59-2ad37e59b420.png)

![OpenLara - Tomb Raider I - Gym level](https://user-images.githubusercontent.com/82117649/116451037-50bdb680-a85c-11eb-9e9f-fb30d5e8602d.png)

On PS1 the texture are more separated.

![DuckStation - Tomb Raider I - Gym level](https://user-images.githubusercontent.com/82117649/116451592-fbce7000-a85c-11eb-8897-88d7f749b6f8.png)

But I can understand that a project that is specific to only 5 games doesn't work in the same way than a emulator which is thought to run lots of other games.

**Comment by SuperLumberjack** [comment]
I found this:

> In terms of resolutions, the console was constrained by the NTSC and PAL Television standards. For US and Japanese markets, a developer could pick an horizontal resolution of 256, 320, 384, 512, or 640. Vertical resolution was either 240 pixels (by skipping every other scanline) or 480 pixels interleaved. Both vertical modes ran at 60Hz. The only difference between NTSC and PAL is the increased vertical resolution (256/512 instead of 240/480) and the lowered refresh rate (50Hz).
> 
> Mode   -   NTSC(60Hz)   -   PAL (50Hz)   -   Remark
> ==========================================================
> 
> 0   -   256 x 240   -   256 x 256   -   Non-Interlaced
> 1   -   320 x 240   -   320 x 256   -   Non-Interlaced
> 2   -   512 x 240   -   512 x 256   -   Non-Interlaced
> 3   -   640 x 240   -   640 x 256   -   Non-Interlaced
> 4   -   256 x 480   -   256 x 512   -   Interlaced
> 5   -   320 x 480   -   320 x 512   -   Interlaced
> 6   -   512 x 480   -   512 x 512   -   Interlaced
> 7   -   640 x 480   -   640 x 512   -   Interlaced
> 8   -   384 x 240   -   384 x 256   -   Non-Interlaced
> 9   -   384 x 480   -   384 x 512   -   Interlaced
>     
> 
> Notice the 384 pixels wide modes (8 and 9) which seem to have been a late addition based on their id.

_(source: https://fabiensanglard.net/doom_psx/ )_

I definitely think that Tomb Raider 3, 4 and 5 were thought with an aspect ratio relative to a resolution of 384 x 240 pixels.
For me the good aspect ratio for **Tomb Raider 1** and **2** is "_**1.525**_" (366:240) and for **Tomb Raider 3**, **4** and **5** is "_**1.6:1**_" (384:240)!

With the cropping set on "_All Borders_" of course!

**Comment by stenzek** [comment]
This has gone way off topic. As far as I'm aware, the AR calculations are correct for the PS1, comparing to the PC is pointless.

As for the original issue, I've added custom ARs now, just need to hook up the UI for it.

**Comment by stenzek** [comment]
Custom aspect ratios are implemented in the latest preview build. You can set it that way, or use "match window" to use the window size/resolution as the AR.
