### ISSUE TITLE
Cannot login with my RetroAchievements account

### ISSUE THREAD

**Issue by luis0henrique** [stenzek/duckstation#1966]
**Game details**
No related.

**Description of the issue / bug**
I tried to login with my RetroAchievements account, but a Login Error message appears every time saying: 

_Login failed. Please check your username and password, and try again._

I don't believe my username and password are the issue, since I'm able to login in Retroarch with no issues.

**duckstation.log:**
E(HTTPStatusCallback): WinHttp async function 0000000000000005 returned error 12175
E(FormattedError): Cheevos Error: Login failed: empty response
E(LogFailedResponseJSON): API call failed. Response JSON was:

**Hardware/software**
Core 2 Quad Q8400 2.66GHz
Radeon HD 8490 (a.k.a. R5 235X)
4 GB Ram DDR2
Windows 7 Home Premium
OpenGL

**Emulator version**
0.1-3771-g8df0496d (dev)

**Comment by stenzek** [comment]
This is not an emulator problem - it's because you're using Windows 7 and it does not support TLS 1.2.

If you have the required update installed, you can use the quick fix here: https://support.microsoft.com/en-us/topic/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-winhttp-in-windows-c4bd73d2-31d7-761e-0178-11268bb10392 to enable it.

But I can't help you any more than that. I don't support Windows 7 because I don't have any hardware old enough to run it, and MS no longer supports it either.

**Comment by stenzek** [comment]
Regarding other emulators supporting it, that's because they ship their own TLS library. I use the library provided with Windows, because it's silly to ship a multi-megabyte dependency just for a dead OS.

**Comment by luis0henrique** [comment]
Yeah, I can't wait to change  will finally move to Win10. Windows 7 has only been giving me a headache lately.
Regarding TLS 1.2 fix, I changed some things on Registry and now is working! Thanks!
