### ISSUE TITLE
No audio during the opening FMV of Akuji the Heartless (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#197]
Sound is fine in the rest of the game, just the opening FMV is completely silent.

**Comment by stenzek** [comment]
Guessing SPU issue - audio is playing from the CD-ROM but the SPU's master volume is muted.

**Comment by stenzek** [comment]
Please re-test on latest build.

If this is the same issue as I found with the PSF, it was actually caused by the GPU/timer, nothing to do with the SPU! I defer GPU line updates for as long as possible for performance reasons, but I forgot to consider line interrupts as one of the cases so those interrupts would be delayed until vblank. Should be fine now, with what should be an almost immeasurable performance impact for games which rely on it.

**Comment by kurayami6** [comment]
The Opening FMV now has audio but Akuji himself is silent during the first cutscene with Baron Samedi.

**Comment by stenzek** [comment]
Is the cutscene audio still broken? Can't seem to reproduce it.

**Comment by kurayami6** [comment]
Fixed as of the latest version.
