### ISSUE TITLE
Defcon 5 strange effect on screen

### ISSUE THREAD

**Issue by ToniBC** [stenzek/duckstation#1981]
Tested with the latest Nightly version, with effects or enhancements on and off, in Hardware mode under Vulkan. Everything under Windows 10 x64 in its Standalone version.

The game shows how a mesh, as if it were a CRT filter, in other emulators it does not happen, also in hardware mode and with improvements.

Duckstation 0.1-3806 (Standalone)
![Defcon 5 (Spain)-210418-002656](https://user-images.githubusercontent.com/45365478/115128333-68d04300-9fdd-11eb-99b6-4db3f9ffcefa.png)

Beetle PSX HW (for example)
![Defcon 5 (Spain)-210418-002742](https://user-images.githubusercontent.com/45365478/115128345-7f769a00-9fdd-11eb-8abd-d060ae9bf048.png)

The game in software mode works without problems, but in hardware mode it is seen with that problem.

Thanks.

**Comment by stenzek** [comment]
Looks like your bog standard drawing-columns-as-triangles issue - same as Doom etc. Upscaling provides no benefit here, as it's not 3D. Will add a gameini override to force upscaling off.

Beetle has a hack to detect these lines-as-triangles and expand them, but I'm not going to add that since (1) it's a large cost to performance, and (2) it's not 3D and won't benefit from upscaling anyway.
