### ISSUE TITLE
[Request] Texture Replacement

### ISSUE THREAD

**Issue by MojoJojoDojo** [stenzek/duckstation#2]
I don't know of any PS1 emulator that could do that besides a certain emulator plugin I think.

**Comment by stenzek** [comment]
Due to how the PSX GPU samples VRAM for texturing, texture replacement isn't straightforward. But, it's not impossible, and something I'd like to do in the future.

I do have a good idea of how it might be implemented. There'd just be a performance penalty in doing so, as currently I don't use a CPU texture cache, instead leaving everything on the GPU. So the additional cost of hashing, maintaining the CPU copy of VRAM and batch splitting would add up, but PSX games aren't exactly huge polygon pushers so it'd probably be fine.

**Comment by fefo-dev** [comment]
@stenzek I read [this comment](https://old.reddit.com/r/emulation/comments/f0u74q/is_possible_to_implement_a_custom_texture_on_a/fh284er/) by you saying that you would be limited by the texture original size. Is this about the area you'll be given to draw the texture (which should be increased with higher internal resolution I believe) or mipmap-style subtextures that will need redrawing due to low resolution?

**Comment by stenzek** [comment]
Original texture page size (256x256).

This might not be the best granularity though, since it creates way too many texture:palette permutations. I might merge the texture dumping feature I wrote ages ago to show people how difficult of a problem it is ;)

I haven't looked at it closely, but I believe the beetle approach is a bit different, using configurable regions instead of fixed sizes. If that ends up working well, I'll probably just end up implementing that approach in DS - that way packs can be shared.

**Comment by MojoJojoDojo** [comment]
This is now partially done now with this commit : https://github.com/stenzek/duckstation/commit/2745783cd1dd4e5fb4cdf6b24eafe13ab6272bf6

**Comment by fefo-dev** [comment]
Mind sharing some basics @stenzek? I'll tinker with this soon, so it could help some reports (or not, if this is just a preliminary implementation).

**Comment by Kupo91** [comment]
Are there any plans to improve this feature? My texture dumps look all like this :(

![vram-write-918f8194423bd62d3fd079683a76d7fb](https://user-images.githubusercontent.com/41426906/116830822-48db7a80-abac-11eb-9a42-3ce494f90d05.png)

**Comment by foxsevent** [comment]
> Are there any plans to improve this feature? My texture dumps look all like this :(
> 
> ![vram-write-918f8194423bd62d3fd079683a76d7fb](https://user-images.githubusercontent.com/41426906/116830822-48db7a80-abac-11eb-9a42-3ce494f90d05.png)

Plans yes, when the devs find the time and motivation to do it, please don't nag them about as it is demotivating as this is a difficult task since PS1 doesn't have textures in the same as most other systems.

**Comment by stenzek** [comment]
There's a full texture of dumping branch here https://github.com/stenzek/duckstation/tree/texture-dumping-2.0

But I lost interest in it because people kept nagging me.

**Comment by stenzek** [comment]
Work in progress in https://github.com/stenzek/duckstation/pull/2224
