### ISSUE TITLE
emulator freezes/fps drops to 0 when opening menu or saving in Legend of Dragoon.

### ISSUE THREAD

**Issue by TwilitSheikah** [stenzek/duckstation#2002]
SCUS-94491 The Legend of Dragoon (USA)

Upon opening the menu to check stats, money or items fps immediately drops to 0 and the emulator freezes up and all in game music stops completely. Same thing happens when using save spots as well. This also happens when playing Chrono Cross

Happens EVERY time. Turned off cheats, still happened. Restarted game with no cheats still happened. all enhancements set to default, still happened. Tried each renderer (D3D11, Vulkan, OGL, and Software) still happened

Windows 10 Home
Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz, 2701 Mhz, 4 Core(s), 4 Logical Processor(s)
NVIDIA GeForce GTX 1060 6GB
D3D11/OpenGL/Vulkan

Duckstation 0.1- 3835-g5af64243 (master)

**Comment by stenzek** [comment]
Are you sure this isn't intended? The music briefly stops for me for about a second, because the game is reading from the disc, but this seems normal: https://youtu.be/i9CklM8Jats?t=13044

If the emulated speed is dropping below 100%, it's probably the result of I/O delays - these are sometimes caused by slow USB storage devices. Try preloading the disc image in console settings.

**Comment by TwilitSheikah** [comment]
https://youtu.be/TI5nUUz-TYw 

This is what the game is doing when i try to open the menu. it even does it when I used the Preload Disc Image as you suggested.

**Comment by stenzek** [comment]
It's working fine here.

Make sure your dump is valid (compare the hash), and try enabling enhancements one at a time.
