### ISSUE TITLE
Write to MacUpdate for them to list your app there

### ISSUE THREAD

**Issue by MaxPower85** [stenzek/duckstation#2018]
I tried DuckStation on a Mac and it seems pretty good so far... some options seemed to make it crash (the app just crashed, but it didn't lock up the system, so I just reopened it and avoided those settings), but once you set it up and start the game, it seems pretty good.

Since DuckStation doesn't seem to be listed on MacUpdate and MacUpdate has been like one of the main places where Mac users discover apps for a long time (it existed before there was App Store), I thought that it would be a good idea if you list it there, so more Mac users would find out about it and so you could get more people to test it on different Macs.

**Comment by stenzek** [comment]
The Mac support is basically on life-support. I don't own one, so it's unrealistic to expect me to provide first-class support for a platform which I cannot debug and fix issues on. And with 1.3% of the downloads at the time of writing, I'm not going to go and spend $1000 out of pocket on a machine which I have no other use for, and for a project which brings in zero revenue.

The only reason I haven't removed the builds is because they're still appearing to work, but I'll be dropping them if issues crop up, since I have no way of investigating them.

Unless someone else wants to volunteer to maintain it, of course.
