### ISSUE TITLE
The button press area is small.

### ISSUE THREAD

**Issue by Vaqtincha** [stenzek/duckstation#2065]
Could you increase it? It's hard to hit them.

![IMG_20210506_155839](https://user-images.githubusercontent.com/51029683/117288135-9b56b880-ae84-11eb-8159-9fdb5a199b32.jpg)

Thanks.

**Comment by PookaMustard** [comment]
Update your DuckStation, then open the Quick Menu and find the option to configure touchscreen. There should be an option to resize buttons in there. Tap and hold on the button you wish to resize and slide to increase or decrease its size.

**Comment by stenzek** [comment]
This feature already exists.

**Comment by Vaqtincha** [comment]
@PookaMustard I am aware of this option. But that doesn't solve the problem.

**Comment by Vaqtincha** [comment]
@stenzek "Closed" It's ugly of you.

**Comment by PookaMustard** [comment]
When you increase the button size, so does the press area. I just checked, I made a gigantic R1 button possible and every part of it is pressable.

Just increase your button size and stop being a dick to developers for a change.

**Comment by Vaqtincha** [comment]
@PookaMustard Do you understand that huge buttons cover the picture and spoil the general view? 
Yes i'm a jerk but only you are smart.

Thank you for your attitude to the users of this product.

**Comment by stenzek** [comment]
I'm sorry, what do you expect me to say? You can already do what you're asking, resize the buttons...

**Comment by PookaMustard** [comment]
If you admit you're a jerk towards the people who work on this free emulator, _what else did you expect?_ 🙂

**Comment by foxsevent** [comment]
> I'm sorry, what do you expect me to say? You can already do what you're asking, resize the buttons...

I think there's a bit of a misundersting here, I think he wants to increase the size of the press of the button without increasing the icon of said button.

**Comment by Vaqtincha** [comment]
@stenzek I wrote not about the size of the buttons but the size of their hitbox. 
Do I only want for myself ? I want your product to be even better.

**Comment by stenzek** [comment]
Increasing the hitbox would just be confusing - now you have a disconnect between what's visible on the screen, and the action it has. Push in the middle of two buttons and it activates both, without actually being in their circle...

If the buttons themselves are annoying, it's simple enough to reduce the opacity.

Everyone has their requests, but I have very limited time to work on this project (spare time, it's free and not my job), so I have to choose what to implement. I don't see any value in this, only confusion.

**Comment by Vaqtincha** [comment]
@stenzek 

> Push in the middle of two buttons and it activates both

This is how it should be. Games where you have to press two buttons (say O + X), it is unrealistic to do this now.

**Comment by Vaqtincha** [comment]
Well, now there will be a smart proposal: Increase the buttons to half the screen. 😁😁😁

**Comment by PookaMustard** [comment]
> @stenzek
> 
> > Push in the middle of two buttons and it activates both
> 
> This is how it should be. Games where you have to press two buttons (say O + X), it is unrealistic to do this now.

That's literally the very use case for touch gliding. Hold one button then swipe over the other. In CTR, keep holding X for accelerate, swipe occasionally to circle while holding X to use your items without slowing down. I think it's much easier than figuring out the midpoint where two buttons are pressed together.

**Comment by stenzek** [comment]
If you push in the middle of a physical controller, nothing happens. I do not see why a touchscreen is any different.

If you need to push multiple buttons, you can do that with touch gliding. Alternatively, resize/reposition the buttons so they overlap.

Please respect that this is a free app with zero income (no ads) that I develop in my spare time, and my decisions regarding features are final. If you wish to employ me, I'll gladly work on whatever you like, but otherwise it's my spare time so I decide what to do with it :)

**Comment by Vaqtincha** [comment]
@stenzek I think I understood the low ratings in the market. You do not accept criticism at all (it was not even criticism, but an assumption). I didn’t demand anything from you. I was even called a jerk by one non-cultured person to your development team.

**Comment by stenzek** [comment]
I'm fine with criticism or requests. That's why this GitHub tracker exists. But just because you make a request, doesn't mean I must implement it.

And there is no development team, it's just me. A few other people have contributed some minor features, but that's it.

**Comment by stenzek** [comment]
This attitude is honestly very demotivating, and why I've considered removing the android app multiple times. It's not fun or interesting for me anymore, when people have this expectation that they can tell me what I should and shouldn't be doing.

This isn't your typical app arrangement where the developer is getting ad or purchase money from users. I literally get nothing from it, in fact it's cost me several hundred dollars out of my own pocket in costs over the year and a bit it's been running for. If some people get some happiness out of my hobby, that's cool, but otherwise if you don't like it, then there's plenty of alternatives around, and maybe you can pay those developers through ads or the app to implement your ideas.

Look at it from another perspective - everyone has things that they want an app to do. There's 87 open feature requests on GitHub currently. 87 other requests have been implemented. I simply don't have time to implement all of them as a one man team on top my full-time job.

**Comment by Vaqtincha** [comment]
Did I write somewhere that you owe me? This is a small request.
Why release it at all if you can't support it and make it better ?
Yes, you have to close if you do not have the ability to "listen" to "get better"

**Comment by Vaqtincha** [comment]
And who's stopping you from adding donation. Some kind of childish whims of the current developers.

**Comment by PookaMustard** [comment]
>Did I write somewhere that you owe me?

Well, going by your conduct so far, your actions speak louder than words, so yes, you are acting like you are owed.
Can we lock this thread already? I'm tired.

**Comment by foxsevent** [comment]
> And who's stopping you from adding donation. Some kind of childish whims of the current developers.

And what's stopping you from learning programing and contributing to the project?
Stenzek said it multiple he does not hurt for money and doesn't feel like dealing with the whole thing plus then people would be even more demanding since they've "paid" for it, and as stenzek said this is just a hobby.

**Comment by stenzek** [comment]
> Why release it at all if you can't support it and make it better ?

Because some people might enjoy it. But yeah, otherwise, why do I bother.....

> Yes, you have to close if you do not have the ability to "listen" to "get better"

I am listening and discussing? I've explained why I do not think this is a good idea, and given several options you could use instead. Most free app developers don't even respond to questions from users.

It's not a "small" request from an implementation perspective. It would require non-trivial changes to the layout editor, as well as how the button pushes are handled, which already has to consider screen scaling and multiple other factors.

I'm also trying to keep the number of options in the app limited. Too many options and users get overwhelmed and confused, and don't bother reading them. I think that's even happening already.

> And who's stopping you from adding donation. Some kind of childish whims of the current developers.

Because it's not a question of money, it's a time problem. I do not have enough time to implement every feature a user wants, and nobody else is interested in helping me.

Plus as soon as someone "donates" money, then they expect that their requests should get priority.

>  I think I understood the low ratings in the market. 

Average rating of 4.4 is pretty damn good for a free app, all the competition is below 4 and full of ads. And the paid emulators don't get the 1-starring users who can't tell the difference between a BIOS and a game, so of course they're going to be higher on average. Plenty of people seem happy with the app.

**Comment by foxsevent** [comment]
> > Did I write somewhere that you owe me?
> 
> Well, going by your conduct so far, your actions speak louder than words, so yes, you are acting like you are owed.
> Can we lock this thread already? I'm tired.

Seconded please just delete this crap fest and block the dude.

**Comment by Vaqtincha** [comment]
@PookaMustard @foxsevent 
This is wildness. Be polite. Don't forget that you are human.

**Comment by stenzek** [comment]
I'm human too you know? But, such comments are not helpful indeed.

**Comment by Vaqtincha** [comment]
@stenzek No problem, not you. You answered more adequately.

**Comment by foxsevent** [comment]
> I'm human too you know? But, such comments are not helpful indeed.

Apologies that indeed was rude and unneeded, just got up from a night shift and got easily annoyed.


> @stenzek No problem, not you. You answered more adequately.
That he did it was just a bit annoying how first you didn't describe better what you wanted and then proceed to make rude remarks how the "childish" developer doesn't take criticism or should take donations and if he doesn't want to *improve" the products the way you want then maybe he should just close it and pointing out "low" ratings.

We're all humans but you didn't take a moment to realize that this isn't some simple request especially for a single developer.

**Comment by Vaqtincha** [comment]
@foxsevent I am using google translator if you notice it. Or maybe our smart (but rude) man @PookaMustard noticed this. But you have to show respect. It was some kind of racism on the part of @PookaMustard.

**Comment by foxsevent** [comment]
> @foxsevent I am using google translator if you notice it. Or maybe our smart (but rude) man @PookaMustard noticed this. But you have to show respect. It was some kind of racism on the part of @PookaMustard.

Then you should've mentioned so and no I didn't notice because I'm not smart and it's impossible to tell bad English from Google translate broken English.
I'm not a native English speaker myself.
And @PookaMustard wasn't racist, there was nothing said about anyones race in this thread.

Also that title change was just childish at this point.

**Comment by stenzek** [comment]
Sorry, this is getting to personal attack territory and I'm locking the thread. It's just an app, it's not worth getting into an argument over. Let's all try to get along huh?
