### ISSUE TITLE
can't stream duckstation with discord.

### ISSUE THREAD

**Issue by cubabori** [stenzek/duckstation#2072]
when i try to stream duckstation, rather than showing the game, it shows only my game list.

**Comment by andercard0** [comment]
> when i try to stream duckstation, rather than showing the game, it shows only my game list.

First you did not fill out the template so next time you'd like to report something, to do or it could be considered invalid. 

Second, this is already fixed by doing as follows: 

Settings > Display Settings Ticking "use Blit swap Chain" option

![image](https://user-images.githubusercontent.com/43047877/117516217-e6e59100-af6e-11eb-9c4f-604ff2f713a7.png)

So, doing it you shall be able to stream via Discord.

**Comment by cubabori** [comment]
Alright, sorry. And it works, thanks.
