### ISSUE TITLE
EPSXE not responding to dualshock4 aside from the touchpad

### ISSUE THREAD

**Issue by yomycontrolleraintworking** [stenzek/duckstation#2076]
Tony Hawk Pro Skater 2

The game was working fine until tonight when i launched the game, the dpad buttons werent being recognized. I have the overlay showing which gamepad buttons are being pressed and the only button that seems to be recognized is the center touchpad. I have tested the controller using https://gamepad-tester.com/. I have also tested 2 different usb cables and each have worked fine outside of duckstation. I have no other programs running asides from DS4windows, and im using the "sdl" controller backend in settings

I am using an intel celeron N4000 and my OS is Windows10

I am using the latest version of Duckstation

**Comment by yomycontrolleraintworking** [comment]
title is incorrect, ive just switched from EPSXE to duckstation, apologies

**Comment by mirrornoir** [comment]
DualShock 4 work in Duckstation out of the box. Make sure you have disabled Steam's built in controller support for DS4 in the Big Picture controller settings. And I would recommend trying without ds4windows as well just for testing. You do not need ds4windows to use Duckstation.

You should see that DS4 works out of the box with SDL. If you are committed to using ds4windows anyways make sure you have it configure correctly because Xbox controllers that it emulates are supported by SDL out of the box as well. However you can try the xinput controller backend in Duckstation as that is what ds4windows is using natively.

**Comment by stenzek** [comment]
This ^ SDL supports DS4 natively. Don't need to use Ds4windows
