### ISSUE TITLE
Incomplete source code

### ISSUE THREAD

**Issue by sbJFn5r** [stenzek/duckstation#2141]
Hello, you seem to have accidentally uploaded a [portion of the source code in encrypted form](https://github.com/stenzek/duckstation/tree/0474454e0b1e7618f7a51f1158e0c3c30de8281d/src/duckstation-libretro). 
You are distributing [compiled binaries making use of this code](https://github.com/stenzek/duckstation/releases). Your project imports GPL licensed code, so you cannot claim that these binaries are not covered by the GPL.
Please rectify this situation by making the unencrypted source code available.

Thank you.

**Comment by bluestang2006** [comment]
> Hello, you seem to have accidentally uploaded a [portion of the source code in encrypted form](https://github.com/stenzek/duckstation/tree/0474454e0b1e7618f7a51f1158e0c3c30de8281d/src/duckstation-libretro).
> You are distributing [compiled binaries making use of this code](https://github.com/stenzek/duckstation/releases). Your project imports GPL licensed code, so you cannot claim that these binaries are not covered by the GPL.
> Please rectify this situation by making the unencrypted source code available.
> 
> Thank you.

Doesn't look like an accident - https://github.com/stenzek/duckstation#libretro-core

**Comment by stenzek** [comment]
This is completely intentional. It's the only way I can stop a few people from making over $200,000 off my work which I give away for free.

At some point I'll release the libretro sources, but at the moment that part is not GPL licensed. Might remove the source from the tree to stop the confusion, however.

**Comment by stenzek** [comment]
I should also add that the libretro core doesn't link to any libraries where this would be an issue, e.g. Qt. The main emulator is essentially dual licensed now - non commerical for libretro linking, and GPL for the desktop versions. In which case, all GPL linking code is in tree.

It's a real shame that it's come down to this, I don't like it anymore than anyone else. It's actually a complete pain in the arse since I lose proper version history too.

But it's the only way to keep it out of the hands of these malicious actors, who are also using my software in an illegal service, and I must reduce my liability.

**Comment by stenzek** [comment]
The encrypted code has been removed from the repository, and the binaries removed from the release page. Therefore this repository now has no relation to the libretro core. Sorry for the confusion.

**Comment by sbJFn5r** [comment]
You are still using GPL licensed code, like libcue, so moving the binaries doesn't really resolve the situation.

**Comment by stenzek** [comment]
[duckstation-libretro.zip](https://github.com/stenzek/duckstation/files/6512473/duckstation-libretro.zip)

Source code for the libretro portion is here.

Thanks for pointing out the incompatibility with libcue, I'll rewrite it.

**Comment by stenzek** [comment]
Anyway, to close out this issue, if you want to go after an actual GPL violation, I'd suggest looking at piepacker (kivutar's project). They're using duckstation's code in a proprietary service, and are the whole reason behind this mess in the first place. They do **not** have a separate licensing arrangement from me to do so.

None of the changes have been committed upstream. They also claim to be "plug and play", which means they are illegally shipping a BIOS with the service. I do not want my code being used by these people and the potential liability from doing so, but sadly enforcing that is impossible.
