### ISSUE TITLE
Add custom per game folders for texture replacement

### ISSUE THREAD

**Issue by sisco1986** [stenzek/duckstation#2198]
**Is your feature request related to a problem? Please describe.**
we can't change the default custom texture folder and i think is a bad idea to have to move the entire documents folder to a new drive or having to create a symlink just to use the texture replacement feature

**Describe the solution you'd like**
we already have custom configs for each game so i would like if you add a way to choose the path the game uses for the texture replacement option
**Describe alternatives you've considered**
if per game folders can't be done i would like at least the option to move the default texture folder from the documents folder to a place of my choosing

**Comment by stenzek** [comment]
I'm not going to add this in its current form, since I'm in the process of some major refactoring to support general texture replacement (see #texture-workshop on Discord for progress).

The final version of this refactor will be able to load textures from two places; the `textures` directory in the user directory, as well as from the directory that the disc image is located in (for libretro support).
