### ISSUE TITLE
[request] post processing configuration per game

### ISSUE THREAD

**Issue by zerardxxxx** [stenzek/duckstation#2200]
would be nice

**Comment by stenzek** [comment]
No interest in doing this, sorry.

If you continue to ignore the rules about completing the issue template, I will be blocking you from the repository.

**Comment by zerardxxxx** [comment]
> Não tenho interesse em fazer isso, desculpe.
> 
> Se você continuar a ignorar as regras sobre como preencher o modelo de problema, irei bloquear você no repositório.

sorry, my english is limited... not wanting to be inopportune, do you intend to implement control mapping per game? congratulations for the great project, the emulator is very good

**Comment by forz0i** [comment]
Plase add  Upscaling and true colour (24-bit) in hardware renderers to  32
bit ?

**Comment by stenzek** [comment]
Enough with the rediculious requests. I'm not your employee to push around.

32 bit and 24 bit colour usually have 8 bits per channel. The most significant 8 bits contain either nothing, or the alpha channel, neither of which is applicable to the PS1. Duckstation actually uses 32bpp formats because 24bpp formats don't exist on the GPU, but ignores the upper 8 bits (actually uses them for the mask bit)
