### ISSUE TITLE
[Libretro] Memory card is set to "NonPersistent" when it's set to "Libretro .srm" type

### ISSUE THREAD

**Issue by bslenul** [stenzek/duckstation#2339]
**Description of the issue / bug**
With the Libretro version, if you select "Save RAM (libretro .srm)" in the core options the memory card will not be created and the line `duckstation_MemoryCards.CardXType` in the core options file will be set to "NonPersistent".

**Steps to reproduce**
1. Start a game with the Libretro core.
2. `Quick Menu > Options > Memory Card 1 Type > Save RAM (libretro .srm)`.
3. Close content, launch again.
4. You'll be able to save and all but ONLY for that game session, as soon as you'll close content, save will be gone and no .srm will be created (which makes sense considering the "NonPersistent" name :p).

**Hardware/software**
Windows 10 / i5-4670K / GTX 970 / D3D11

**Emulator version**
No idea, latest core from the core updater but it doesn't show the commit version :/ 

**Additional context**
:heart:

**Comment by stenzek** [comment]
NonPersistent is the correct setting, it maps to to the memory data pointer.

It won't apply the type change until the next reboot as a safety measure, because otherwise the current data in the .srm will be lost (e.g. if coming from a different core). After next boot the frontend will populate the data array.

**Comment by stenzek** [comment]
Additional info: it should display a message that the memory card type won't be changed until reboot, and any future saves in that session will apply to the mcd. I'll double check this is working.

**Comment by bslenul** [comment]
Yes, I know you have to close content (step 3. in the reproduction steps :D), but still no .srm file is being created in my retroarch/saves/ folder.

To make 200% sure I quickly beat the first level of Ape Escape, saved my progress (worked fine), close content, restarted Ape Escape, went to "Load" and it says "Empty".

Same if I use my Beetle PSX save, it's not seeing it (proper filename).

**Comment by stenzek** [comment]
Turns out this is a retroarch bug. The problem here is that if a core indicates it supports contentless booting (i.e. booting to the BIOS), SRAM saving will be disabled and can't be used.

So, you can have contentless booting, or save ram, but not both. I'll disable contentless for now, since sram saves are probably more useful... but these silly frontend bugs are starting to annoy me, I don't have the time nor interest in fixing them.

**Comment by bslenul** [comment]
Oh I see, yeah this is a bit strange... But yeah eject disc to enter BIOS is fine IMO.

Thanks for looking at this anyway, it will avoid some confusion! 👍 And sorry about the frustration, I honestly thought it was just an oversight and that "NonPersistent" was incorrect 😓

**Comment by stenzek** [comment]
It probably should be reported as a retroarch bug, but given it was in a TODO/FIXME comment from over a year ago, there's probably no interest in fixing it. Bit of a shame.
