### ISSUE TITLE
Updater pulls x64 files when updating on ARM64 machine

### ISSUE THREAD

**Issue by Gerdya** [stenzek/duckstation#2340]
**Description of the issue / bug**
[Describe what you are seeing and/or hearing during gameplay]
When starting Duckstation yesterday, I got an indication, that a new version is available. I confirmed the update and the update process ran without any obvious issues. However the updater installed x64 specific files.

**Steps to reproduce**
I hope it is reproducable.

**Hardware/software**
Surface Pro X - CPU: SQ1 - 16MByte - GPU: Adreno 680
GPU Renderer: D3D11
OS: Windows 11 (dev/beta)

**Emulator version**
0.1-4315-gf7587 (this is after i installed new from *.zip)

**Additional context**
Duckstation runs exceptionally well with low CPU usage on the Surface Pro X. All features I tried are working. So thanks for supporting ARM64 on Windows!

**Comment by stenzek** [comment]
Whoops. I don't currently have any ARM64 devices so I had no way of checking this, thanks for letting me know.

Should be fixed in https://github.com/stenzek/duckstation/commit/172c522a73369264fa105c26927a15b6a1f2f095, but you'll need to update to the latest build, and then wait for the next update before it queries for the new filename.
