### ISSUE TITLE
crop mode: all borders enabled does not work well in some fmv

### ISSUE THREAD

**Issue by fox140cv** [stenzek/duckstation#2365]
**Game details**
SLES_012.58 Alundra (Spain)
SLES_004.45 Die Hard Trilogy (Europe) (En,Fr,De,Es,It,Sv)
SLES_027.50 Die Hard Trilogy 2 Viva Las Vegas (Spain)
SLES_019.06 Mission - Impossible (Europe) (En,Fr,De,Es,It)
SLES_015.14 Silent Hill (Europe) (En,Fr,De,Es,It)

**Description of the issue / bug**
In most games the option 'crop mode All Borders' the FMVs are correctly seen except in these:
In the case of Alundra the intro is seen at the top instead of centered.
In the rest, the FMV are stretched as seen in the mission impossible image.
With the default option 'only overscan area' it is solved in the FMV but in the game the image is cropped.
Tested with vulkan d3d11 and opengl 

**Enhancements information**
Crop mode: All borders

**Hardware/software**
CPU intel i5 6600k
Nvidia gtx 1060
windows 10 x64

**Emulator version**
0.1-4401-g0c4629bd

![alundra 1](https://user-images.githubusercontent.com/79443698/124403400-8be5d580-dd36-11eb-92b3-3261449566da.jpg)
![alundra 2](https://user-images.githubusercontent.com/79443698/124403402-8c7e6c00-dd36-11eb-87a8-4e71bd559c71.jpg)
![mision 1](https://user-images.githubusercontent.com/79443698/124403403-8c7e6c00-dd36-11eb-82d8-6f79f33f13ba.jpg)
![mision 2](https://user-images.githubusercontent.com/79443698/124403404-8d170280-dd36-11eb-9b4b-6ceed2467200.jpg)

**Comment by foxsevent** [comment]
![Bez tytułu](https://user-images.githubusercontent.com/64225743/124403759-314d7900-dd38-11eb-9cd3-7946e13893eb.png)

**Comment by stenzek** [comment]
Not a bug. This option is not guaranteed to give the correct AR as the description says.

**Comment by daFourch** [comment]
I'm unearthing this post because I'm running into this kind of questioning at the moment. How is Crop Mode supposed to behave, exactly? Is it supposed to hide native psx pillar boxes by stretching the picture horizontally?

Here is Alundra NTSC with Crop Mode respectively on None, Only Overscan and All Borders:
![Alundra (USA)-211103-232117](https://user-images.githubusercontent.com/72701886/140204041-05d89dad-6323-407a-9487-fa2a1d7a7050.png)

![Alundra (USA)-211103-232151](https://user-images.githubusercontent.com/72701886/140204105-2dcbc04f-5998-417f-903f-f5d2f9c727a6.png)

![Alundra (USA)-211103-232135](https://user-images.githubusercontent.com/72701886/140204176-c8051172-2ce5-4240-b036-19b95947fd79.png)

As we can see, "None" displays pillar boxes. "Only Overscan" kind of stretches the picture proprotionally until pillar boxes disappear. The thing is the aspect ratio is not 4:3 and we can see some visible areas at top and bottom are "missing". "All borders" stretches picture horizontally until pillar boxes disappear. It seems to be the proper way to display the game, with 4:3 ratio and all drawings displayed.

Same goes for Crash Bandicoot NTSC:

Here's with Only Overscan: 
![Crash Bandicoot (USA)-211103-233144](https://user-images.githubusercontent.com/72701886/140209887-895f9915-09b8-4253-948b-0daf60548ee7.png)

Here's with All Borders:
![Crash Bandicoot (USA)-211103-233131](https://user-images.githubusercontent.com/72701886/140209917-e8af1bc2-cad1-445e-b09a-e3171fe36615.png)

I can confirm that on CRT, there are black little bars on top and bottom of the screen, because internal game resolution is 512x240, so kind of "wide". We can also clearly see that crates are more "cubic" when using "All Borders".

So I Assume "All borders" is more accurate, but indeed behaves weird with some FMV, as stated in OP.

Thanks for your time and answers.
