### ISSUE TITLE
Main menu of Power Dolls 2 - Detachment of Limited Line Service (Japan) runs at over 1500 FPS

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#237]
![Capture](https://user-images.githubusercontent.com/31968468/78543314-d890e700-783b-11ea-9642-2237ece2fa00.PNG)

**Comment by stenzek** [comment]
Please re-test on latest build. It'll likely still be above 60 if the game is running uncapped, but the console internally is probably running above 60 too, you just can't tell.

It's only an issue if say, it switches to the attract mode too quickly.

**Comment by kurayami6** [comment]
It now runs at just over 300 FPS. 

![Capture](https://user-images.githubusercontent.com/31968468/79685557-0420c200-827d-11ea-8d0f-012eb30779c5.PNG)

**Comment by stenzek** [comment]
Are there any issues? Does input not work? If there are no issues, like I said running at 300fps internally is not a problem.

**Comment by kurayami6** [comment]
Alright I'll close this.

**Comment by stenzek** [comment]
My point was that unless something is broken, it's likely the same as on the console, you just can't see the frame rate there. The GPU timings are still approximate and most of the time faster than the console, but it shouldn't be 5-10x slower which is what would be needed for this to render at 60fps. (I know they're not 10x slower because when I make them 10x slower, things break horribly).
