### ISSUE TITLE
[Libretro] Always reports 320x240 resolution (geometry)

### ISSUE THREAD

**Issue by Jamirus238** [stenzek/duckstation#2382]
Reported this back in February over at Swanstation:
https://github.com/libretro/swanstation/issues/12

The core appeared to always assume a 320x240 resolution, resulting in scaling issues,
it was fixed with
https://github.com/libretro/swanstation/pull/16

**Comment by stenzek** [comment]
This is intentional. Otherwise with a larger internal resolution the window is too large to fit on the screen.

**Comment by Redemp** [comment]
So basically this makes the core completely useless with Switchres in RA. Has to be a way to solve this?

**Comment by stenzek** [comment]
I've never used it. But if someone can suggest a solution which doesn't involve making the window too large when you use high internal resolution I'm happy to implement it.

**Comment by dankcushions** [comment]
perhaps if it always reported the 1x resolution (regardless of whether 2x, etc were selected)? i imagine the use case for things like crt-switchres is always 1x resolution anyway, because they want to get natural scanlines, etc.

(that said, personally i don't think it's an issue with high res = big internal windows - that's how all libretro cores operate AFAIK - seems like maybe a front end issue where it should downsample to a reasonable window size, when in windowed mode)
