### ISSUE TITLE
Wild Arms 2: Corrupted character sprite when walking into a forest on the overworld map

### ISSUE THREAD

**Issue by Petsura** [stenzek/duckstation#2600]
SCUS-94484 - Wild Arms 2 (USA)

Basically what the title says.
When you walk into a forest on the overworld map, your character turns into literal mush.
This only seems to happen if you increase the internal resolution of the game, so playing it on the Software Renderer or with all Enhancements disabled fixes the problem to the detriment of all the QoL improvements.

CPU - 3770k
Graphics card - GTX1070
GPU Renderer - D3D11/D3D12/OpenGL/Vulkan 

Emulation Version - 0.1-4714-g6c628bb8 (dev)

I also noticed that this problem occurs when Lilka uses her teleportation magic during a cutscene at the end of her prologue (reoccurring issue).
It happens on all renderers except for the Software Renderer for obvious reasons.

Screenshots:
Internal resolution set to 1 (PGXP on)
![WA2_01](https://user-images.githubusercontent.com/90411087/132732940-04567507-7f85-4c80-b22c-25a385b43b8d.jpg)
Internal resolution set to 2 (PGXP on, disabling it does nothing to fix the sprite)
![WA2_02](https://user-images.githubusercontent.com/90411087/132732987-138984ad-70c2-4b2a-ad4a-7c827fcf982b.jpg)
Software Renderer or Internal resolution set to 1 (PGXP off)
![WA2_03](https://user-images.githubusercontent.com/90411087/132734749-2d55d058-8612-453a-bd39-df04b61009f7.jpg)

**Comment by andercard0** [comment]
Not sure if this is really relevant but as you @stenzek can see here : 

Legend of Dragoon (texture correction) ON same behaviour.  Which --in this case. at some parts of the game will make chests dissapear completely.
![image](https://user-images.githubusercontent.com/43047877/132737229-bcfe071c-52a0-4ed0-b783-9051b66fc4c4.png)

Not sure if it is a reall issue so to speak, because it is a eEnhancement. but I think it's relevant to reinforce.

**Comment by stenzek** [comment]
There's an enhancement issues megathread. But otherwise enhancements aren't guaranteed to work with all games.
