### ISSUE TITLE
'Zoom to Fit' video option

### ISSUE THREAD

**Issue by theraineydaze** [stenzek/duckstation#2608]
**Is your feature request related to a problem? Please describe.**
When trying out Riven I realized there's no video option for a 'Zoom to Fit' which would make the presentation alot better, it would crop out the black bars without distorting the image. But as of now there is no way to do this

**Describe the solution you'd like**
An option to keep the aspect ratio but resize the image to fit the width of the display, or even an option to do this in an ini file or something since I know this doesn't have a lot of applications outside of Myst/Riven.

**Describe alternatives you've considered**
I haven't found this option in other PSX emulators and I'm not using the PC version because I'm experimenting with texture replacements, not sure what alternatives I could do for this.

Here's an example of 'Zoom to Fit' I'm talking about. 

![cat_people_zoomed-683x1024](https://user-images.githubusercontent.com/30421001/133158768-1ddefd5e-63b6-4bd7-9eae-e23838d91abf.jpg)

**Comment by Awakened0** [comment]
You can do this manually per game by right clicking a game in the list, going to Properties, then the the Compatibility tab and messing with the Display Line Offset values. Increasing the first one crops from the top, while decreasing the second (put a - in front of it) crops from the bottom. You'll have to figure out what numbers to use for each game. Here's an example of Crash 1 set to 40, -40:

![example](https://user-images.githubusercontent.com/4565863/133165512-2680e0a9-ce02-4da0-99c9-3d6ce2a4b37c.png)

**Comment by stenzek** [comment]
There's already a stretch to fit option as well as line cropping.

**Comment by Defreezer** [comment]
> You can do this manually per game by right clicking a game in the list, going to Properties, then the the Compatibility tab and messing with the Display Line Offset values.
Line cropping stretches the image's height even when used with integer scaling, and causes warping in 2D sprites/games. The requester is probably looking for a feature similar to [#2588](https://github.com/stenzek/duckstation/issues/2588).

**Comment by Awakened0** [comment]
> Line cropping stretches the image's height even when used with integer scaling, thus warping the image.

I thought aspect ratio was maintained when using line cropping? It looks like it's zoomed rather than stretched in my screenshot.

**Comment by Defreezer** [comment]
> I thought aspect ratio was maintained when using line cropping? It looks like it's zoomed rather than stretched in my screenshot.

The following screenshots were taken at a 4:3 aspect ratio with cropping set to overscan area (generally the closest combination to a 4:3 TV[*](https://www.neogaf.com/threads/the-ps1-games-and-the-question-of-the-aspect-ratio.1599974/)), disabled downsampling, disabled widescreen hack, 1x internal resolution at fullscreen on a 1080p monitor:

1 - Integer upscaling enabled;
2 - Integer upscaling disabled (zoom to fill);
3 - Integer upscaling enabled + display line offset of 8 lines (4 top and -4 bottom, the minimal amount necessary for the integer upscaling function to fill the screen vertically).

![1 - integer scaling](https://user-images.githubusercontent.com/79490923/133365050-b0f301f5-973c-4c5e-b59b-1292572bc744.png)
![2 - No integer scaling](https://user-images.githubusercontent.com/79490923/133365055-4b0d5514-688f-4b52-8005-9c1555b00d89.png)
![3 - integer scaling with crop](https://user-images.githubusercontent.com/79490923/133365060-43b535ab-cd02-4498-bfc9-5fe90db1a197.png)

When layering picture #3 over picture #1 and resizing the former to match the latter's height or width, it appears that the line cropping function stretches the height instead of multiplying the native resolution while keeping the correct aspect ratio.  The warping is especially noticeable in 2D games.

**Comment by Awakened0** [comment]
> The following screenshots were taken at a 4:3 aspect ratio

That ratio doesn't automatically adjust to line cropping settings. Auto (Game Native) and PAR 1:1 should. I think 4:3, 16:9, ect. don't because they're just static aspect settings.

**Comment by Defreezer** [comment]
> That ratio doesn't automatically adjust to line cropping settings.

If that's the case, an option that permits enables it to render integers beyond the resolution limit instead of constraining it (along with X/Y position offset options) would be a welcome addition to the display options if it can be done.

**Comment by TheRealYasri** [comment]
It seems retroarch supports this now. Its under config>video>scaling. It works with the duckstation core. It was  added with the 1.9.7 release. Be nice if duckstation would support this standalone, but I do not think he will, since he closes tickets instantly.

![Capture](https://user-images.githubusercontent.com/20503367/134941303-0139b6e1-d2c6-4ca2-b5f2-254fc388f53b.PNG)
