### ISSUE TITLE
Checking with PVS-Studio static analyser

### ISSUE THREAD

**Issue by Stolyarrrov** [stenzek/duckstation#2716]
To demonstrate the capabilities of our analyzer, we regularly perform analysis of open source projects. We had recently checked the DuckStation project.

- Here is the [link](https://pvs-studio.com/en/blog/posts/cpp/0881/) to the article about it (we check [13c5ee8](https://github.com/stenzek/duckstation/tree/13c5ee8bfb4f0f8fc40f76b39de58b5d9b473dc3) version)
- Open Source projects [can use](https://pvs-studio.com/en/blog/posts/0614/ ) PVS-Studio as free

**Comment by andercard0** [comment]
> 
> 
> To demonstrate the capabilities of our analyzer, we regularly perform analysis of open source projects. We had recently checked the DuckStation project.
> 
>     * Here is the [link](https://pvs-studio.com/en/blog/posts/cpp/0881/) to the article about it (we check [13c5ee8](https://github.com/stenzek/duckstation/tree/13c5ee8bfb4f0f8fc40f76b39de58b5d9b473dc3) version)
> 
>     * Open Source projects [can use](https://pvs-studio.com/en/blog/posts/0614/%C2%A0) PVS-Studio as free

Invalid! this is not a issue, this is not a report why are you raising this anyway ? so please do close this before you get blocked!

**Comment by liljotik** [comment]
I like the idea. Don't give up.

**Comment by stenzek** [comment]
Thanks for the info, I'll get around to addressing them soon :) to be honest I'm a little surprised that there's no issues in the emu core itself. I actually turned off VS's background static analysis due to false positives.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/e6741dad9b4c5dc7f6871939e314f4ef54fba8a3, https://github.com/stenzek/duckstation/commit/fca4a2ec28132da2869cd87dc1c9782d275fed55, https://github.com/stenzek/duckstation/commit/a2223124ad1cc4869fc25a362b6c2e94a7965334, https://github.com/stenzek/duckstation/commit/a8ca5446487cd9dbf0812b489e71862ca5f27be7, https://github.com/stenzek/duckstation/commit/c54c5f1b95413657418627ab9195ea7be3b52bf7

The Qt one was interesting - I didn't realize that it was inverting the comparison result internally when sorting descending. But makes sense, and a good catch from the analyser.

For what it's worth, N10 was deliberately written this way so it would fall back to the later backends if the earlier ones failed to initialize. But in the current setup, those `Create()` methods just return a new instance unconditionally (which the analyzer was detecting cross-compilation-unit?).
