### ISSUE TITLE
PlayStation 2 Emulation

### ISSUE THREAD

**Issue by SpaceAgeHero** [stenzek/duckstation#2720]
Up to this date there is no consistent, performant & portable PS2 emulator.
Do you think you'd be up to the task?
You've achieved this with PS1 / DuckStation.
Perhaps we can initiate crowdfunding if you require monetary support.

**Comment by stenzek** [comment]
Wrong.

https://github.com/PCSX2/pcsx2/

**Comment by liljotik** [comment]
I don't get it. He asked for a consistent, performant & portable PS2 emulator. Why did you link pcsx2?

**Comment by stenzek** [comment]
Because pcsx2 is consistent, performant and cross-platform?

So you're asking me for something which I am actually working on, on one hand, but on the other hand, saying it sucks?

:thonk:

**Comment by liljotik** [comment]
Not your fault it sucks and maybe you can make it suck less. But it absolutely does suck. I tried Onimusha: Dawn of Dreams about a year ago. Had to screw around with settings for half an hour to try and make the blur look correct and half of them just crashed the emulator completely. Then it turned out the shop menu is corrupted with no fix which made the game unplayable. I was so angry after this whole experience I just gave up on PS2 emulation.
