### ISSUE TITLE
Asuncia locks after starting new game

### ISSUE THREAD

**Issue by bajolzas** [stenzek/duckstation#298]
The game locks right after trying to start a new game (and I guess loading a save too).
I am using the translated version but it should happen on the original japanese version as well.
The log is firing this message over and over again:
W(CDROM::DoSectorRead): Skipping sector 2360 as it is a data sector and we're not reading

**Comment by kurayami6** [comment]
The unpatched version works fine. This is what happens when people develop patches to work on inaccurate emulators instead of real hardware. As emulation improves the patched break. It probably works on hacked together dogshit like ePSXe or something. 

![SLPS-01097_2020-04-16_13-25-18](https://user-images.githubusercontent.com/31968468/79411384-159c6c80-7fe6-11ea-8fcc-7ffadbcc4140.png)

**Comment by bajolzas** [comment]
Hm, guess I had a bad dump, its working now, wierd because it was even working on beetle.
