### ISSUE TITLE
[Request] Add filename column

### ISSUE THREAD

**Issue by cascardian** [stenzek/duckstation#30]
_Having a redump-based automatic scanner is great. However, it doesn't work for romhacks. This is also an issue with RetroArch's content scanner, especially when it comes to matching manually added content with boxart/screenshot thumbnails (which might be one of those nice-to-haves later on for DuckStation as well).

In cases of an extension match (.cue/.bin, .chd, and so on), the scanner should use the file name to determine the game's name and region. Region could be determined with the usual (U), (E)/(EU), (J) or (USA), (Europe), (Japan) in the file name. I personally use Cowering's old country code scheme for its shortness when dealing with romhacked games, but either or both would work for most people, I guess.

Of course, you could also just use the file name as is to display romhacks and disable automatic region detection in those cases and use a pre-determined setting._

Edit: This is inaccurate as per the content scanner's function. See below. This issue is now about adding a filename column to the list.

**Comment by stenzek** [comment]
The game ID is pulled executable name defined in the `SYSTEM.CNF` file on the disc. I'm assuming romhacks don't change the executable name, so yeah, they'll pick up the original game's name from the database.

If the game doesn't exist in the database, or the database isn't present, it pulls the region from the system area of the disc: https://github.com/stenzek/duckstation/blob/master/src/core/game_list.cpp#L152 This should be pretty accurate unless a romhack deliberately modifies this string. So, I'm not sure if string matching is needed to detect the region. I guess the only caveat to this might be translations, but unless the game code is modified it's going to expect the original region's BIOS anyway.

I'm not really sure on the best way to handle romhacks in this regard, unless there's a simple way of flagging modified disc images. Checking the hashes won't work, since there's multiple formats which could produce a different hash, but not necessarily a bad dump. So, having a global enable/disable for the database might work better. For what it's worth, if the database isn't present, it just uses the image's filename as the title.

**Comment by cascardian** [comment]
Hm, looking this over now and double-checking, I think this is actually an invalid issue in how I describe it. I apologise. The content scanner actually does recognise all discs I could find.

Though having that global database enable/disable option is indeed helpful for those with meticulous filenames. I think it's a great workaround that should satisfy most people's needs. You can close issue upon its addition.

**Comment by stenzek** [comment]
Latest master adds column toggling to the game list, as well as a hidden-by-default column "File Title". The file title column is generated from the filename. Do you think this is sufficient for a enable/disable option?

**Comment by cascardian** [comment]
Works great. Thank you. I believe that should satisfy most people's needs. If anyone else has another idea related to this, they should probably open a new issue. I consider this solved.
