### ISSUE TITLE
Texture is misaligned in RayCrisis - Series Termination (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#314]
See how the word "Connect" is all messed up? Possibly the same issue as the box textures in Crash Bandicoot. 

![SLUS-01217_2020-04-21_06-36-13](https://user-images.githubusercontent.com/31968468/79801735-003a9000-83a2-11ea-8bf9-d667e063dc3a.png)

**Comment by stenzek** [comment]
Did the Crash Bandicoot fix (https://github.com/stenzek/duckstation/commit/98ff136f67bcf6d21bf70663e93c55e53d3853ce) affect this at all?

**Comment by kurayami6** [comment]
I just checked and it's still misaligned even in software mode.

**Comment by stenzek** [comment]
That's not surprising.

To be honest I suspect this is just the way the game is. It looks like just a plain old rectangle/sprite, not a 3D object where differences in interpolation and texture coordinate scaling could become an issue.

If you can run it on console yourself, or find footage where it is not broken and show otherwise I'm happy to investigate more, but for now I'm considering this invalid. Alternatively, check VRAM and see if the letters are skewed there as well. If so, then it's definitely not a rendering bug.
