### ISSUE TITLE
The ability to transfer save states between versions

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#317]
That way if and when I encounter a bug 20 hours into a game I can just save state right there and immediately check it in a newer version of the emulator instead of having to play all the way back to where I was. 

![Capture](https://user-images.githubusercontent.com/31968468/79902827-79df8600-8455-11ea-89a8-dbe23e38e06b.PNG)

**Comment by stenzek** [comment]
This is not something which can be done. I don't bump the save state version with every change, only when it is necessary, usually because some variable has been added. How can you "transfer" the value of a variable when it did not exist in the old build?

I'd suggest keeping a copy of the older build around, so that when you do run into this, you can fire up the old build, save your game to memory card, and then reload and create a save state on the new build.
