### ISSUE TITLE
BIOS music is wrong in Disney's Hercules (USA) as of the latest version

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#342]
It sounds slightly distorted and crackles at the end. Last time this happened it was caused by some broken Beetle PSX code but the problem was fixed when it was removed. Was that code added back in at some point?

**Comment by kurayami6** [comment]
Yeah just checked Tarzan and the same problem is back. BIOS is distorted and crackles horribly.

**Comment by stenzek** [comment]
Probably because I reduced the delay for the CD-ROM changing speeds as it was causing issues for other games in CDDA.

As with the Tarzan issue, given this happens on every other emulator out there, I'm considering it invalid until I hear a console recording which proves otherwise.

**Comment by kurayami6** [comment]
You're not understanding me. Tarzan has two unrelated issues. One is that the BIOS sounds continue well into the game itself. The other, which is the one I'm talking about, is definitely a regression. The BIOS sound is wrong and crackles. This didn't used to happen.

**Comment by stenzek** [comment]
Is it just this game? I compared the BIOS startup sound to my console and the new reverb implementation sounds more correct. It also fixed the clipping in FF7.

**Comment by kurayami6** [comment]
No it isn't just one game. As I said in the name of the issue, I found it was broken while playing Hercules. It sounded broken in the exact same way that happened when you added reverb code from Beetle so on a hunch I checked Tarzan and sure enough it was broken as well, just like last time.

**Comment by stenzek** [comment]
The first time I ported the reverb code from Mednafen I omitted a couple of things and the memory addressing was incorrect. That shouldn't be a problem now.

The problem with these games is they don't clear out the reverb RAM or move the pointer to the end of RAM, but leave writes disabled. This results in the echo from the BIOS repeating, and never being overwritten with the silence/new sound.

Before the latest changes the CD-ROM took longer to read the game's executable into RAM, so the reverb was still there, it just had more time to "fade out" before writes were disabled and the game started. So it was never "fixed", and you could hear it if you turned the volume up high.

So, either this issue happens on console and it's just less noticeable because of the longer boot times, or something is missing entirely. Hence why I would like to compare it to a recording from a console, because I haven't found anything which is missing.

As an interim fix, use fast boot.

**Comment by kurayami6** [comment]
Instead of arguing with me why don't you just play Tarzan in the latest version and see if it sounds correct?

**Comment by stenzek** [comment]
Because I don't have it, so I can't run it on my console.

**Comment by kurayami6** [comment]
You can't find a ISO of the game to try in the emulator?

**Comment by stenzek** [comment]
I'm not concerned about how the emulator behaves until I know it is definitely a bug.

I already investigated and found why you're hearing the echo after the game starts (see the explanation above). As far as I know nothing is missing in the emulator which would cause this, so like I said either something is missing (and also missing in every other emulator, as they all have this issue), or it's an oversight by the developers and just less noticeable on the real console due to longer boot times.

**Comment by kurayami6** [comment]
Alright I've said this several times and this is the last time I'll say it. I am not talking about the BIOS echoing. I am talking about a completely unrelated regression that was introduced at some point in the last few days that causes the sound on the BIOS screen to be distorted and crackly. It does not happen on real hardware nor did it happen in older versions of the emulator.

**Comment by stenzek** [comment]
Based on the title I assumed it only happened in these games.

I am unable to hear any crackling in the BIOS intro sound, and there's no clipping in the waveform. I can check again, but I did this last night before pushing the changes. I also checked that it sounded correct with some users on Discord.

I'm not saying it doesn't happen, just that I can't reproduce it. Can you make a recording with the "Dump Audio" feature and attach it?

**Comment by kurayami6** [comment]
How should I post it? Github isn't letting me post 7-Zip files.

**Comment by stenzek** [comment]
Compress it as a zip instead.

**Comment by kurayami6** [comment]
Tarzan

[SLUS-01029_2020-04-26_00-12-14.zip](https://github.com/stenzek/duckstation/files/4533123/SLUS-01029_2020-04-26_00-12-14.zip)

Hercules

[SLUS-01537_2020-04-26_00-02-39.zip](https://github.com/stenzek/duckstation/files/4533124/SLUS-01537_2020-04-26_00-02-39.zip)

**Comment by stenzek** [comment]
Pretty sure this is still the reverb issue which causes the echo to continue. It happens right after the BIOS hands control over to the game.

**Comment by kurayami6** [comment]
Well in any case the echo has always been there but the crackling didn't used to be.

**Comment by stenzek** [comment]
Probably just a side-effect of the differences in the reverb algorithm (probably because the old one saturated at every step). Delaying the CD-ROM again so the boot takes longer would probably "fix" it, but that's not the correct fix.

I probably won't spend any more time looking into it until someone can confirm on console that there is no echo at all once the game starts. Because there may not be any SPU issue at all, and it's just due to the faster booting,
