### ISSUE TITLE
Broken graphics around the edge of the screen in Pink Panther - Pinkadelic Pursuit (USA) using OpenGL and D3D11

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#352]
OpenGL and D3D11. Happens at all resolutions and with all crop modes.

![Capture2](https://user-images.githubusercontent.com/31968468/80322567-61160c80-8869-11ea-9e98-6cbf3210d81f.PNG)

Software

![Capture](https://user-images.githubusercontent.com/31968468/80322572-683d1a80-8869-11ea-9083-3a017539df79.PNG)

**Comment by stenzek** [comment]
Does this occur if you disable linear upscaling/filtering?

**Comment by kurayami6** [comment]
Yes

**Comment by stenzek** [comment]
Could you please upload a screenshot with "Show VRAM" enabled? I'm trying to work out if this is a display issue or if it's not rendering in the correct area of the screen.

**Comment by stenzek** [comment]
Okay, this doesn't happen at 1x as far as I can tell. Not sure if you're doing this or not, but when testing this stuff could you please reset the console inbetween changing settings, rather than changing the resolution on the fly. Sometimes bugs can persist otherwise, particularly stuff which affects VRAM.

**Comment by stenzek** [comment]
Merged with #427.
