### ISSUE TITLE
Ronaldo V-Football (Europe) hangs on the first screen

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#395]
![SLES-02681_2020-05-05_16-10-57](https://user-images.githubusercontent.com/31968468/81038964-0aed3d00-8eeb-11ea-88e7-e9c94df76642.png)

**Comment by stenzek** [comment]
I think this is another case of a libcrypt game and you not having the SBI file. That, or a bad dump. Once you have checked that, if the issue is still occurring I will look into it. In the future, particularly for European games, it's worth checking for libcrypt if things are broken.

![image](https://user-images.githubusercontent.com/11288319/81704572-51293a00-94b1-11ea-995a-694d52675925.png)
(data courtesy of redump.org)

**Comment by kurayami6** [comment]
Yeah you were right.
