### ISSUE TITLE
[Feature Request] Texture Upscaling

### ISSUE THREAD

**Issue by insaneninja117** [stenzek/duckstation#400]
Hi Stenzek,

Given that DuckStation can render out ridiculously high resolutions making geometry appear very sharp, it would be nice if there was an option to toggle texture upscaling in the enhancement menu as well, preferably something along the lines of xBRZ. If this doesn't fit within your outlook of what DuckStation should do (as a "hacky" option that reduces accuracy) or can't be implimented within the current framework than thats fine. However as it is something other emulators offer it would be nice to have this as yet another reason to stick to/move to DuckStation.

Thanks in advance

**Comment by stenzek** [comment]
I like the idea, if it can be implemented purely in fragment shaders.

Custom textures are on a bit of a standstill at the moment - I do have a branch with texture dumping, but the number of files it produces is in the thousands for some games because of different palette combinations. I'd need to find a way around that.

But, if it can be done in a fragment shader as part of the normal rendering process, then it should be doable. I'd just have to find a way around the edge sampling issues which is what causes bilinear texture filtering to break in some games currently, because otherwise it will have the same problem.

**Comment by insaneninja117** [comment]
Yes, in Crash Bandicoot the bilinear filtering does leave weird edges on the UI textures for example.

It appears as though there are xBRZ and other scaling filters written in HLSL in the libretro repository; if there are no licensing issues then perhaps that is a good starting point. I would be happy to test the results if you ever get round to this.

**Comment by heckez-sys** [comment]
@insaneninja117 yes i love the xbrz like stuff(mesen) and with texture upscaling would make it look like cs:go fortrnite etc.

**Comment by MojoJojoDojo** [comment]
PPSSPP already does something like that I think and you can even upscale up to a factor of 5 there.
It works best with Vulkan for some reason though.

**Comment by DonelBueno** [comment]
This request is already implemented. This can be closed, no?

**Comment by stenzek** [comment]
Realtime texture upscaling can be achieved with xbr filtering, texture replacement is tracked in https://github.com/stenzek/duckstation/issues/2
