### ISSUE TITLE
Driver is invisible in Championship Motocross 2001 featuring Ricky Carmichael

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#43]
![Capture](https://user-images.githubusercontent.com/31968468/75827159-2362ad80-5dfd-11ea-9a8f-b3289696df3b.PNG)

**Comment by stenzek** [comment]
That's an.. amusing one

**Comment by stenzek** [comment]
Please re-test on latest build.

**Comment by HeroponRikiBestest** [comment]
Works perfectly now.

**Comment by stenzek** [comment]
Thanks for checking! :)

**Comment by BloodRaynare** [comment]
Request for reopen this again, since the bug still happening even on latest dev build (0d28153), so definitely some regression happened (IIRC last time it work flawlessly was on build from somewhere between Oct-Nov 2020 I didn't remember much). And I already disabled the enhancements.

![SLUS-01230_2021-01-02_07-16-05](https://user-images.githubusercontent.com/46045141/103448375-687c9800-4ccb-11eb-9d25-eacfe6a4b158.png)

**Comment by stenzek** [comment]
I have a fix for it, just need to make sure it doesn't cause regressions.

**Comment by stenzek** [comment]
Fixed again in https://github.com/stenzek/duckstation/commit/0de34d7bf770f06726524ca1c406acb52795c210 (preview build).
