### ISSUE TITLE
Can anything be done to reduce input lag?

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#445]
Sorry if it's a silly question but I've found games like the World Stadium series to be nigh unplayable as a result of how long it takes inputs to register.

**Comment by stenzek** [comment]
Host controllers are polled at the beginning of a frame. Frame ends at guest vblank, just before the game polls controllers in the vblank irq handler. So that's about as little time difference as you can get without running ahead or other tricks.

Other people have actually commented on the input lag and found it to be better then alternatives. If it's really bad for you, it might be your controller or OS at fault (e.g. the compositor adding extra latency for display. MS didn't do well there until Win10). That or it just doesn't work well with SDL.

**Comment by kurayami6** [comment]
That's a good enough explanation for me. Thanks.
