### ISSUE TITLE
[QUESTION] LightRec as dynamic recompiler?

### ISSUE THREAD

**Issue by RaydenX93** [stenzek/duckstation#5]
Hello,
Firstly, it's nice to see a new psx emulator around and your work seems really promising!

Secondly, I am not an expert in the subject but in the updated readme you wrote that you're working on a CPU recompiler. If you never heard about this, I believe you could have a look at this dynarec that is currently being developed and integrated into beetle-psx and pcsx-rearmed for the libretro platform.

https://github.com/pcercuei/lightrec
https://github.com/libretro/beetle-psx-libretro/issues/214

Hopefully, this could be useful for you as well ;)

Keep it up!

**Comment by stenzek** [comment]
Not really useful - already made decent progress with my own recompiler design, but thanks for the link anyway.

**Comment by pcercuei** [comment]
It's really easy to plug, very compatible and support many more archs. You could have it as an optional fallback :)

**Comment by stenzek** [comment]
Are there any performance numbers released? My recompiler already targets the main two architectures which are relevant today (x86_64 and AArch64), and can get up to 4x speed improvement (more with fastmem) vs the interpreter. If lightrec can't reach these numbers, it's probably not worthwhile considering.

**Comment by pcercuei** [comment]
In pcsx4all, if I disable the frame limiter, in the opening credits scene in FF7 I get ~265 fps. With Lightrec enabled it runs at about ~1000fps. So that's also about 4x speed vs. the interpreter for full system emulation.

**Comment by stenzek** [comment]
@pcercuei Hmm, interesting. Assuming fps = vblanks per second, I'm getting approx. 1100fps in the JIT without fastmem, and varying between 1600-1800fps with fastmem. The interpreter runs around 240fps. This is on a Ryzen 3900X. I haven't merged the fastmem code yet because it doesn't properly generate address error exceptions, not that this matters for any of the games I've tested, but I'd rather emulate it properly across all modes and I haven't thought of a performant way to do so yet.

Performance seems pretty similar then, although probably worth considering I haven't spent much time optimizing the other components in the system yet. If nothing else, it's an interesting comparison!

I'm not doing any intra-block optimizations yet. Inter-block is just simple linking to save the cache lookup, but this is done in C++ code and not directly in the generated code. Something for the future. No doubt we could probably share some optimization ideas :)

**Comment by pcercuei** [comment]
i5-3230M here, which is what you would call a potato :)

Do you have a IRC channel for duckstation?

**Comment by stenzek** [comment]
I don't have any IRC/Discord/etc channels as I'm not sure if there is enough interest yet to create one. Looks like you found me on freenode, I'm in the Dolphin channels there, and we also have a PlayStation channel in the emudev Discord which is pretty active.
