### ISSUE TITLE
Support ECM disc images

### ISSUE THREAD

**Issue by DarkFrost89** [stenzek/duckstation#509]
ı have a idea,duckstation emulator support play ecm compressed files ?
ı found Neill Corlett's ECM files in achive.org 
https://archive.org/details/ErrorCodeModelerEncodeDecodeUtilities_Version_1.0 
and ecm software under GPL licance
Can You İmplament This Files Duckstation Emulator ?

**Comment by heckez-sys** [comment]
what if u code it your self?(not trying to be rude)

**Comment by TzakShrike** [comment]
Has anyone done any sort of comparison of ECM vs CHD for PSX, comprehensive or otherwise? I can't find anything mentioning them both.

**Comment by stenzek** [comment]
My expectation would be that CHD generally compresses better, since the small amount of data you save by removing ECC would be outweighed by the compression of the actual sector data. But of course this may not apply to **all** games.

@Zet-sensei might be able to give an answer on what the "standard" is for archival now. I was under the impression things were moving over to CHD.

**Comment by Zet-sensei** [comment]
The "standard" for archival remains the multi-tracks format, majorly inside preservation groups and between researchers.

But I'm not against the idea of "1 file == 1 disc" personally.

For the general public, it could be easier to use on their solutions as long as the tools are maintained/maintainable & the licences permit to do so.

On the usage for the SONY PlayStation disc images, I don't have any kind of veto to use a CHDv5 format at all, as we never had any problem on the whole set (as of February 2020).

The ECM format isn't maintained anymore since at least 10 years, so I leave to the emudevs the choice to implement it (or not).

**Comment by tony971** [comment]
If there were any format that I would consider above CHDv5, it would be [Aaru Image Format](https://github.com/aaru-dps/Aaru/)

**Comment by Vaporeon** [comment]
ECM is not really compression but rather the removal of data that can be perfectly recalculated. This aids in compression ratio when using a proper compression format, but it makes no sense to use it by itself.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/ac4dd11fa0b711718d0d4b1bafc2be29b75ecbf7
