### ISSUE TITLE
Rayman (NTSC-J) plays music out of order

### ISSUE THREAD

**Issue by MojoJojoDojo** [stenzek/duckstation#579]
It plays the wrong music for the menus and world map , when you finish the level and in some levels.
This is how the music should have sounded like in the first levels and on the menu : https://youtu.be/87GWSv3OFUM
Here is a picture of some debug info when the wrong music plays in the main menu:
![image](https://user-images.githubusercontent.com/33392696/86108505-e7e6a000-bacb-11ea-8fa1-96c219588000.png)

**Comment by Zet-sensei** [comment]
After a rapid test betwenn all versions of the game.
Only the JPN version is affected.

Tracks are shifted by 1 when readed by the emulator.
It plays Track 29 rather than Track 30 on the menus (for example).
Same problem in-game.

**Comment by RibShark** [comment]
This is an issue with the .cue handler, converting the image to .chd causes the bug to disappear. The issue is that a 2-second pregap is added to _all_ tracks that do not have a pregap specified, rather than just track 01. In Rayman's case, the audio tracks (barring track 02) do not have a pregap, and so adding one caused the audio to be played back from the wrong LBA.
