### ISSUE TITLE
All crop modes seem to be slightly wrong in Lupupu Cube - Lup Salad (Japan)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#596]
This is what the game looks like on my TV. Note the amount of space between the bottom row of letters and the bottom of the screen. 

![IMG_20200709_083058](https://user-images.githubusercontent.com/31968468/86977690-8f488e80-c1c0-11ea-8079-cbfffb87bbb4.jpg)

Here it is in Duckstation with crop mode set to "only overscan area". This one speaks for itself. 

![SLPS-00416_2020-07-09_08-41-25](https://user-images.githubusercontent.com/31968468/86977781-bb640f80-c1c0-11ea-8085-80cb80e2f44e.png)

Here it is with crop mode set to "none". Notice how there's slightly more space under the bottom letters than on a real TV?

![none](https://user-images.githubusercontent.com/31968468/86977938-11d14e00-c1c1-11ea-8ee1-d1fdc1cf713e.png)

Here it is with crop mode set to " all borders". Notice how the whole image is now distorted and stretched? Especially the hiragana at the top. 

![SLPS-00416_2020-07-09_08-51-27](https://user-images.githubusercontent.com/31968468/86978207-a045cf80-c1c1-11ea-88d6-deed72386641.png)

**Comment by ggrtk** [comment]
They're not necessarily wrong, your television is likely just less conservatively calibrated and shows more vertical overscan than DuckStation's overscan cropping mode does. DuckStation crops a standard 8 lines top and 8 lines bottom (each doubled for 480i). "All Borders" should not really be used as a measure of accuracy because it just shows what is being outputted from VRAM without taking video signal encoding into account.

**Comment by stenzek** [comment]
Will probably need custom per-game settings.
