### ISSUE TITLE
Opening .ZIP .RAR or .7Z

### ISSUE THREAD

**Issue by Richard-L** [stenzek/duckstation#620]
Would you consider adding the ability to open these archive files directly, without having to extract them first?

Many thanks.

**Comment by stenzek** [comment]
The main issue is archive formats are not "seekable". In other words, you can't say "I want to read offset 2352 from file xyz" without decompressing the whole thing first.

Creating an "index" may be possible, then you can seek to the closest "block" and decompress from there. The other alternative is just to decompress into memory first, which I'll probably add when I add the option to preload disc images to RAM.

zip should be doable as I already ship zlib. RAR most likely no, because of license concerns. 7z, perhaps, depending on whether I pull in the libraries for the auto-updater when I write that.

My best advice would be to just use chd. It's compatible with most of the big-name emulators now, and compresses better than archive formats anyway.

**Comment by Richard-L** [comment]
Perhaps with the feature to load images into RAM, is a parsing of zip or 7z more plausible?

**Comment by TzakShrike** [comment]
Yeah I was gunna say exactly this. If loading from a compressed file forced a full preload into RAM, then it's seekable.

**Comment by Richard-L** [comment]
Yeah I think even just good old zip would be enough.
