### ISSUE TITLE
Duckstation isn't including or detecting .iso games

### ISSUE THREAD

**Issue by ZeraX7** [stenzek/duckstation#631]
I noticed that many games weren't added to the emulator even after updating redump and scanning folders on version 0.1-1281-gf67862d.
Turned out all the games that weren't added have .iso extension but I can run them fine if I manually select them from System- > Start Disc
![duckstation](https://user-images.githubusercontent.com/68525464/87895023-0eee1d00-ca4d-11ea-8588-9c23bdd4b8ba.JPG)

**Comment by stenzek** [comment]
What format are these .iso games in? Usually .iso only stores the data part of CD-ROM sectors (2048 bytes). Most PlayStation games have additional data in the remaining parts of the sector (2352 bytes) including XA audio/FMVs/etc, so you shouldn't be dumping your games as ISOs.

I could add an ISO reader to the image handler, and generate the extra 304 bytes on the fly, I'm just not sure it's worthwhile.

**Comment by stenzek** [comment]
Also, ISO files won't launch at all. So if they're starting they must not be in ISO format.

Could you enable the log (advanced options -> set it to developer level, and enable system console), rescan your games, and look for any errors? It should say why it was not included in the game list.

**Comment by ZeraX7** [comment]
I'm not very knowledgable in that stuff so I will just post the log file
[log.txt](https://github.com/stenzek/duckstation/files/4945287/log.txt)

**Comment by stenzek** [comment]
Okay, so your issue with some of the games is the cuesheets - the filename in the .cue has to match the .bin.

You can download the cuesheets from redump and rename your bin files to match, or edit them yourself.

Obviously the .iso games aren't going to load, assuming they are actually iso format. If they're raw dumps in bin/cue format, just with an iso extension, they should run fine after renaming.

One last note, the game list won't show .bin files on their own. This is because of multi-track games, if I showed .bin files in the game list you'd get the same game in there multiple times! You need a cue sheet for them to show up, but .bin files can be launched directly.

**Comment by ZeraX7** [comment]
Thanks a lot!
I fixed the cuesheets problem and the games now appear!
