### ISSUE TITLE
Cheat Support

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#65]
maybe later on you could add Gameshark codes

**Comment by TzakShrike** [comment]
I have a dumb request for this enhancement.
(Depending on implementation) Can it be called something other than Cheats? Cheats has always seemed to me like a weird way to describe this feature, because personally I use this kind of feature for several things, but pretty much never for cheating.
How about "RAM Freeze" or "Memory Lock" or "Memory Manipulation" or similar?

**Comment by vannessqn** [comment]
please support retroarch ps1 cheat if u can, they have a whole ps1 cheat database so we wouldnt have to add manually

**Comment by stenzek** [comment]
Basic cheat support is added in the latest build. Not all commands are supported yet, and there isn't an editor in the Qt frontend. Will add these later.
