### ISSUE TITLE
Worms Pinball (Europe) (En,Fr,De,Es,It) ball glitches

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#66]
could be related to #48

**Comment by stenzek** [comment]
Should be fixed in the latest build. But I'm still not sure if the fix is correct, as I haven't hardware tested it yet.

**Comment by benderscruffy** [comment]
goes ingame now but the ball is glitchy 
![worms](https://user-images.githubusercontent.com/2696404/76503850-8e595780-6481-11ea-90e4-e9af3ade8f83.PNG)

**Comment by stenzek** [comment]
You're right about there being a connection between the pinball games. With the odd/even line drawing implemented, this fixes the ball display.

It does have combing artifacts, but that's because the game is drawing interlaced and not the GPU itself, so the force progressive option has no effect. Long term we'll probably need a deinterlacer for games like this.

**Comment by stenzek** [comment]
Should be fixed in latest master. Make sure you disable the force progressive scan option.

This one is fine with the hardware renderers, since it doesn't use the rendering-to-active-field trick to check which field is being displayed.

**Comment by benderscruffy** [comment]
fixed
