### ISSUE TITLE
[Feature Request] Faster CD-ROM Read Speeds

### ISSUE THREAD

**Issue by brianblakely** [stenzek/duckstation#701]
Many games work great with CD reads faster than 2x.  Please provide read speed options that are as fast as the emulator can support.

**Comment by stenzek** [comment]
Straightforward to implement, but there is a limited number of scenarios where this will actually work. Any FMVs or XA audio would have still have to read at 2x speed, otherwise they'll break. Games like FF8 which stream FMVs but don't use XA audio will break.

Basically, it's only useful for actual data loading, and it's difficult to tell the difference between that and streaming audio/FMVs (more so the latter).

**Comment by brianblakely** [comment]
Beetle's implementation does not mention FMV, but it does mention audio.  It could be that the FMV detection is not documented.

https://github.com/libretro/beetle-psx-libretro/blob/master/mednafen/psx/cdc.cpp#L1091

**Comment by brianblakely** [comment]
Did some more testing with Beetle faster CD read settings.

FMVs which do not use streaming audio do play back faster than they should, and successive FMVs with this issue appeared to softlock (although the game might have been catching up to the ultra-fast FMV).  This was easy to fix in RetroArch by rewinding, opening the core options, reverting to native CD read speed, watching the FMV normally, and then setting the read speed higher again when gameplay resumed.

FMVs which use streaming audio trigger the native CD read speed branch and therefore play normally without needing to fiddle any settings back and forth.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/8ba93b36a03fb57b7b68a5274a643bd8865b203c
