### ISSUE TITLE
Observations with resolution switching

### ISSUE THREAD

**Issue by Richard-L** [stenzek/duckstation#735]
I'm on 0.1-1467-g5df116b6.

Few thoughts regarding resolution:

- When using "automatic based on window size", it would be nice to see what resolution it sets to in window, and then again when going into full-screen mode. Latter perhaps via an OSD message? Former perhaps just in the status bar of the emulator, together with emulation speed, FPS, etc.
- When using the hotkeys to change to a higher/lower resolution, an OSD message telling what resolution has been switched to would be nice, regardless of whether in windowed or full-screen mode.
- After having switched, the chosen resolution should be selected in GPU options accordingly. Currently it's always stuck at "automatic" if that was chosen prior.

**Comment by stenzek** [comment]
> When using "automatic based on window size", it would be nice to see what resolution it sets to in window, and then again when going into full-screen mode. Latter perhaps via an OSD message? Former perhaps just in the status bar of the emulator, together with emulation speed, FPS, etc.
> When using the hotkeys to change to a higher/lower resolution, an OSD message telling what resolution has been switched to would be nice, regardless of whether in windowed or full-screen mode.

Fixed in https://github.com/stenzek/duckstation/commit/26aa627deb45277e5e6784a85cb0e85da67c0b64

> After having switched, the chosen resolution should be selected in GPU options accordingly. Currently it's always stuck at "automatic" if that was chosen prior.

The hotkey for changing resolutions doesn't actually commit the change. That's why when you change some other setting after using a hotkey to change the resolution, it'll revert back to whatever was set in the UI. Same with the PGXP toggle. I don't plan to change this, as it's intended to be a debug tool. But also because currently there's no way for the settings dialog to listen for external config changes.
