### ISSUE TITLE
Implement mouse capture/relative mouse movement

### ISSUE THREAD

**Issue by Konkonfaux** [stenzek/duckstation#739]
The problem is that the mouse still work outside the game, so mouse look is severly limited in game. Any way of disabling mouse in fullscreen mode?
This isn't well explained. So in game, mouse look stops when the mouse reaches the screen border.

**Comment by CookiePLMonster** [comment]
It should be easily fixable by switching DuckStation to use relative mouse movements instead of absolute. Right now absolute movements are used for both GunCon and PS Mouse, and while it's probably okay for the former, it causes bugs like these for the latter.

**Comment by Konkonfaux** [comment]
The issue is still happening. Is that a toggable option somewhere?

**Comment by stenzek** [comment]
@CookiePLMonster absolute positioning is needed for guncon, as it needs to convert the position to horizontal clocks and lines. That's why I haven't implemented it in the libretro core yet.

@Konkonfaux: What you're asking for is known as mouse capturing + relative mouse mode. I haven't implemented it, but will consider in the future.

**Comment by Konkonfaux** [comment]
Okay. Thank you for answering.

**Comment by CookiePLMonster** [comment]
This is a valid issue, it shouldn't be closed.

**Comment by Skynet19972029** [comment]
I see this was reported.
Sorry. I should have checked.

**Comment by stenzek** [comment]
Implemented in https://github.com/stenzek/duckstation/commit/8bb5ff47eb721d278c643d320c25556c87cef351 (you'll need to switch to the preview channel if you want to use it now, before I push the next dev build).

**Comment by LukasThyWalls** [comment]
I'm playing _Resident Evil: Survivor_, and using the GunCon the mouse goes outside the window constantly making harder to play, because you can clic other windows, lost focus, etc. Also i'm using the NoGUI, and the "Pause when lost focus" doesn't work, making that worse (i tried with QT and it worked).

Seems very related to me to this issue, although the OP talk about the PS Mouse, both PS Mouse and GunCon are played with the real mouse, but if it's needed a new issue i can post it.

Using 0.1-3919-g4875b2ec (dev).
