### ISSUE TITLE
40 Winks won't boot past BIOS when Auto Analog mode is enabled

### ISSUE THREAD

**Issue by ds22x** [stenzek/duckstation#740]
Happens with both standalone and Libretro versions.
If you enable Auto Analog mode, the game will refuse to continue past the BIOS screen, with the message that it has switched from analog to digital controls.
On standalone you can continue past the hang by toggling analog back on.

**Comment by stenzek** [comment]
I warned people that this would break games, but people kept insisting for it anyway............

**Comment by stenzek** [comment]
As a side note, I'm aware there's no other way to get analog in the libretro core for games which don't enable it themselves, since there's not enough buttons to have a toggle.

What I might do in the future is add a chord which must be held for a few seconds, or something (to reduce the risk of it interfering with games).
