### ISSUE TITLE
multi game have problem on Separate Card Per Game

### ISSUE THREAD

**Issue by phoe-nix** [stenzek/duckstation#750]
if choose "Separate Card Per Game (Game Title)" or "Separate Card Per Game (Game Code)",
memory card file will create by Game Title or Game Code, so in disc 2, cant load save from disc 1,
 Should add Separate Card Per Game (Save Code)?

**Comment by stenzek** [comment]
This is working as intended - there's no "shared" code between discs, and there's no way to know which name the game will save the slot with before it's created.

Personally I like this behavior - it gives you more save slots. Finish up disc 1, swap to disc 2, and then save to a new card.

But I know some people don't :) I'm going to add playlist support in the standalone UI soon, and when you load a playlist it will save based on the playlist's filename, which you can remove the "(Disc N)" suffix from.

**Comment by phoe-nix** [comment]
and, setting files and memory card files all store in Disc C, can you change it into emu path?

**Comment by stenzek** [comment]
Do you mean how it saves to Documents/DuckStation ? You can save to the directory of the emu by creating a file named `portable.txt` in the directory with the exe (same as Dolphin).

**Comment by phoe-nix** [comment]
lol, thank u so much, and i update Chinese language translation. hope u can add it.

**Comment by stenzek** [comment]
Latest build has an option in memory card settings "Use Single Card For Playlist". Enabling this will use a single card for multi-disc games, but you **must** use a playlist (m3u), otherwise it will have no effect.

I left it disabled by default in the libretro core, as people were already using playlists there and I didn't want them to "lose" their saves. But standalone has it enabled by default.
