### ISSUE TITLE
Save state incompatible

### ISSUE THREAD

**Issue by nickp85** [stenzek/duckstation#763]
Since Libretro was hacked, I decided to try and manually update Duckstation by downloading the SO file and installing it.  I did that and now when I load Final Fantasy VII and load state, it tells me save state is incompatible, expecting version 40 but got version 39.  I also cannot load anything from memory card.  The files are in the directory but when I load the memory card there are no saves in it.

How can I get my save state working to resume my FFVII game?

Thanks

**Comment by stenzek** [comment]
You should not rely on save states for saving your progress - I have to break them from time to time because new variables get added to fix bugs. I try to keep this to a minimum (last change was over a month ago), but it is unavoidable.

Memory cards should be working fine. I'll double-check...

As for getting your save back, you can download the last version with the old save state version here: https://github.com/stenzek/duckstation/runs/988162274 (go to Artifacts on the top-right and download your platform, GitHub login required). Then get to a save point, save to the memory card, and update to the latest version again.

**Comment by stenzek** [comment]
Memory cards in libretro seem to be working okay from a quick test. There was an issue with the single-card-for-playlist setting not behaving as intended when disabled, but doubt that was the problem.

Might want to double-check that your save directory in RetroArch is set. DuckStation should create .mcd files.
