### ISSUE TITLE
Crash Bash (PAL) is too fast

### ISSUE THREAD

**Issue by AlfyGame** [stenzek/duckstation#798]
**Version**
0.1-1600-g032127a7

**Issue**

Crash Bash (PAL) is a little bit fast, VO is not in sync
Emulation speed settings are in default
Video: https://youtu.be/8aZiFX_BrNc?t=793 (13:13)

**Comment by stenzek** [comment]
Seems to be running at 25fps internally instead of 20fps in that cutscene. US version is fine, as is forcing NTSC timings..

**Comment by ToniBC** [comment]
Yes, the same thing happens with cinematics, the audio is out of sync, tested with the Libretro version. In other emulators it works well, so it is not a problem with the pal version, it is a bug that makes the cinematics are as advanced to the audio.

**Comment by stenzek** [comment]
It happens because the CPU is still running too fast. Under locking would probably fix it. Other emulators (e.g pcsxr) cheat and just run the CPU slower, which isn't exists accurate. Mednanen is the only one which gets it right.

Idle skipping fixes this as well, but it breaks other games and I need to figure out why.

**Comment by stenzek** [comment]
Mostly fixed with https://github.com/stenzek/duckstation/commit/fdc7066ead2196886516c8845af870334722f00d, still some very slight drift.
