### ISSUE TITLE
Widescreen hack is not saved in "User Settings"

### ISSUE THREAD

**Issue by Richard-L** [stenzek/duckstation#815]
The checkmark for widescreen mode if chosen (only) via user settings does not stick when DS is restarted.
![image](https://user-images.githubusercontent.com/4934209/91669257-d04f8600-eb13-11ea-98a7-e4c6d9283875.png)

Each time it is reset to "default".

My GPU settings 
![image](https://user-images.githubusercontent.com/4934209/91669276-f4ab6280-eb13-11ea-93d0-6286ae028cc3.png)

Can you reproduce this?

**Comment by stenzek** [comment]
Should be fixed by https://github.com/stenzek/duckstation/commit/bf85fbe331c9a6998d0de1917626cbfebeb1d1e2

**Comment by Richard-L** [comment]
Haven't had the issue again. Think you might close :)

**Comment by DonelBueno** [comment]
Now the "Aspect Ratio" option is not saved and "Integer Scaling" is always on.

It also would be nice to have "PGXP Texture Correction" option in per-game settings, since some games have skewed textures with in on.

**Comment by stenzek** [comment]
@DonelBueno are you using the latest build? Those settings seem to be working fine for me.

**Comment by stenzek** [comment]
PGXP texture correction can be forced off with a compatibility override: https://github.com/stenzek/duckstation/commit/daa5e02853c3788693e5a5a5d061ab66cdb47def

Scaling issue should be fixed by https://github.com/stenzek/duckstation/commit/51c595759f4faceb72928f69452294bdcb052c15

Let me know if it's still happening.

**Comment by DonelBueno** [comment]
Everything is working as expected, thank you!
