### ISSUE TITLE
Broken rendering Windows x64 libretro port [8d5a6ac]

### ISSUE THREAD

**Issue by afjara** [stenzek/duckstation#852]
Hello!

I've just updated the duckstation core to the latest development build `8d5a6ac` on my RetroArch Windows 10 x64 setup. When a game is launched, I can only see half of the screen when BIOS logo starts. After that, the games i tried may show a random a vertical misaligned position over the screen. Please take a look to the attached screenshot.

Step to reproduce the issue:

1. Start a PSX image in RA
2. Open core options
3. Change renderer to: Hardware OpenGL or Auto
4. Keep other settings at default values
5. Close content
6. Rerun or load another PSX image

Tested both with a Intel HD 610 laptop and a GTX 950 desktop. RA video driver set to OpenGL.

![Spyro the Dragon (USA)-200915-011918](https://user-images.githubusercontent.com/45073924/93166580-29631080-f6f5-11ea-8afc-121d4094cfbe.png)

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/352a3405e80b87ffe3ad9b0e583d02968c6a1f94

As an aside, if you have other options OpenGL is the last renderer you should use. There's a bunch of games which have off-by-one coordinate issues, and it's by far the slowest. I only keep it around for hardware which can't use DX11/Vulkan, which works much better. You don't even have to change your RA core driver, just set it to either of the others in the duckstation core settings and it'll auto-switch.

**Comment by afjara** [comment]
Thanks stenzek!

duckstation core GPU renderer set to D3D11 as recommended 👍
