### ISSUE TITLE
Gun and mouse not working in Libretro

### ISSUE THREAD

**Issue by ToniBC** [stenzek/duckstation#876]
In the Libretro port, if you select the Guncon, mouse and other devices, an error appears that they are not supported. Only the normal controller and dualshock work.

Apparently, the implementation of these devices does work, but not in the libretro port.

Also another minor fact is that in the libretro port the controls are selected in the emulator options, and not in the controls, as in almost all other cores. But this I think would not generate errors.

I wanted to test if Duckstation emulated the gun in Hardware mode and not in software mode like others. But at the moment it doesn't work.

Thank you.

**Comment by stenzek** [comment]
Lightgun isn't implemented in the libretro port because there's no way of querying the window size. The pointer input device might map to the av config size, but I haven't looked into it. Not a priority because I don't use the libretro core nor have much interest in it, but maybe I'll get around to it some day.

The controller type setting is there because that's how it works in the standalone version, and that code is shared. It might be possible to work around, but having a single code path is more important than "doing things the libretro way" to me.

GunCon works fine in both hardware and software modes in standalone. I have a branch with the Justifier implemented, but it still needs some tweaking.

**Comment by ToniBC** [comment]
The window size problem always causes problems, because multiplying the resolution seems to be that things do not fit well and the crosshairs controlled with the mouse does not seem to work quite well.

I understand that the libretro port is not a "priority", each one with their project focuses it where they want, but I think that, from the tests carried out, the libretro versions are always better. For example, it's like using your own graphics engine or Unreal Engine, for example, I understand that your own gives you more freedom to put whatever you want, but moving to Unreal gives you some tools and stability than your own.

But each one with his project to do as he can.

In the meantime, then nothing, we will have to wait to see if one day it is implemented to be able to use the mouse as a gun.

As always, thank you very much for responding.

**Comment by stenzek** [comment]
> The window size problem always causes problems, because multiplying the resolution seems to be that things do not fit well and the crosshairs controlled with the mouse does not seem to work quite well.

Not sure why this is a problem, I had no issues utilizing it in my frontends. The resolution has no connection to the window size, and isn't even used for determining the internal position of the GunCon. I just use the mouse position and the window size, normalize it to 0..1, and convert that to 8MHz clock ticks.

**Comment by ToniBC** [comment]
In Beetle PSX HW, they commented a long time ago, that the mouse support in Hardware mode did not work because the resolution could not be determined, but in software mode it does work. It seemed strange to me because other emulators could, therefore, something fails or they try to implement it super precisely and with that it is not possible.

In software mode, with Beetle PSX HW you can use the mouse and even the touch screen.

I'm not a programmer, I can't tell you, but I'm surprised that you can't know the size of the window, and more in full screen, because the video options do come out, but as I said, I'm not a programmer, I'm just looking forums and comments and reporting bugs that I find or inform me.

**Comment by ggrtk** [comment]
> In Beetle PSX HW, they commented a long time ago, that the mouse support in Hardware mode did not work because the resolution could not be determined, but in software mode it does work. It seemed strange to me because other emulators could, therefore, something fails or they try to implement it super precisely and with that it is not possible.

I don't know where you read this, but I don't believe this is true. The lightgun mouse cursor doesn't show up in Beetle's hardware renderers because cursor drawing functionality was never added, not because of resolution issues. 

As for the libretro port, `RETRO_DEVICE_POINTER` and `RETRO_DEVICE_LIGHTGUN` both provide normalized window coordinates.

**Comment by ToniBC** [comment]
Hopefully it can be implemented well, I like how this emulator works, so far I have found few errors and the games work well.

I just tested the gun with the standalone version and with no problems.

Now it only remains to implement it in the Libretro port.

**Comment by stenzek** [comment]
Merged with #1064
