### ISSUE TITLE
m3u playlist QoL improvements

### ISSUE THREAD

**Issue by bajolzas** [stenzek/duckstation#937]
Hi, I'm not sure if this is (already) possible; but I would like to have the option for DS to ignore the individual discs of a multi disc game already present on a m3u playlist when scaning a game folder (as to not have duplicates); or at least give us the option to manually remove entries.

It would also be nice if the emulator could detect the last disc played on such a playlist instead of always starting on disc 1.

**Comment by stenzek** [comment]
This has been asked numerous times, and it's not possible at this point because each item in the game list is entirely independent.

I'm considering adding additional per-game metadata, and "hiding" an entry could be possible with this.

> It would also be nice if the emulator could detect the last disc played on such a playlist instead of always starting on disc 1.

The save state should do this when resuming.

Really, if you're using the Qt frontend, it's not designed for playlists (it's more of a libretro thing), just use the game list. If you need a memory card across all disks, use game properties and override the shared card path.
