### ISSUE TITLE
Two Game-Entries for Spyro the Dragon EU

### ISSUE THREAD

**Issue by GitToTheHub** [stenzek/duckstation#955]
For the Game "Spyro the Dragon (EU)" two game entries are shown in the UI:

![spyro_the_dragon_eu_double_entry_duckstation](https://user-images.githubusercontent.com/13721821/95665642-4f3fd180-0b4a-11eb-8465-1dd39c8f896b.png)

The game has 4 files:

![spyro_the_dragon_eu_double_entry_files](https://user-images.githubusercontent.com/13721821/95665649-62eb3800-0b4a-11eb-8d0c-e036c35888ed.png)

The **first Entry** points to **Spyro the Dragon (EU).cue**, 1 Track, Mode 2/Raw, Start: 00:02:00 (LBA 150), **Length: 69:13:66 (LBA 311541)**
The **second Entry** points to **Spyro the Dragon (EU).img**, 1 Track, Mode 2/Raw, Start: 00:02:00 (LBA 150), **Length: 69:11:66 (LBA 311391)**

The Length is different in the entries. I don't know if it makes any difference which entry i use.

Game-Code: SCES-01438
Title: Spyro the Dragon (EU)

**Comment by stenzek** [comment]
That's because img files are currently included in the game list. If you use .bin instead (and update your cuesheet) it will only be listed once.

**Comment by GitToTheHub** [comment]
ok so the emulator lists only correctly games made in .bin-Format? I thought more like that: If there is a .bin- and .cue-File, the .bin-File is not extra listed, what's currently the status. If there is a .img-File and .cue-File, i thought that there could be the same logic and the .img-File will not extra be shown?

**Comment by stenzek** [comment]
I was under the impression that bin files are usually paired with cue files. The img extension was usually paired with other formats like ccd? And ccd is not supported, so I show the img.

The logic is simple, bin files are not shown in the game list at all, but you can open them manually.

**Comment by GitToTheHub** [comment]
I was looking to .cue-File and the content is:
```
FILE "Spyro the Dragon (EU).img" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
```
So it's pointing to the .img-File. I think the .ccd-File is not necessary. So the logic would be to lock first the cue-File and the pointing images and exclude them from the list. What do you think?

**Comment by TzakShrike** [comment]
CloneCD stores optical disc images in .img files and generates additional CloneCD Control Files (with .ccd extension) for each image to hold the necessary metadata.  to mark the properties of a CD/DVD image. It may also come with a subchannel file (usually .sub). 

Raw .img disk images of optical media contain a raw image of **all** the tracks in a disc (which can include audio, data and video tracks). In the case of CD-ROMs and DVDs, these images usually include not only the data from each sector, but the control headers and error correction fields for each sector as well.

The CUE/BIN format stores disc images in .bin files, which are functionally equivalent to .img image files, and use .cue files as descriptor files.

It's worth noting that the cue/bin format can support monolithic bin files, or can split them into separate bin files as separate tracks, etc, containing less data (excluding irrelevant sectors for audio tracks, for example). img files are monolithic, and will be identical to a standard full disc bin file.

The GNU Project's ccd2cue can convert a CCD file to a cue sheet.

So, I think that that must've been what happened in your case. Someone made that disc image with CloneCD as a way to get the _**subchannel information**_ along with everything else, however that person actually wanted to use cue/bin, and used ccd2cue to make the cuesheet. Preparing the cuesheet doesn't change the extension of the img file, because it doesn't need to, the extension is irrelevant. img/bin are storing the same data, and both the ccd file and the cuesheet are pointing at the same file, allowing it to be burned/read either way.

**Comment by GitToTheHub** [comment]
@TzakShrike 
Wow, thank you really much for your very detailed explanation!
I understand now the structure of the disk i've here. So the CloneCD Disk Image is already converted to the cue/bin format? I have a .sub-File from CloneCD here too for that game. Do you think, I can everything remove, leave the cue- and img-file there and rename the img-file to bin-file? On my first comment on this issue i attached the file structure of that image. So the -sub-File is irrelevant?

**Comment by TzakShrike** [comment]
I don't know if that game uses subchannel information for copy protection, because a bunch of PAL games did. I'd be inclined to keep it. CUE files are easily readable in any text editor, so open that up and change the reference from .img to .bin if you want. Then you can rename the file too. That'll stop it from showing up twice in DuckStation.

DuckStation doesn't support CCD files, so that file is being ignored, however DuckStation **does** support subchannel information files (sub or sbi? not sure) as long as they're named identically to the cue file.

If you remove the ccd file you won't have any way to replicate the disc with subchannel information intact, and it's not unlikely that the subchannel information is required to play the game correctly.

**Comment by GitToTheHub** [comment]
@TzakShrike Thank you. Again, great informations :) I changed the img to bin and edited the cue-file and now i only have one entry in the list. Thank you. I don't need the ccd file, because i don't want to burn the image to disk.
