### ISSUE TITLE
Jackie Chan Stuntmaster (USA) crashes in Cached Interpreter/Recompiler mode

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#98]
happens on all renderers

**Comment by stenzek** [comment]
Seems to be an issue with the code cache/recompiler, it works in interpreter mode.

The game's interrupt handler, among other things, checks a flag, then sets it, re-enables interrupts, then clears the flag. It expects the handler to be executed again after re-enabling interrupts, since it never cleared it in interrupt controller, and since the flag is set, jumps to the real handler. In the cached interpreter/recompiler, the entire block is executed without dispatching any new interrupts, so the case where the flag is set and it jumps to the real handler never happens, instead it's just a never-ending loop of interrupt dispatches.

Not a straightforward solution, I'll probably have to check for interrupts on `mtc0 sr` and exit the block early in such a case, which isn't ideal..

**Comment by DarkFrost89** [comment]
Jackie Chan Stuntmaster USA Version Problem
Stuck After The Main Video
Tested İnterpenter, Recompiler and Cached İnterpenter
https://youtu.be/jJCPRtpzRB8

**Comment by stenzek** [comment]
Fixed with https://github.com/stenzek/duckstation/commit/ad727c79918c52548e228bda3f57233f26c38521
